/* ============================================================
   THE APPOINTMENT SUMMARY — the document the person brings · en-US

   ⚠️ Reasons live in ../pt-BR/resumo.ts. Two carry over:

   THE REGISTER IS MORE FORMAL than the rest of the app. These are
   clinical table labels, not the conversational voice of the Home.
   Whoever reads it on the other side has two minutes and is looking for
   numbers.

   AND THE PROVENANCE GOES WITH IT, on the last line. Whoever receives
   this by message needs to know it came out of a tracking app, not a
   medical record — and that the numbers are what the PERSON logged.
   ============================================================ */

export const resumo = {
  medicacao: 'Medication',
  medicamento: 'Medication',
  dose: 'Dose',
  cadencia: 'Cadence',
  tempoDeTratamento: 'Time in treatment',
  emDias: (dias: number) => `${dias} days`,
  aplicacoes: 'Injections',
  aplicacoesValor: (feitas: number, previstas: number) => `${feitas} of ${previstas} expected`,

  peso: 'Weight',
  inicioAtual: 'Start → current',
  variacao: 'Change',
  em: 'Over',
  metaDePeso: 'Weight goal',

  /* ⚠️ EACH SYMPTOM WITH ITS OWN UNIT. Nausea, hunger and energy are
     zero-to-ten scales; sleep is clock hours. A section labeled "(0–10)"
     put seven hours of sleep on the same ruler as a nausea seven. */
  sintomas: 'Symptoms',
  mediaDosDias: (comResposta: number) => `Average of the last 14 days · ${comResposta} answered`,
  semRespostas: 'No answers in the last 14 days',
  nausea: 'Nausea',
  fome: 'Hunger',
  energia: 'Energy',
  sono: 'Sleep',
  de10: ' of 10',
  horas: ' h',

  examesRecentes: 'Recent labs',
  anotacoes: 'Notes for the appointment',
  semAnotacoes: '(no notes)',

  cabecalho: (nome: string) => `TREATMENT SUMMARY — ${nome}`,
  paraDoutor: (doutor: string) => ` · for ${doutor}`,
  origem: 'Generated by the app from the person’s own logs.',

  nomeDoDocumento: 'Treatment summary',
  enviadoPara: (doutor: string) => `Sent by you to ${doutor}`,
  enviado: 'Sent by you',
};
