/* ============================================================
   AS FOTOS DOS ALIMENTOS

   ARQUIVO GERADO por scripts/gerar-fotos.mjs a partir do que existe em
   assets/images/alimentos/. Para acrescentar uma foto, ponha o arquivo lá com o id do
   alimento no nome e rode:

     node scripts/gerar-fotos.mjs

   A tela de consulta procura nesta ordem: a foto DAQUELE alimento, a
   foto da prateleira dele, e por último o painel de cor — que continua
   dizendo alguma coisa, porque a cor vem do nutriente em destaque.

   A prateleira existe para o meio do caminho. Com vinte fotos entre
   duzentas e vinte e quatro, dezenove telas caem no painel de cor; com
   uma foto de "carnes e aves", todas as carnes já abrem com imagem
   enquanto a específica não chega.
   ============================================================ */
const POR_ITEM: Record<string, any> = {
  'abacate': require('../../assets/images/alimentos/abacate.jpg'),
  'abacaxi': require('../../assets/images/alimentos/abacaxi.jpg'),
  'abobora': require('../../assets/images/alimentos/abobora.jpg'),
  'acai-tigela': require('../../assets/images/alimentos/acai-tigela.jpg'),
  'acaraje': require('../../assets/images/alimentos/acaraje.jpg'),
  'achocolatado': require('../../assets/images/alimentos/achocolatado.jpg'),
  'almondega': require('../../assets/images/alimentos/almondega.jpg'),
  'amendoa': require('../../assets/images/alimentos/amendoa.jpg'),
  'amendoim': require('../../assets/images/alimentos/amendoim.jpg'),
  'arroz-carreteiro': require('../../assets/images/alimentos/arroz-carreteiro.jpg'),
  'arroz-frito': require('../../assets/images/alimentos/arroz-frito.jpg'),
  'arroz-integral': require('../../assets/images/alimentos/arroz-integral.jpg'),
  'arroz': require('../../assets/images/alimentos/arroz.jpg'),
  'atum-lata': require('../../assets/images/alimentos/atum-lata.jpg'),
  'aveia': require('../../assets/images/alimentos/aveia.jpg'),
  'bacalhau-natas': require('../../assets/images/alimentos/bacalhau-natas.jpg'),
  'bacalhau': require('../../assets/images/alimentos/bacalhau.jpg'),
  'bagel-cream-cheese': require('../../assets/images/alimentos/bagel-cream-cheese.jpg'),
  'baiao': require('../../assets/images/alimentos/baiao.jpg'),
  'banana': require('../../assets/images/alimentos/banana.jpg'),
  'barra-cereal': require('../../assets/images/alimentos/barra-cereal.jpg'),
  'barra-proteina': require('../../assets/images/alimentos/barra-proteina.jpg'),
  'barreado': require('../../assets/images/alimentos/barreado.jpg'),
  'batata-doce': require('../../assets/images/alimentos/batata-doce.jpg'),
  'batata-frita': require('../../assets/images/alimentos/batata-frita.jpg'),
  'batata': require('../../assets/images/alimentos/batata.jpg'),
  'beterraba': require('../../assets/images/alimentos/beterraba.jpg'),
  'bibimbap': require('../../assets/images/alimentos/bibimbap.jpg'),
  'bife-a-cavalo': require('../../assets/images/alimentos/bife-a-cavalo.jpg'),
  'bife-milanesa': require('../../assets/images/alimentos/bife-milanesa.jpg'),
  'biscoito-recheado': require('../../assets/images/alimentos/biscoito-recheado.jpg'),
  'biscoito-salgado': require('../../assets/images/alimentos/biscoito-salgado.jpg'),
  'bobo-camarao': require('../../assets/images/alimentos/bobo-camarao.jpg'),
  'bolo-chocolate': require('../../assets/images/alimentos/bolo-chocolate.jpg'),
  'brocolis': require('../../assets/images/alimentos/brocolis.jpg'),
  'burrito-frango': require('../../assets/images/alimentos/burrito-frango.jpg'),
  'camarao': require('../../assets/images/alimentos/camarao.jpg'),
  'canja': require('../../assets/images/alimentos/canja.jpg'),
  'carbonara': require('../../assets/images/alimentos/carbonara.jpg'),
  'carne-moida': require('../../assets/images/alimentos/carne-moida.jpg'),
  'carne-panela': require('../../assets/images/alimentos/carne-panela.jpg'),
  'castanha-caju': require('../../assets/images/alimentos/castanha-caju.jpg'),
  'castanha-para': require('../../assets/images/alimentos/castanha-para.jpg'),
  'cenoura': require('../../assets/images/alimentos/cenoura.jpg'),
  'cereal': require('../../assets/images/alimentos/cereal.jpg'),
  'ceviche-peixe': require('../../assets/images/alimentos/ceviche-peixe.jpg'),
  'charuto': require('../../assets/images/alimentos/charuto.jpg'),
  'chili-carne': require('../../assets/images/alimentos/chili-carne.jpg'),
  'chocolate': require('../../assets/images/alimentos/chocolate.jpg'),
  'chuchu': require('../../assets/images/alimentos/chuchu.jpg'),
  'contrafile': require('../../assets/images/alimentos/contrafile.jpg'),
  'corvina': require('../../assets/images/alimentos/corvina.jpg'),
  'costelinha': require('../../assets/images/alimentos/costelinha.jpg'),
  'cottage': require('../../assets/images/alimentos/cottage.jpg'),
  'couve-flor': require('../../assets/images/alimentos/couve-flor.jpg'),
  'couve': require('../../assets/images/alimentos/couve.jpg'),
  'coxao-mole': require('../../assets/images/alimentos/coxao-mole.jpg'),
  'coxinha': require('../../assets/images/alimentos/coxinha.jpg'),
  'crepe-carne': require('../../assets/images/alimentos/crepe-carne.jpg'),
  'crepe-frango': require('../../assets/images/alimentos/crepe-frango.jpg'),
  'crepe-queijo': require('../../assets/images/alimentos/crepe-queijo.jpg'),
  'crepioca': require('../../assets/images/alimentos/crepioca.jpg'),
  'croissant-presunto-queijo': require('../../assets/images/alimentos/croissant-presunto-queijo.jpg'),
  'croquete': require('../../assets/images/alimentos/croquete.jpg'),
  'curry-grao-de-bico': require('../../assets/images/alimentos/curry-grao-de-bico.jpg'),
  'cuscuz-paulista': require('../../assets/images/alimentos/cuscuz-paulista.jpg'),
  'cuscuz': require('../../assets/images/alimentos/cuscuz.jpg'),
  'dobradinha': require('../../assets/images/alimentos/dobradinha.jpg'),
  'empada-frango': require('../../assets/images/alimentos/empada-frango.jpg'),
  'ervilha': require('../../assets/images/alimentos/ervilha.jpg'),
  'escondidinho-carne-seca': require('../../assets/images/alimentos/escondidinho-carne-seca.jpg'),
  'escondidinho-carne': require('../../assets/images/alimentos/escondidinho-carne.jpg'),
  'escondidinho-frango': require('../../assets/images/alimentos/escondidinho-frango.jpg'),
  'esfiha': require('../../assets/images/alimentos/esfiha.jpg'),
  'espinafre': require('../../assets/images/alimentos/espinafre.jpg'),
  'estrogonofe-carne': require('../../assets/images/alimentos/estrogonofe-carne.jpg'),
  'estrogonofe': require('../../assets/images/alimentos/estrogonofe.jpg'),
  'falafel': require('../../assets/images/alimentos/falafel.jpg'),
  'farofa': require('../../assets/images/alimentos/farofa.jpg'),
  'feijao-carioca': require('../../assets/images/alimentos/feijao-carioca.jpg'),
  'feijao-preto': require('../../assets/images/alimentos/feijao-preto.jpg'),
  'feijao-tropeiro': require('../../assets/images/alimentos/feijao-tropeiro.jpg'),
  'feijoada': require('../../assets/images/alimentos/feijoada.jpg'),
  'file-mignon': require('../../assets/images/alimentos/file-mignon.jpg'),
  'frango-assado': require('../../assets/images/alimentos/frango-assado.jpg'),
  'frango-milanesa': require('../../assets/images/alimentos/frango-milanesa.jpg'),
  'frango-xadrez': require('../../assets/images/alimentos/frango-xadrez.jpg'),
  'galinhada': require('../../assets/images/alimentos/galinhada.jpg'),
  'goiaba': require('../../assets/images/alimentos/goiaba.jpg'),
  'granola': require('../../assets/images/alimentos/granola.jpg'),
  'grao-de-bico': require('../../assets/images/alimentos/grao-de-bico.jpg'),
  'guacamole-nachos': require('../../assets/images/alimentos/guacamole-nachos.jpg'),
  'gyoza-porco': require('../../assets/images/alimentos/gyoza-porco.jpg'),
  'hamburguer': require('../../assets/images/alimentos/hamburguer.jpg'),
  'homus-pao': require('../../assets/images/alimentos/homus-pao.jpg'),
  'iogurte-fruta': require('../../assets/images/alimentos/iogurte-fruta.jpg'),
  'iogurte-granola': require('../../assets/images/alimentos/iogurte-granola.jpg'),
  'iogurte': require('../../assets/images/alimentos/iogurte.jpg'),
  'kebab-carne': require('../../assets/images/alimentos/kebab-carne.jpg'),
  'laranja': require('../../assets/images/alimentos/laranja.jpg'),
  'lasanha-carne': require('../../assets/images/alimentos/lasanha-carne.jpg'),
  'lasanha-frango': require('../../assets/images/alimentos/lasanha-frango.jpg'),
  'lasanha-presunto': require('../../assets/images/alimentos/lasanha-presunto.jpg'),
  'legumes': require('../../assets/images/alimentos/legumes.jpg'),
  'leite': require('../../assets/images/alimentos/leite.jpg'),
  'lentilha': require('../../assets/images/alimentos/lentilha.jpg'),
  'linguica': require('../../assets/images/alimentos/linguica.jpg'),
  'lombo': require('../../assets/images/alimentos/lombo.jpg'),
  'mac-and-cheese': require('../../assets/images/alimentos/mac-and-cheese.jpg'),
  'maca': require('../../assets/images/alimentos/maca.jpg'),
  'macarrao-alho': require('../../assets/images/alimentos/macarrao-alho.jpg'),
  'macarrao-bolonhesa': require('../../assets/images/alimentos/macarrao-bolonhesa.jpg'),
  'macarrao-queijos': require('../../assets/images/alimentos/macarrao-queijos.jpg'),
  'macarrao': require('../../assets/images/alimentos/macarrao.jpg'),
  'mamao': require('../../assets/images/alimentos/mamao.jpg'),
  'mandioca-frita': require('../../assets/images/alimentos/mandioca-frita.jpg'),
  'mandioca': require('../../assets/images/alimentos/mandioca.jpg'),
  'manga': require('../../assets/images/alimentos/manga.jpg'),
  'manicoba': require('../../assets/images/alimentos/manicoba.jpg'),
  'manjuba': require('../../assets/images/alimentos/manjuba.jpg'),
  'melancia': require('../../assets/images/alimentos/melancia.jpg'),
  'merluza': require('../../assets/images/alimentos/merluza.jpg'),
  'milho': require('../../assets/images/alimentos/milho.jpg'),
  'mingau-aveia': require('../../assets/images/alimentos/mingau-aveia.jpg'),
  'misto-quente': require('../../assets/images/alimentos/misto-quente.jpg'),
  'moqueca': require('../../assets/images/alimentos/moqueca.jpg'),
  'morango': require('../../assets/images/alimentos/morango.jpg'),
  'mortadela': require('../../assets/images/alimentos/mortadela.jpg'),
  'musculo': require('../../assets/images/alimentos/musculo.jpg'),
  'mussarela': require('../../assets/images/alimentos/mussarela.jpg'),
  'nhoque': require('../../assets/images/alimentos/nhoque.jpg'),
  'omelete': require('../../assets/images/alimentos/omelete.jpg'),
  'ovo-codorna': require('../../assets/images/alimentos/ovo-codorna.jpg'),
  'ovo-cozido': require('../../assets/images/alimentos/ovo-cozido.jpg'),
  'ovo-frito': require('../../assets/images/alimentos/ovo-frito.jpg'),
  'pacoca': require('../../assets/images/alimentos/pacoca.jpg'),
  'pad-thai-camarao': require('../../assets/images/alimentos/pad-thai-camarao.jpg'),
  'paella-frutos-do-mar': require('../../assets/images/alimentos/paella-frutos-do-mar.jpg'),
  'panqueca-americana': require('../../assets/images/alimentos/panqueca-americana.jpg'),
  'panqueca-carne': require('../../assets/images/alimentos/panqueca-carne.jpg'),
  'panqueca-frango': require('../../assets/images/alimentos/panqueca-frango.jpg'),
  'pao-aveia': require('../../assets/images/alimentos/pao-aveia.jpg'),
  'pao-de-queijo': require('../../assets/images/alimentos/pao-de-queijo.jpg'),
  'pao-frances': require('../../assets/images/alimentos/pao-frances.jpg'),
  'pao-integral': require('../../assets/images/alimentos/pao-integral.jpg'),
  'pao-sovado': require('../../assets/images/alimentos/pao-sovado.jpg'),
  'parmegiana-carne': require('../../assets/images/alimentos/parmegiana-carne.jpg'),
  'parmegiana-frango': require('../../assets/images/alimentos/parmegiana-frango.jpg'),
  'parmesao': require('../../assets/images/alimentos/parmesao.jpg'),
  'pasta-amendoim': require('../../assets/images/alimentos/pasta-amendoim.jpg'),
  'pastel-carne': require('../../assets/images/alimentos/pastel-carne.jpg'),
  'pastel-queijo': require('../../assets/images/alimentos/pastel-queijo.jpg'),
  'patinho': require('../../assets/images/alimentos/patinho.jpg'),
  'peito-frango': require('../../assets/images/alimentos/peito-frango.jpg'),
  'pepino': require('../../assets/images/alimentos/pepino.jpg'),
  'pernil': require('../../assets/images/alimentos/pernil.jpg'),
  'peru': require('../../assets/images/alimentos/peru.jpg'),
  'pescada': require('../../assets/images/alimentos/pescada.jpg'),
  'picanha': require('../../assets/images/alimentos/picanha.jpg'),
  'pimentao': require('../../assets/images/alimentos/pimentao.jpg'),
  'pipoca': require('../../assets/images/alimentos/pipoca.jpg'),
  'pizza-calabresa': require('../../assets/images/alimentos/pizza-calabresa.jpg'),
  'pizza-frango': require('../../assets/images/alimentos/pizza-frango.jpg'),
  'pizza-mussarela': require('../../assets/images/alimentos/pizza-mussarela.jpg'),
  'pizza-portuguesa': require('../../assets/images/alimentos/pizza-portuguesa.jpg'),
  'poke-salmao': require('../../assets/images/alimentos/poke-salmao.jpg'),
  'presunto': require('../../assets/images/alimentos/presunto.jpg'),
  'queijo-minas': require('../../assets/images/alimentos/queijo-minas.jpg'),
  'queijo-prato': require('../../assets/images/alimentos/queijo-prato.jpg'),
  'quesadilla-queijo': require('../../assets/images/alimentos/quesadilla-queijo.jpg'),
  'quiabo': require('../../assets/images/alimentos/quiabo.jpg'),
  'quibe': require('../../assets/images/alimentos/quibe.jpg'),
  'quiche-queijo': require('../../assets/images/alimentos/quiche-queijo.jpg'),
  'ramen-carne': require('../../assets/images/alimentos/ramen-carne.jpg'),
  'repolho': require('../../assets/images/alimentos/repolho.jpg'),
  'requeijao': require('../../assets/images/alimentos/requeijao.jpg'),
  'ricota': require('../../assets/images/alimentos/ricota.jpg'),
  'risoto-camarao': require('../../assets/images/alimentos/risoto-camarao.jpg'),
  'risoto-frango': require('../../assets/images/alimentos/risoto-frango.jpg'),
  'salada-folhas': require('../../assets/images/alimentos/salada-folhas.jpg'),
  'salmao': require('../../assets/images/alimentos/salmao.jpg'),
  'salpicao': require('../../assets/images/alimentos/salpicao.jpg'),
  'sanduiche-atum': require('../../assets/images/alimentos/sanduiche-atum.jpg'),
  'sanduiche-frango': require('../../assets/images/alimentos/sanduiche-frango.jpg'),
  'sanduiche-ovo': require('../../assets/images/alimentos/sanduiche-ovo.jpg'),
  'sanduiche-peru': require('../../assets/images/alimentos/sanduiche-peru.jpg'),
  'sardinha-lata': require('../../assets/images/alimentos/sardinha-lata.jpg'),
  'sardinha': require('../../assets/images/alimentos/sardinha.jpg'),
  'shakshuka': require('../../assets/images/alimentos/shakshuka.jpg'),
  'shawarma-frango': require('../../assets/images/alimentos/shawarma-frango.jpg'),
  'smoothie-proteico': require('../../assets/images/alimentos/smoothie-proteico.jpg'),
  'sobrecoxa': require('../../assets/images/alimentos/sobrecoxa.jpg'),
  'sopa-carne': require('../../assets/images/alimentos/sopa-carne.jpg'),
  'sopa-feijao': require('../../assets/images/alimentos/sopa-feijao.jpg'),
  'sopa-legumes': require('../../assets/images/alimentos/sopa-legumes.jpg'),
  'souvlaki-frango': require('../../assets/images/alimentos/souvlaki-frango.jpg'),
  'suco-laranja': require('../../assets/images/alimentos/suco-laranja.jpg'),
  'sushi': require('../../assets/images/alimentos/sushi.jpg'),
  'tabule': require('../../assets/images/alimentos/tabule.jpg'),
  'taco-carne': require('../../assets/images/alimentos/taco-carne.jpg'),
  'tapioca-frango': require('../../assets/images/alimentos/tapioca-frango.jpg'),
  'tapioca-queijo': require('../../assets/images/alimentos/tapioca-queijo.jpg'),
  'tapioca': require('../../assets/images/alimentos/tapioca.jpg'),
  'temaki-salmao': require('../../assets/images/alimentos/temaki-salmao.jpg'),
  'tikka-masala': require('../../assets/images/alimentos/tikka-masala.jpg'),
  'tofu': require('../../assets/images/alimentos/tofu.jpg'),
  'tomate': require('../../assets/images/alimentos/tomate.jpg'),
  'torrada-abacate-ovo': require('../../assets/images/alimentos/torrada-abacate-ovo.jpg'),
  'torrada': require('../../assets/images/alimentos/torrada.jpg'),
  'torta-frango': require('../../assets/images/alimentos/torta-frango.jpg'),
  'tortilla-espanhola': require('../../assets/images/alimentos/tortilla-espanhola.jpg'),
  'uva': require('../../assets/images/alimentos/uva.jpg'),
  'vaca-atolada': require('../../assets/images/alimentos/vaca-atolada.jpg'),
  'vagem': require('../../assets/images/alimentos/vagem.jpg'),
  'vatapa': require('../../assets/images/alimentos/vatapa.jpg'),
  'virado': require('../../assets/images/alimentos/virado.jpg'),
  'vitamina-banana': require('../../assets/images/alimentos/vitamina-banana.jpg'),
  'waffle': require('../../assets/images/alimentos/waffle.jpg'),
  'whey': require('../../assets/images/alimentos/whey.jpg'),
  'wrap-frango': require('../../assets/images/alimentos/wrap-frango.jpg'),
  'x-salada': require('../../assets/images/alimentos/x-salada.jpg'),
  'yakisoba': require('../../assets/images/alimentos/yakisoba.jpg'),
};

const POR_PRATELEIRA: Record<string, any> = {

};

const chave = (s: string) =>
  s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** A foto de um alimento: a dele, a da prateleira dele, ou nenhuma. */
export function fotoDoAlimento(id: string, onde: string): any | null {
  return POR_ITEM[id] || POR_PRATELEIRA[chave(onde)] || null;
}

/** Quantas fotos existem hoje — a tela de consulta não usa, o gerador sim. */
export const TOTAL_FOTOS = 222;
