/* ============================================================
   OS ALIMENTOS — de onde saem os gramas

   ARQUIVO GERADO por scripts/gerar-alimentos.mjs, que é onde mora a
   curadoria. Para mexer na lista, mexa lá e rode de novo:

     node scripts/gerar-alimentos.mjs src/logic/alimentos.ts

   Proteína por 100 g, como se come. Os valores vêm da TACO — Tabela
   Brasileira de Composição de Alimentos, 4ª edição, NEPA/UNICAMP — e o
   campo `taco` guarda a linha exata de onde cada um saiu, para que o
   número tenha procedência e não opinião. As poucas entradas sem `taco`
   trazem `fonte` dizendo de onde vieram: a TACO não analisou o leite
   líquido, não tem suplemento, e traz grão-de-bico e macarrão só crus.

   Já a UNIDADE não é da TACO, e não podia ser: tabela de composição
   descreve 100 g, não descreve prato. Que um filé de frango pese perto
   de 120 g é medida caseira, e é por isso que a tela escreve "~".

   Mas a unidade é o que torna a pergunta respondível. "A porção foi
   pouca, normal ou bastante?" pede uma comparação com uma régua que só
   o app conhece. "Quantas colheres de arroz?" pergunta uma coisa que
   quem comeu viu acontecer.

   A lista é curta de propósito. São os alimentos que alguém digita
   DEPOIS de comer — não um inventário de ingredientes. Quem procurar
   "farinha de trigo" não acha, e está certo: ninguém almoça isso. O que
   entra além dos ingredientes são pratos inteiros, somados a partir dos
   componentes na TACO com a receita escrita em `fonte`: quem almoçou
   carbonara escreve carbonara, não "macarrão + ovo + bacon".
   ============================================================ */

export type Alimento = {
  id: string;
  nome: string;
  /** Termos sem acento para a busca encontrar o que a pessoa digita. */
  busca: string;
  /** Proteína por 100 g. */
  p: number;
  /* O RESTO DO RÓTULO, por 100 g.

     Um `null` ali quer dizer NÃO ANALISADO, e não zero: a TACO deixa
     a célula vazia quando o nutriente não foi medido naquele alimento, e
     a tela mostra "—". Dizer zero ali seria afirmar uma ausência que
     ninguém verificou. */
  kcal: number | null;
  carb: number | null;
  gord: number | null;
  fibra: number | null;
  /** Gramas de UMA unidade: um filé, uma colher, uma concha. */
  gUn: number;
  /** Quantas unidades vêm marcadas ao escolher o alimento. */
  qtd: number;
  /** A unidade no singular, e no plural. */
  un: string;
  unp: string;
  /** Em que corredor do mercado ele estaria — filtro e foto. */
  onde: string;
  /* O nutriente em que 100 g deste alimento mais se destacam, quando
     algum passa de 15% da IDR — o mesmo corte que a regra brasileira de
     rotulagem usa para autorizar a frase "fonte de". Sem destaque, a
     tela não inventa frase nenhuma. */
  destaque?: { nome: string; valor: number; un: string; pct: number };
  /** Linha da TACO de onde os números saíram. */
  taco?: number;
  /** Quando não é da TACO, de onde é. */
  fonte?: string;
};

export const ALIMENTOS: Alimento[] = [
  { id: 'peito-frango', nome: 'Peito de frango grelhado', busca: 'frango peito file grelhado file de frango', p: 32, kcal: 159, carb: 0, gord: 2.5, fibra: null, gUn: 120, qtd: 1, un: 'filé', unp: 'filés', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 32, un: 'g', pct: 64 }, taco: 410 }, /* Frango, peito, sem pele, grelhado */
  { id: 'frango-assado', nome: 'Frango assado sem pele', busca: 'frango assado cozido', p: 28, kcal: 187, carb: 0, gord: 7.5, fibra: null, gUn: 120, qtd: 1, un: 'pedaço', unp: 'pedaços', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 28, un: 'g', pct: 56 }, taco: 403 }, /* Frango, inteiro, sem pele, assado */
  { id: 'sobrecoxa', nome: 'Coxa ou sobrecoxa de frango', busca: 'coxa sobrecoxa frango', p: 29.2, kcal: 233, carb: 0, gord: 12, fibra: null, gUn: 100, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 29, un: 'g', pct: 58 }, taco: 413 }, /* Frango, sobrecoxa, sem pele, assada */
  { id: 'frango-milanesa', nome: 'Frango à milanesa', busca: 'frango milanesa empanado nuggets', p: 28.5, kcal: 221, carb: 7.5, gord: 7.8, fibra: 1.1, gUn: 120, qtd: 1, un: 'filé', unp: 'filés', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 28, un: 'g', pct: 57 }, taco: 401 }, /* Frango, filé, à milanesa */
  { id: 'patinho', nome: 'Bife de patinho grelhado', busca: 'bife patinho carne vermelha grelhado', p: 35.9, kcal: 219, carb: 0, gord: 7.3, fibra: null, gUn: 100, qtd: 1, un: 'bife', unp: 'bifes', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 36, un: 'g', pct: 72 }, taco: 377 }, /* Carne, bovina, patinho, sem gordura, grelhado */
  { id: 'contrafile', nome: 'Contra-filé grelhado', busca: 'contra file bife carne', p: 32.4, kcal: 278, carb: 0, gord: 15.5, fibra: null, gUn: 100, qtd: 1, un: 'bife', unp: 'bifes', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 32, un: 'g', pct: 65 }, taco: 344 }, /* Carne, bovina, contra-filé, com gordura, grelhado */
  { id: 'file-mignon', nome: 'Filé mignon grelhado', busca: 'file mignon carne', p: 32.8, kcal: 220, carb: 0, gord: 8.8, fibra: null, gUn: 100, qtd: 1, un: 'medalhão', unp: 'medalhões', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 33, un: 'g', pct: 66 }, taco: 358 }, /* Carne, bovina, filé mingnon, sem gordura, grelhado */
  { id: 'picanha', nome: 'Picanha grelhada', busca: 'picanha churrasco carne', p: 31.9, kcal: 238, carb: 0, gord: 11.3, fibra: null, gUn: 50, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 32, un: 'g', pct: 64 }, taco: 383 }, /* Carne, bovina, picanha, sem gordura, grelhada */
  { id: 'carne-moida', nome: 'Carne moída refogada', busca: 'carne moida bolonhesa moido', p: 26.7, kcal: 212, carb: 0, gord: 10.9, fibra: null, gUn: 25, qtd: 4, un: 'colher', unp: 'colheres', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 27, un: 'g', pct: 53 }, taco: 326 }, /* Carne, bovina, acém, moído, cozido */
  { id: 'carne-panela', nome: 'Carne de panela', busca: 'carne panela cozida ensopado paleta', p: 29.7, kcal: 194, carb: 0, gord: 7.4, fibra: null, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 30, un: 'g', pct: 59 }, taco: 374 }, /* Carne, bovina, paleta, sem gordura, cozida */
  { id: 'musculo', nome: 'Músculo cozido', busca: 'musculo cozido sopa', p: 31.2, kcal: 194, carb: 0, gord: 6.7, fibra: null, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 31, un: 'g', pct: 62 }, taco: 371 }, /* Carne, bovina, músculo, sem gordura, cozido */
  { id: 'hamburguer', nome: 'Hambúrguer', busca: 'hamburguer burguer lanche', p: 20, kcal: 258, carb: 6.3, gord: 17, fibra: null, gUn: 80, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 20, un: 'g', pct: 40 }, taco: 416 }, /* Hambúrguer, bovino, frito */
  { id: 'linguica', nome: 'Linguiça', busca: 'linguica calabresa churrasco', p: 18.2, kcal: 244, carb: 0, gord: 18.4, fibra: null, gUn: 80, qtd: 1, un: 'gomo', unp: 'gomos', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 18, un: 'g', pct: 36 }, taco: 420 }, /* Lingüiça, frango, grelhada */
  { id: 'lombo', nome: 'Lombo de porco assado', busca: 'lombo porco suino', p: 35.7, kcal: 210, carb: 0, gord: 6.4, fibra: null, gUn: 100, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 36, un: 'g', pct: 71 }, taco: 432 }, /* Porco, lombo, assado */
  { id: 'pernil', nome: 'Pernil assado', busca: 'pernil porco suino', p: 32.1, kcal: 262, carb: 0, gord: 13.9, fibra: null, gUn: 100, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 32, un: 'g', pct: 64 }, taco: 435 }, /* Porco, pernil, assado */
  { id: 'costelinha', nome: 'Costelinha de porco', busca: 'costela costelinha porco', p: 30.2, kcal: 402, carb: 0, gord: 30.3, fibra: null, gUn: 60, qtd: 2, un: 'costela', unp: 'costelas', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 30, un: 'g', pct: 60 }, taco: 430 }, /* Porco, costela, assada */
  { id: 'coxao-mole', nome: 'Carne cozida (coxão mole)', busca: 'coxao mole carne cozida panela', p: 32.4, kcal: 219, carb: 0, gord: 8.9, fibra: null, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 32, un: 'g', pct: 65 }, taco: 351 }, /* Carne, bovina, coxão mole, sem gordura, cozido */
  { id: 'almondega', nome: 'Almôndegas', busca: 'almondega bolinho de carne', p: 18.2, kcal: 272, carb: 14.3, gord: 15.8, fibra: null, gUn: 33, qtd: 3, un: 'unidade', unp: 'unidades', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 18, un: 'g', pct: 36 }, taco: 331 }, /* Carne, bovina, almôndegas, fritas */
  { id: 'figado', nome: 'Fígado acebolado', busca: 'figado bife acebolado', p: 29.9, kcal: 225, carb: 4.2, gord: 9, fibra: null, gUn: 100, qtd: 1, un: 'bife', unp: 'bifes', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 30, un: 'g', pct: 60 }, taco: 356 }, /* Carne, bovina, fígado, grelhado */
  { id: 'peru', nome: 'Peru assado', busca: 'peru chester ave natal', p: 26.2, kcal: 163, carb: 0, gord: 5.7, fibra: null, gUn: 100, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Carnes e aves', destaque: { nome: 'proteína', valor: 26, un: 'g', pct: 52 }, taco: 425 }, /* Peru, congelado, assado */
  { id: 'quibe', nome: 'Quibe assado', busca: 'quibe kibe', p: 14.6, kcal: 136, carb: 12.9, gord: 2.7, fibra: 1.9, gUn: 80, qtd: 1, un: 'pedaço', unp: 'pedaços', onde: 'Carnes e aves', destaque: { nome: 'zinco', valor: 4.1, un: 'mg', pct: 37 }, taco: 440 }, /* Quibe, assado */
  { id: 'presunto', nome: 'Presunto', busca: 'presunto frios peito de peru', p: 14.3, kcal: 94, carb: 2.1, gord: 2.7, fibra: null, gUn: 15, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Carnes e aves', destaque: { nome: 'tiamina', valor: 0.5, un: 'mg', pct: 42 }, taco: 439 }, /* Presunto, sem capa de gordura */
  { id: 'mortadela', nome: 'Mortadela', busca: 'mortadela frios', p: 12, kcal: 269, carb: 5.8, gord: 21.6, fibra: null, gUn: 15, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Carnes e aves', destaque: { nome: 'fósforo', valor: 216, un: 'mg', pct: 31 }, taco: 424 }, /* Mortadela */
  { id: 'salmao', nome: 'Salmão grelhado', busca: 'salmao peixe', p: 23.9, kcal: 229, carb: 0, gord: 14, fibra: null, gUn: 120, qtd: 1, un: 'posta', unp: 'postas', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 24, un: 'g', pct: 48 }, taco: 315 }, /* Salmão, filé, com pele, fresco,  grelhado */
  { id: 'merluza', nome: 'Merluza assada', busca: 'merluza peixe branco assado file', p: 26.6, kcal: 122, carb: 0, gord: 0.9, fibra: null, gUn: 120, qtd: 1, un: 'filé', unp: 'filés', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 27, un: 'g', pct: 53 }, taco: 301 }, /* Merluza, filé, assado */
  { id: 'pescada', nome: 'Pescada frita', busca: 'pescada peixe frito tilapia', p: 28.6, kcal: 154, carb: 0, gord: 3.6, fibra: null, gUn: 120, qtd: 1, un: 'filé', unp: 'filés', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 29, un: 'g', pct: 57 }, taco: 308 }, /* Pescada, filé, frito */
  { id: 'sardinha', nome: 'Sardinha assada', busca: 'sardinha peixe assada', p: 32.2, kcal: 164, carb: 0, gord: 3, fibra: null, gUn: 50, qtd: 2, un: 'unidade', unp: 'unidades', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 32, un: 'g', pct: 64 }, taco: 318 }, /* Sardinha, assada */
  { id: 'sardinha-lata', nome: 'Sardinha em lata', busca: 'sardinha lata conserva', p: 15.9, kcal: 285, carb: 0, gord: 24, fibra: null, gUn: 160, qtd: 1, un: 'lata', unp: 'latas', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 16, un: 'g', pct: 32 }, taco: 319 }, /* Sardinha, conserva em óleo */
  { id: 'atum-lata', nome: 'Atum em lata', busca: 'atum lata conserva', p: 26.2, kcal: 166, carb: 0, gord: 6, fibra: null, gUn: 160, qtd: 1, un: 'lata', unp: 'latas', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 26, un: 'g', pct: 52 }, taco: 277 }, /* Atum, conserva em óleo */
  { id: 'bacalhau', nome: 'Bacalhau refogado', busca: 'bacalhau', p: 24, kcal: 140, carb: 1.2, gord: 3.6, fibra: null, gUn: 120, qtd: 1, un: 'porção', unp: 'porções', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 24, un: 'g', pct: 48 }, taco: 280 }, /* Bacalhau, salgado, refogado */
  { id: 'corvina', nome: 'Corvina assada', busca: 'corvina peixe assado', p: 26.8, kcal: 147, carb: 0, gord: 3.6, fibra: null, gUn: 120, qtd: 1, un: 'posta', unp: 'postas', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 27, un: 'g', pct: 54 }, taco: 293 }, /* Corvina grande, assada */
  { id: 'manjuba', nome: 'Manjuba frita', busca: 'manjuba peixinho frito', p: 30.1, kcal: 349, carb: 0, gord: 24.5, fibra: null, gUn: 80, qtd: 1, un: 'porção', unp: 'porções', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 30, un: 'g', pct: 60 }, taco: 300 }, /* Manjuba, frita */
  { id: 'camarao', nome: 'Camarão cozido', busca: 'camarao frutos do mar', p: 19, kcal: 90, carb: 0, gord: 1, fibra: null, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Peixes e frutos do mar', destaque: { nome: 'proteína', valor: 19, un: 'g', pct: 38 }, taco: 284 }, /* Camarão, Rio Grande, grande, cozido */
  { id: 'ovo-cozido', nome: 'Ovo cozido', busca: 'ovo ovos cozido pochê', p: 13.3, kcal: 146, carb: 0.6, gord: 9.5, fibra: null, gUn: 50, qtd: 2, un: 'unidade', unp: 'unidades', onde: 'Ovos', destaque: { nome: 'proteína', valor: 13, un: 'g', pct: 27 }, taco: 488 }, /* Ovo, de galinha, inteiro, cozido/10minutos */
  { id: 'ovo-frito', nome: 'Ovo frito ou mexido', busca: 'ovo ovos frito mexido mexidos', p: 15.6, kcal: 240, carb: 1.2, gord: 18.6, fibra: null, gUn: 50, qtd: 2, un: 'unidade', unp: 'unidades', onde: 'Ovos', destaque: { nome: 'proteína', valor: 16, un: 'g', pct: 31 }, taco: 490 }, /* Ovo, de galinha, inteiro, frito */
  { id: 'omelete', nome: 'Omelete de queijo', busca: 'omelete omelette', p: 15.6, kcal: 268, carb: 0.4, gord: 22, fibra: null, gUn: 120, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Ovos', destaque: { nome: 'proteína', valor: 16, un: 'g', pct: 31 }, taco: 484 }, /* Omelete, de queijo */
  { id: 'iogurte', nome: 'Iogurte natural', busca: 'iogurte natural grego', p: 4.1, kcal: 51, carb: 1.9, gord: 3, fibra: null, gUn: 170, qtd: 1, un: 'pote', unp: 'potes', onde: 'Leite e queijos', destaque: { nome: 'riboflavina', valor: 0.2, un: 'mg', pct: 19 }, taco: 448 }, /* Iogurte, natural */
  { id: 'iogurte-fruta', nome: 'Iogurte de fruta', busca: 'iogurte morango sabor fruta', p: 2.7, kcal: 70, carb: 9.7, gord: 2.3, fibra: 0.2, gUn: 150, qtd: 1, un: 'pote', unp: 'potes', onde: 'Leite e queijos', taco: 451 }, /* Iogurte, sabor morango */
  { id: 'queijo-minas', nome: 'Queijo minas frescal', busca: 'queijo minas branco frescal', p: 17.4, kcal: 264, carb: 3.2, gord: 20.2, fibra: null, gUn: 50, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Leite e queijos', destaque: { nome: 'proteína', valor: 17, un: 'g', pct: 35 }, taco: 461 }, /* Queijo, minas, frescal */
  { id: 'mussarela', nome: 'Mussarela', busca: 'mussarela muçarela queijo', p: 22.6, kcal: 330, carb: 3, gord: 25.2, fibra: null, gUn: 15, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Leite e queijos', destaque: { nome: 'proteína', valor: 23, un: 'g', pct: 45 }, taco: 463 }, /* Queijo, mozarela */
  { id: 'queijo-prato', nome: 'Queijo prato', busca: 'queijo prato', p: 22.7, kcal: 360, carb: 1.9, gord: 29.1, fibra: null, gUn: 15, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Leite e queijos', destaque: { nome: 'proteína', valor: 23, un: 'g', pct: 45 }, taco: 467 }, /* Queijo, prato */
  { id: 'parmesao', nome: 'Parmesão ralado', busca: 'parmesao queijo ralado', p: 35.6, kcal: 453, carb: 1.7, gord: 33.5, fibra: null, gUn: 15, qtd: 1, un: 'colher', unp: 'colheres', onde: 'Leite e queijos', destaque: { nome: 'proteína', valor: 36, un: 'g', pct: 71 }, taco: 464 }, /* Queijo, parmesão */
  { id: 'ricota', nome: 'Ricota', busca: 'ricota queijo', p: 12.6, kcal: 140, carb: 3.8, gord: 8.1, fibra: null, gUn: 50, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Leite e queijos', destaque: { nome: 'proteína', valor: 13, un: 'g', pct: 25 }, taco: 469 }, /* Queijo, ricota */
  { id: 'requeijao', nome: 'Requeijão', busca: 'requeijao cream cheese', p: 9.4, kcal: 303, carb: 5.7, gord: 27.4, fibra: null, gUn: 30, qtd: 1, un: 'colher', unp: 'colheres', onde: 'Leite e queijos', destaque: { nome: 'fósforo', valor: 578, un: 'mg', pct: 83 }, taco: 465 }, /* Queijo, pasteurizado */
  { id: 'leite', nome: 'Leite', busca: 'leite copo integral desnatado', p: 3.2, kcal: 60, carb: 4.7, gord: 3.2, fibra: null, gUn: 200, qtd: 1, un: 'copo', unp: 'copos', onde: 'Leite e queijos', fonte: 'TBCA' }, /* TBCA */
  { id: 'achocolatado', nome: 'Leite com achocolatado', busca: 'achocolatado nescau toddy leite', p: 2.1, kcal: 83, carb: 14.2, gord: 2.2, fibra: 0.6, gUn: 200, qtd: 1, un: 'copo', unp: 'copos', onde: 'Leite e queijos', destaque: { nome: 'riboflavina', valor: 0.3, un: 'mg', pct: 24 }, taco: 455 }, /* Leite, de vaca, achocolatado */
  { id: 'whey', nome: 'Whey protein', busca: 'whey proteina suplemento shake', p: 80, kcal: 380, carb: 8, gord: 5, fibra: null, gUn: 30, qtd: 1, un: 'scoop', unp: 'scoops', onde: 'Suplementos', destaque: { nome: 'proteína', valor: 80, un: 'g', pct: 160 }, fonte: 'rótulo' }, /* rótulo */
  { id: 'feijao-carioca', nome: 'Feijão carioca', busca: 'feijao carioca caldo', p: 4.8, kcal: 76, carb: 13.6, gord: 0.5, fibra: 8.5, gUn: 80, qtd: 1, un: 'concha', unp: 'conchas', onde: 'Grãos e feijões', destaque: { nome: 'fibra', valor: 8.5, un: 'g', pct: 34 }, taco: 561 }, /* Feijão, carioca, cozido */
  { id: 'feijao-preto', nome: 'Feijão preto', busca: 'feijao preto', p: 4.5, kcal: 77, carb: 14, gord: 0.5, fibra: 8.4, gUn: 80, qtd: 1, un: 'concha', unp: 'conchas', onde: 'Grãos e feijões', destaque: { nome: 'fibra', valor: 8.4, un: 'g', pct: 34 }, taco: 567 }, /* Feijão, preto, cozido */
  { id: 'lentilha', nome: 'Lentilha cozida', busca: 'lentilha', p: 6.3, kcal: 93, carb: 16.3, gord: 0.5, fibra: 7.9, gUn: 80, qtd: 1, un: 'concha', unp: 'conchas', onde: 'Grãos e feijões', destaque: { nome: 'fibra', valor: 7.9, un: 'g', pct: 31 }, taco: 577 }, /* Lentilha, cozida */
  { id: 'grao-de-bico', nome: 'Grão-de-bico cozido', busca: 'grao de bico homus', p: 8.8, kcal: 148, carb: 24.1, gord: 2.3, fibra: 5.1, gUn: 80, qtd: 1, un: 'concha', unp: 'conchas', onde: 'Grãos e feijões', destaque: { nome: 'fibra', valor: 5.1, un: 'g', pct: 21 }, taco: 575 }, /* Grão-de-bico, cru ÷ 2,4 de rendimento */
  { id: 'tofu', nome: 'Tofu', busca: 'tofu soja queijo de soja', p: 6.6, kcal: 64, carb: 2.1, gord: 4, fibra: 0.8, gUn: 100, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Grãos e feijões', destaque: { nome: 'fósforo', valor: 130, un: 'mg', pct: 19 }, taco: 584 }, /* Soja, queijo (tofu) */
  { id: 'feijao-tropeiro', nome: 'Feijão tropeiro', busca: 'tropeiro feijao mineiro', p: 10.2, kcal: 152, carb: 19.6, gord: 6.8, fibra: 3.6, gUn: 120, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'fósforo', valor: 199, un: 'mg', pct: 28 }, taco: 539 }, /* Feijão tropeiro mineiro */
  { id: 'ervilha', nome: 'Ervilha', busca: 'ervilha', p: 7.5, kcal: 88, carb: 14.2, gord: 0.5, fibra: 9.7, gUn: 20, qtd: 3, un: 'colher', unp: 'colheres', onde: 'Grãos e feijões', destaque: { nome: 'fibra', valor: 9.7, un: 'g', pct: 39 }, taco: 559 }, /* Ervilha, em vagem */
  { id: 'arroz', nome: 'Arroz branco', busca: 'arroz branco', p: 2.5, kcal: 128, carb: 28.1, gord: 0.2, fibra: 1.6, gUn: 30, qtd: 4, un: 'colher', unp: 'colheres', onde: 'Arroz, massas e pães', taco: 3 }, /* Arroz, tipo 1, cozido */
  { id: 'arroz-integral', nome: 'Arroz integral', busca: 'arroz integral', p: 2.6, kcal: 124, carb: 25.8, gord: 1, fibra: 2.7, gUn: 30, qtd: 4, un: 'colher', unp: 'colheres', onde: 'Arroz, massas e pães', destaque: { nome: 'fósforo', valor: 106, un: 'mg', pct: 15 }, taco: 1 }, /* Arroz, integral, cozido */
  { id: 'macarrao', nome: 'Macarrão cozido', busca: 'macarrao massa espaguete penne', p: 4.5, kcal: 169, carb: 35.4, gord: 0.6, fibra: 1.3, gUn: 150, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Arroz, massas e pães', taco: 40 }, /* Macarrão, trigo, cru ÷ 2,2 de rendimento */
  { id: 'macarrao-bolonhesa', nome: 'Macarrão à bolonhesa', busca: 'macarrao bolonhesa molho carne', p: 4.9, kcal: 120, carb: 22.5, gord: 0.9, fibra: 0.8, gUn: 200, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', taco: 542 }, /* Macarrão, molho bolognesa */
  { id: 'pao-frances', nome: 'Pão francês', busca: 'pao frances padaria', p: 8, kcal: 300, carb: 58.6, gord: 3.1, fibra: 2.3, gUn: 50, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Arroz, massas e pães', destaque: { nome: 'riboflavina', valor: 0.7, un: 'mg', pct: 56 }, taco: 53 }, /* Pão, trigo, francês */
  { id: 'pao-integral', nome: 'Pão integral de forma', busca: 'pao forma integral', p: 9.4, kcal: 253, carb: 49.9, gord: 3.7, fibra: 6.9, gUn: 25, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Arroz, massas e pães', destaque: { nome: 'fibra', valor: 6.9, un: 'g', pct: 28 }, taco: 52 }, /* Pão, trigo, forma, integral */
  { id: 'aveia', nome: 'Aveia em flocos', busca: 'aveia flocos mingau', p: 13.9, kcal: 394, carb: 66.6, gord: 8.5, fibra: 9.1, gUn: 15, qtd: 2, un: 'colher', unp: 'colheres', onde: 'Arroz, massas e pães', destaque: { nome: 'tiamina', valor: 0.6, un: 'mg', pct: 46 }, taco: 7 }, /* Aveia, flocos, crua */
  { id: 'tapioca', nome: 'Tapioca', busca: 'tapioca goma', p: 0.1, kcal: 348, carb: 63.6, gord: 10.9, fibra: 0, gUn: 90, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', taco: 551 }, /* Tapioca, com manteiga */
  { id: 'cuscuz', nome: 'Cuscuz de milho', busca: 'cuscuz milho', p: 2.2, kcal: 113, carb: 25.3, gord: 0.7, fibra: 2.1, gUn: 120, qtd: 1, un: 'pedaço', unp: 'pedaços', onde: 'Pratos prontos', taco: 533 }, /* Cuscuz, de milho, cozido com sal */
  { id: 'pao-de-queijo', nome: 'Pão de queijo', busca: 'pao de queijo', p: 5.1, kcal: 363, carb: 34.2, gord: 24.6, fibra: 0.6, gUn: 20, qtd: 3, un: 'unidade', unp: 'unidades', onde: 'Verduras e legumes', taco: 140 }, /* Pão, de queijo, assado */
  { id: 'cereal', nome: 'Cereal matinal', busca: 'cereal matinal granola sucrilhos', p: 7.2, kcal: 365, carb: 83.8, gord: 1, fibra: 4.1, gUn: 30, qtd: 1, un: 'xícara', unp: 'xícaras', onde: 'Arroz, massas e pães', destaque: { nome: 'riboflavina', valor: 1, un: 'mg', pct: 85 }, taco: 25 }, /* Cereal matinal, milho */
  { id: 'arroz-carreteiro', nome: 'Arroz carreteiro', busca: 'carreteiro arroz com carne', p: 10.8, kcal: 154, carb: 11.6, gord: 7.1, fibra: 1.5, gUn: 200, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'zinco', valor: 2.7, un: 'mg', pct: 24 }, taco: 526 }, /* Arroz carreteiro */
  { id: 'baiao', nome: 'Baião de dois', busca: 'baiao de dois', p: 6.2, kcal: 136, carb: 20.4, gord: 3.2, fibra: 5.1, gUn: 200, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'fibra', valor: 5.1, un: 'g', pct: 20 }, taco: 527 }, /* Baião de dois, arroz e feijão-de-corda */
  { id: 'pao-sovado', nome: 'Pão doce ou sovado', busca: 'pao sovado doce bisnaguinha', p: 8.4, kcal: 311, carb: 61.5, gord: 2.8, fibra: 2.4, gUn: 50, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Arroz, massas e pães', destaque: { nome: 'zinco', valor: 2.7, un: 'mg', pct: 24 }, taco: 54 }, /* Pão, trigo, sovado */
  { id: 'pao-aveia', nome: 'Pão de aveia', busca: 'pao aveia forma', p: 12.3, kcal: 343, carb: 59.6, gord: 5.7, fibra: 6, gUn: 25, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Arroz, massas e pães', destaque: { nome: 'ferro', valor: 4.7, un: 'mg', pct: 34 }, taco: 48 }, /* Pão, aveia, forma */
  { id: 'cuscuz-paulista', nome: 'Cuscuz paulista', busca: 'cuscuz paulista', p: 2.6, kcal: 142, carb: 22.5, gord: 4.6, fibra: 2.4, gUn: 150, qtd: 1, un: 'pedaço', unp: 'pedaços', onde: 'Pratos prontos', taco: 534 }, /* Cuscuz, paulista */
  { id: 'estrogonofe', nome: 'Estrogonofe de frango', busca: 'estrogonofe strogonoff frango', p: 17.6, kcal: 157, carb: 2.6, gord: 8, fibra: null, gUn: 150, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 18, un: 'g', pct: 35 }, taco: 538 }, /* Estrogonofe de frango */
  { id: 'bife-a-cavalo', nome: 'Bife à cavalo', busca: 'bife a cavalo', p: 23.7, kcal: 291, carb: 0, gord: 21.1, fibra: null, gUn: 150, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 24, un: 'g', pct: 47 }, taco: 529 }, /* Bife à cavalo, com contra filé */
  { id: 'coxinha', nome: 'Coxinha', busca: 'coxinha salgado', p: 9.6, kcal: 283, carb: 34.5, gord: 11.8, fibra: 5, gUn: 80, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Carnes e aves', destaque: { nome: 'fibra', valor: 5, un: 'g', pct: 20 }, taco: 386 }, /* Coxinha de frango, frita */
  { id: 'legumes', nome: 'Legumes cozidos', busca: 'legumes cozidos vapor mistura', p: 2, kcal: 35, carb: 7.1, gord: 0.3, fibra: 2.5, gUn: 100, qtd: 1, un: 'pires', unp: 'pires', onde: 'Pratos prontos', destaque: { nome: 'vitamina A', valor: 255, un: 'mcg', pct: 32 }, taco: 546 }, /* Salada, de legumes, cozida no vapor */
  { id: 'feijoada', nome: 'Feijoada', busca: 'feijoada', p: 8.7, kcal: 117, carb: 11.6, gord: 6.5, fibra: 5.1, gUn: 250, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'fibra', valor: 5.1, un: 'g', pct: 20 }, taco: 540 }, /* Feijoada */
  { id: 'virado', nome: 'Virado à paulista', busca: 'virado paulista', p: 10.2, kcal: 307, carb: 14.1, gord: 25.6, fibra: 2.2, gUn: 250, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 10, un: 'g', pct: 20 }, taco: 555 }, /* Virado à paulista */
  { id: 'estrogonofe-carne', nome: 'Estrogonofe de carne', busca: 'estrogonofe strogonoff carne', p: 15, kcal: 173, carb: 3, gord: 10.8, fibra: null, gUn: 150, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 15, un: 'g', pct: 30 }, taco: 537 }, /* Estrogonofe de carne */
  { id: 'yakisoba', nome: 'Yakisoba', busca: 'yakisoba macarrao oriental', p: 7.5, kcal: 113, carb: 18.3, gord: 2.6, fibra: 1.1, gUn: 250, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 7.5, un: 'g', pct: 15 }, taco: 556 }, /* Yakisoba */
  { id: 'salpicao', nome: 'Salpicão de frango', busca: 'salpicao', p: 13.9, kcal: 148, carb: 4.6, gord: 7.8, fibra: 0.4, gUn: 120, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 14, un: 'g', pct: 28 }, taco: 547 }, /* Salpicão, de frango */
  { id: 'dobradinha', nome: 'Dobradinha', busca: 'dobradinha bucho', p: 19.8, kcal: 125, carb: 0, gord: 4.4, fibra: null, gUn: 200, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 20, un: 'g', pct: 40 }, taco: 536 }, /* Dobradinha */
  { id: 'vaca-atolada', nome: 'Vaca atolada', busca: 'vaca atolada costela mandioca', p: 5.1, kcal: 145, carb: 10.1, gord: 9.3, fibra: 2.3, gUn: 250, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', taco: 553 }, /* Vaca atolada */
  { id: 'vatapa', nome: 'Vatapá', busca: 'vatapa', p: 6, kcal: 255, carb: 9.7, gord: 23.2, fibra: 1.7, gUn: 150, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'fósforo', valor: 108, un: 'mg', pct: 15 }, taco: 554 }, /* Vatapá */
  { id: 'acaraje', nome: 'Acarajé', busca: 'acaraje', p: 8.3, kcal: 289, carb: 19.1, gord: 19.9, fibra: 9.4, gUn: 100, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'fibra', valor: 9.4, un: 'g', pct: 37 }, taco: 525 }, /* Acarajé */
  { id: 'manicoba', nome: 'Maniçoba', busca: 'manicoba', p: 10, kcal: 134, carb: 3.4, gord: 8.7, fibra: 2.2, gUn: 200, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'ferro', valor: 3.2, un: 'mg', pct: 23 }, taco: 543 }, /* Maniçoba */
  { id: 'barreado', nome: 'Barreado', busca: 'barreado', p: 18.3, kcal: 165, carb: 0.2, gord: 9.5, fibra: 0.1, gUn: 200, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 18, un: 'g', pct: 37 }, taco: 528 }, /* Barreado */
  { id: 'charuto', nome: 'Charuto de repolho', busca: 'charuto repolho', p: 6.8, kcal: 78, carb: 10.1, gord: 1.1, fibra: 1.5, gUn: 75, qtd: 2, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'zinco', valor: 1.8, un: 'mg', pct: 16 }, taco: 532 }, /* Charuto, de repolho */
  { id: 'tabule', nome: 'Tabule', busca: 'tabule', p: 2, kcal: 57, carb: 10.6, gord: 1.2, fibra: 2.1, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'vitamina C', valor: 16, un: 'mg', pct: 16 }, taco: 549 }, /* Tabule */
  { id: 'salada-folhas', nome: 'Salada de folhas', busca: 'salada alface folhas verde rucula', p: 1.3, kcal: 11, carb: 1.7, gord: 0.2, fibra: 1.8, gUn: 60, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Verduras e legumes', destaque: { nome: 'vitamina C', valor: 16, un: 'mg', pct: 16 }, taco: 78 }, /* Alface, crespa, crua */
  { id: 'tomate', nome: 'Tomate', busca: 'tomate', p: 0.8, kcal: 21, carb: 5.1, gord: 0, fibra: 2.3, gUn: 60, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Verduras e legumes', taco: 161 }, /* Tomate, salada */
  { id: 'brocolis', nome: 'Brócolis', busca: 'brocolis', p: 2.1, kcal: 25, carb: 4.4, gord: 0.5, fibra: 3.4, gUn: 80, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', destaque: { nome: 'vitamina C', valor: 42, un: 'mg', pct: 42 }, taco: 100 }, /* Brócolis, cozido */
  { id: 'cenoura', nome: 'Cenoura cozida', busca: 'cenoura', p: 0.8, kcal: 30, carb: 6.7, gord: 0.2, fibra: 2.6, gUn: 20, qtd: 3, un: 'colher', unp: 'colheres', onde: 'Verduras e legumes', destaque: { nome: 'vitamina A', valor: 306, un: 'mcg', pct: 38 }, taco: 109 }, /* Cenoura, cozida */
  { id: 'beterraba', nome: 'Beterraba cozida', busca: 'beterraba', p: 1.3, kcal: 32, carb: 7.2, gord: 0.1, fibra: 1.9, gUn: 20, qtd: 3, un: 'colher', unp: 'colheres', onde: 'Verduras e legumes', taco: 97 }, /* Beterraba, cozida */
  { id: 'couve', nome: 'Couve refogada', busca: 'couve mineira', p: 1.7, kcal: 90, carb: 8.7, gord: 6.6, fibra: 5.7, gUn: 25, qtd: 2, un: 'colher', unp: 'colheres', onde: 'Verduras e legumes', destaque: { nome: 'vitamina C', valor: 77, un: 'mg', pct: 77 }, taco: 116 }, /* Couve, manteiga, refogada */
  { id: 'couve-flor', nome: 'Couve-flor', busca: 'couve flor', p: 1.2, kcal: 19, carb: 3.9, gord: 0.3, fibra: 2.1, gUn: 80, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', destaque: { nome: 'vitamina C', valor: 24, un: 'mg', pct: 24 }, taco: 118 }, /* Couve-flor, cozida */
  { id: 'espinafre', nome: 'Espinafre refogado', busca: 'espinafre', p: 2.7, kcal: 67, carb: 4.2, gord: 5.4, fibra: 2.5, gUn: 30, qtd: 2, un: 'colher', unp: 'colheres', onde: 'Verduras e legumes', destaque: { nome: 'vitamina A', valor: 312, un: 'mcg', pct: 39 }, taco: 120 }, /* Espinafre, Nova Zelândia, refogado */
  { id: 'abobora', nome: 'Abóbora cozida', busca: 'abobora jerimum cabotia', p: 1.4, kcal: 48, carb: 10.8, gord: 0.7, fibra: 2.5, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', taco: 64 }, /* Abóbora, cabotian, cozida */
  { id: 'chuchu', nome: 'Chuchu cozido', busca: 'chuchu', p: 0.4, kcal: 19, carb: 4.8, gord: 0, fibra: 1, gUn: 80, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', taco: 112 }, /* Chuchu, cozido */
  { id: 'vagem', nome: 'Vagem', busca: 'vagem', p: 1.8, kcal: 25, carb: 5.3, gord: 0.2, fibra: 2.4, gUn: 60, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', taco: 162 }, /* Vagem, crua */
  { id: 'quiabo', nome: 'Quiabo', busca: 'quiabo', p: 1.9, kcal: 30, carb: 6.4, gord: 0.3, fibra: 4.6, gUn: 60, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', destaque: { nome: 'fibra', valor: 4.6, un: 'g', pct: 18 }, taco: 147 }, /* Quiabo, cru */
  { id: 'repolho', nome: 'Repolho', busca: 'repolho', p: 0.9, kcal: 17, carb: 3.9, gord: 0.1, fibra: 1.9, gUn: 50, qtd: 1, un: 'pires', unp: 'pires', onde: 'Verduras e legumes', destaque: { nome: 'vitamina C', valor: 19, un: 'mg', pct: 19 }, taco: 149 }, /* Repolho, branco, cru */
  { id: 'pepino', nome: 'Pepino', busca: 'pepino', p: 0.9, kcal: 10, carb: 2, gord: 0, fibra: 1.1, gUn: 100, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Verduras e legumes', taco: 142 }, /* Pepino, cru */
  { id: 'mandioca', nome: 'Mandioca cozida', busca: 'mandioca aipim macaxeira', p: 0.6, kcal: 125, carb: 30.1, gord: 0.3, fibra: 1.6, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', taco: 129 }, /* Mandioca, cozida */
  { id: 'mandioca-frita', nome: 'Mandioca frita', busca: 'mandioca frita aipim', p: 1.4, kcal: 300, carb: 50.3, gord: 11.2, fibra: 1.9, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', destaque: { nome: 'magnésio', valor: 95, un: 'mg', pct: 23 }, taco: 132 }, /* Mandioca, frita */
  { id: 'batata', nome: 'Batata cozida', busca: 'batata inglesa cozida pure', p: 1.2, kcal: 52, carb: 11.9, gord: 0, fibra: 1.3, gUn: 120, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Verduras e legumes', taco: 91 }, /* Batata, inglesa, cozida */
  { id: 'batata-frita', nome: 'Batata frita', busca: 'batata frita fritas', p: 5, kcal: 267, carb: 35.6, gord: 13.1, fibra: 8.1, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Verduras e legumes', destaque: { nome: 'fibra', valor: 8.1, un: 'g', pct: 32 }, taco: 93 }, /* Batata, inglesa, frita */
  { id: 'batata-doce', nome: 'Batata doce', busca: 'batata doce', p: 0.6, kcal: 77, carb: 18.4, gord: 0.1, fibra: 2.2, gUn: 120, qtd: 1, un: 'pedaço', unp: 'pedaços', onde: 'Verduras e legumes', destaque: { nome: 'vitamina C', valor: 24, un: 'mg', pct: 24 }, taco: 88 }, /* Batata, doce, cozida */
  { id: 'milho', nome: 'Milho verde', busca: 'milho verde lata', p: 3.2, kcal: 98, carb: 17.1, gord: 2.4, fibra: 4.6, gUn: 27, qtd: 3, un: 'colher', unp: 'colheres', onde: 'Arroz, massas e pães', destaque: { nome: 'niacina', valor: 3.7, un: 'mg', pct: 25 }, taco: 45 }, /* Milho, verde, enlatado, drenado */
  { id: 'farofa', nome: 'Farofa', busca: 'farofa farinha mandioca', p: 2.1, kcal: 406, carb: 80.3, gord: 9.1, fibra: 7.8, gUn: 15, qtd: 2, un: 'colher', unp: 'colheres', onde: 'Verduras e legumes', destaque: { nome: 'fibra', valor: 7.8, un: 'g', pct: 31 }, taco: 131 }, /* Mandioca, farofa, temperada */
  { id: 'banana', nome: 'Banana', busca: 'banana', p: 1.3, kcal: 98, carb: 26, gord: 0.1, fibra: 2, gUn: 90, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Frutas', destaque: { nome: 'vitamina C', valor: 22, un: 'mg', pct: 22 }, taco: 182 }, /* Banana, prata, crua */
  { id: 'maca', nome: 'Maçã', busca: 'maca fruta', p: 0.2, kcal: 63, carb: 16.6, gord: 0.2, fibra: 2, gUn: 130, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Frutas', taco: 221 }, /* Maçã, Argentina, com casca, crua */
  { id: 'abacate', nome: 'Abacate', busca: 'abacate guacamole', p: 1.2, kcal: 96, carb: 6, gord: 8.4, fibra: 6.3, gUn: 200, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Frutas', destaque: { nome: 'fibra', valor: 6.3, un: 'g', pct: 25 }, taco: 163 }, /* Abacate, cru */
  { id: 'abacaxi', nome: 'Abacaxi', busca: 'abacaxi', p: 0.9, kcal: 48, carb: 12.3, gord: 0.1, fibra: 1, gUn: 50, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Frutas', destaque: { nome: 'vitamina C', valor: 35, un: 'mg', pct: 35 }, taco: 164 }, /* Abacaxi, cru */
  { id: 'goiaba', nome: 'Goiaba', busca: 'goiaba', p: 1.1, kcal: 54, carb: 13, gord: 0.4, fibra: 6.2, gUn: 100, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Frutas', destaque: { nome: 'vitamina C', valor: 81, un: 'mg', pct: 81 }, taco: 200 }, /* Goiaba, vermelha, com casca, crua */
  { id: 'laranja', nome: 'Laranja', busca: 'laranja', p: 1, kcal: 37, carb: 8.9, gord: 0.1, fibra: 0.8, gUn: 130, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Frutas', destaque: { nome: 'vitamina C', valor: 54, un: 'mg', pct: 54 }, taco: 214 }, /* Laranja, pêra, crua */
  { id: 'mamao', nome: 'Mamão', busca: 'mamao papaia formosa', p: 0.8, kcal: 45, carb: 11.6, gord: 0.1, fibra: 1.8, gUn: 150, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Frutas', destaque: { nome: 'vitamina C', valor: 79, un: 'mg', pct: 79 }, taco: 225 }, /* Mamão, Formosa, cru */
  { id: 'manga', nome: 'Manga', busca: 'manga', p: 0.9, kcal: 51, carb: 12.8, gord: 0.2, fibra: 2.1, gUn: 150, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Frutas', taco: 231 }, /* Manga, Tommy Atkins, crua */
  { id: 'melancia', nome: 'Melancia', busca: 'melancia', p: 0.9, kcal: 33, carb: 8.1, gord: 0, fibra: 0.1, gUn: 200, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Frutas', taco: 235 }, /* Melancia, crua */
  { id: 'morango', nome: 'Morango', busca: 'morango', p: 0.9, kcal: 30, carb: 6.8, gord: 0.3, fibra: 1.7, gUn: 100, qtd: 1, un: 'xícara', unp: 'xícaras', onde: 'Frutas', destaque: { nome: 'vitamina C', valor: 64, un: 'mg', pct: 64 }, taco: 239 }, /* Morango, cru */
  { id: 'uva', nome: 'Uva', busca: 'uva', p: 0.7, kcal: 53, carb: 13.6, gord: 0.2, fibra: 0.9, gUn: 100, qtd: 1, un: 'cacho', unp: 'cachos', onde: 'Frutas', taco: 256 }, /* Uva, Itália, crua */
  { id: 'castanha-caju', nome: 'Castanha de caju', busca: 'castanha caju', p: 18.5, kcal: 570, carb: 29.1, gord: 46.3, fibra: 3.7, gUn: 30, qtd: 1, un: 'punhado', unp: 'punhados', onde: 'Castanhas e sementes', destaque: { nome: 'proteína', valor: 19, un: 'g', pct: 37 }, taco: 588 }, /* Castanha-de-caju, torrada, salgada */
  { id: 'castanha-para', nome: 'Castanha do Pará', busca: 'castanha para brasil', p: 14.5, kcal: 643, carb: 15.1, gord: 63.5, fibra: 7.9, gUn: 7, qtd: 3, un: 'unidade', unp: 'unidades', onde: 'Castanhas e sementes', destaque: { nome: 'fósforo', valor: 853, un: 'mg', pct: 122 }, taco: 589 }, /* Castanha-do-Brasil, crua */
  { id: 'amendoim', nome: 'Amendoim', busca: 'amendoim', p: 22.5, kcal: 606, carb: 18.7, gord: 54, fibra: 7.8, gUn: 30, qtd: 1, un: 'punhado', unp: 'punhados', onde: 'Grãos e feijões', destaque: { nome: 'proteína', valor: 22, un: 'g', pct: 45 }, taco: 558 }, /* Amendoim, torrado, salgado */
  { id: 'pasta-amendoim', nome: 'Pasta de amendoim', busca: 'pasta de amendoim peanut', p: 25, kcal: 590, carb: 22, gord: 50, fibra: null, gUn: 20, qtd: 1, un: 'colher', unp: 'colheres', onde: 'Castanhas e sementes', destaque: { nome: 'proteína', valor: 25, un: 'g', pct: 50 }, fonte: 'rótulo' }, /* rótulo */
  { id: 'pacoca', nome: 'Paçoca', busca: 'pacoca amendoim doce', p: 16, kcal: 487, carb: 52.4, gord: 26.1, fibra: 7.3, gUn: 25, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Grãos e feijões', destaque: { nome: 'proteína', valor: 16, un: 'g', pct: 32 }, taco: 579 }, /* Paçoca, amendoim */
  { id: 'amendoa', nome: 'Amêndoas', busca: 'amendoa amendoas nuts', p: 18.6, kcal: 581, carb: 29.5, gord: 47.3, fibra: 11.6, gUn: 30, qtd: 1, un: 'punhado', unp: 'punhados', onde: 'Castanhas e sementes', destaque: { nome: 'proteína', valor: 19, un: 'g', pct: 37 }, taco: 587 }, /* Amêndoa, torrada, salgada */
  { id: 'granola', nome: 'Granola', busca: 'granola aveia mel cereal barra', p: 9, kcal: 430, carb: 65, gord: 14, fibra: null, gUn: 12, qtd: 3, un: 'colher', unp: 'colheres', onde: 'Arroz, massas e pães', destaque: { nome: 'proteína', valor: 9, un: 'g', pct: 18 }, fonte: 'rótulo' }, /* rótulo */
  { id: 'cottage', nome: 'Queijo cottage', busca: 'cottage queijo branco fresco', p: 11, kcal: 98, carb: 3.4, gord: 4.3, fibra: null, gUn: 50, qtd: 2, un: 'colher', unp: 'colheres', onde: 'Leite e queijos', destaque: { nome: 'proteína', valor: 11, un: 'g', pct: 22 }, fonte: 'rótulo' }, /* rótulo */
  { id: 'barra-proteina', nome: 'Barra de proteína', busca: 'barra de proteina protein bar', p: 33, kcal: 350, carb: 40, gord: 10, fibra: null, gUn: 45, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Suplementos', destaque: { nome: 'proteína', valor: 33, un: 'g', pct: 66 }, fonte: 'rótulo' }, /* rótulo */
  { id: 'ovo-codorna', nome: 'Ovo de codorna', busca: 'ovo codorna ovinho', p: 13.7, kcal: 177, carb: 0.8, gord: 12.7, fibra: null, gUn: 10, qtd: 4, un: 'unidade', unp: 'unidades', onde: 'Ovos', destaque: { nome: 'fósforo', valor: 279, un: 'mg', pct: 40 }, taco: 485 }, /* Ovo, de codorna, inteiro, cru */
  { id: 'torrada', nome: 'Torrada', busca: 'torrada pao torrado', p: 10.5, kcal: 377, carb: 74.6, gord: 3.3, fibra: 3.4, gUn: 8, qtd: 2, un: 'fatia', unp: 'fatias', onde: 'Arroz, massas e pães', destaque: { nome: 'tiamina', valor: 0.4, un: 'mg', pct: 31 }, taco: 63 }, /* Torrada, pão francês */
  { id: 'biscoito-salgado', nome: 'Biscoito cream cracker', busca: 'biscoito salgado cream cracker agua e sal bolacha', p: 10.1, kcal: 432, carb: 68.7, gord: 14.4, fibra: 2.5, gUn: 6, qtd: 4, un: 'unidade', unp: 'unidades', onde: 'Arroz, massas e pães', destaque: { nome: 'tiamina', valor: 0.7, un: 'mg', pct: 59 }, taco: 13 }, /* Biscoito, salgado, cream cracker */
  { id: 'biscoito-recheado', nome: 'Biscoito recheado', busca: 'biscoito recheado bolacha doce', p: 6.4, kcal: 472, carb: 70.5, gord: 19.6, fibra: 3, gUn: 15, qtd: 3, un: 'unidade', unp: 'unidades', onde: 'Arroz, massas e pães', destaque: { nome: 'riboflavina', valor: 0.4, un: 'mg', pct: 33 }, taco: 9 }, /* Biscoito, doce, recheado com chocolate */
  { id: 'bolo-chocolate', nome: 'Bolo de chocolate', busca: 'bolo chocolate fatia doce', p: 6.2, kcal: 410, carb: 54.7, gord: 18.5, fibra: 1.4, gUn: 60, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Arroz, massas e pães', destaque: { nome: 'fósforo', valor: 197, un: 'mg', pct: 28 }, taco: 16 }, /* Bolo, pronto, chocolate */
  { id: 'pipoca', nome: 'Pipoca', busca: 'pipoca milho estourado', p: 9.9, kcal: 448, carb: 70.3, gord: 15.9, fibra: 14.3, gUn: 30, qtd: 1, un: 'porção', unp: 'porções', onde: 'Arroz, massas e pães', destaque: { nome: 'fibra', valor: 14, un: 'g', pct: 57 }, taco: 61 }, /* Pipoca, com óleo de soja, sem sal */
  { id: 'chocolate', nome: 'Chocolate ao leite', busca: 'chocolate barra ao leite bombom', p: 7.2, kcal: 540, carb: 59.6, gord: 30.3, fibra: 2.2, gUn: 25, qtd: 1, un: 'porção', unp: 'porções', onde: 'Doces e lanches', destaque: { nome: 'fósforo', valor: 212, un: 'mg', pct: 30 }, taco: 495 }, /* Chocolate, ao leite */
  { id: 'suco-laranja', nome: 'Suco de laranja', busca: 'suco laranja natural', p: 0.7, kcal: 33, carb: 7.6, gord: 0.1, fibra: 0, gUn: 200, qtd: 1, un: 'copo', unp: 'copos', onde: 'Frutas', destaque: { nome: 'vitamina C', valor: 73, un: 'mg', pct: 73 }, taco: 215 }, /* Laranja, pêra, suco */
  { id: 'palmito', nome: 'Palmito em conserva', busca: 'palmito conserva pupunha', p: 2.5, kcal: 29, carb: 5.5, gord: 0.5, fibra: 2.5, gUn: 30, qtd: 3, un: 'tolete', unp: 'toletes', onde: 'Verduras e legumes', taco: 139 }, /* Palmito, pupunha, em conserva */
  { id: 'pimentao', nome: 'Pimentão', busca: 'pimentao cru salada', p: 1.2, kcal: 28, carb: 6, gord: 0.4, fibra: 1.9, gUn: 30, qtd: 2, un: 'rodela', unp: 'rodelas', onde: 'Verduras e legumes', destaque: { nome: 'vitamina C', valor: 201, un: 'mg', pct: 201 }, taco: 143 }, /* Pimentão, amarelo, cru */
  { id: 'barra-cereal', nome: 'Barra de cereal', busca: 'barra de cereal snack lanche', p: 6, kcal: 400, carb: 70, gord: 10, fibra: null, gUn: 25, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', fonte: 'rótulo' }, /* rótulo */
  { id: 'carbonara', nome: 'Macarrão à carbonara', busca: 'carbonara massa bacon ovo', p: 9.5, kcal: 173, carb: 22.3, gord: 4.7, fibra: null, gUn: 295, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 9.5, un: 'g', pct: 19 }, fonte: 'soma TACO 40×180g÷2,2 + 489×55g + 439×40g + 464×20g' }, /* soma TACO 40×180g÷2,2 + 489×55g + 439×40g + 464×20g */
  { id: 'macarrao-alho', nome: 'Macarrão ao alho e óleo', busca: 'macarrao alho e oleo massa simples', p: 6.2, kcal: 184, carb: 33.7, gord: 2.3, fibra: null, gUn: 190, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', fonte: 'soma TACO 40×180g÷2,2 + 464×10g' }, /* soma TACO 40×180g÷2,2 + 464×10g */
  { id: 'macarrao-queijos', nome: 'Macarrão aos quatro queijos', busca: 'macarrao quatro queijos massa', p: 9.3, kcal: 223, carb: 23.2, gord: 10.2, fibra: null, gUn: 275, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 9.3, un: 'g', pct: 19 }, fonte: 'soma TACO 40×170g÷2,2 + 463×45g + 464×20g + 447×40g' }, /* soma TACO 40×170g÷2,2 + 463×45g + 464×20g + 447×40g */
  { id: 'lasanha-carne', nome: 'Lasanha de carne', busca: 'lasanha bolonhesa carne', p: 15.4, kcal: 213, carb: 16.9, gord: 9, fibra: null, gUn: 240, qtd: 1, un: 'pedaço', unp: 'pedaços', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 15.4, un: 'g', pct: 31 }, fonte: 'soma TACO 37×120g + 326×70g + 463×50g' }, /* soma TACO 37×120g + 326×70g + 463×50g */
  { id: 'lasanha-frango', nome: 'Lasanha de frango', busca: 'lasanha de frango', p: 14.9, kcal: 200, carb: 16.9, gord: 7.9, fibra: null, gUn: 240, qtd: 1, un: 'pedaço', unp: 'pedaços', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 14.9, un: 'g', pct: 30 }, fonte: 'soma TACO 37×120g + 404×70g + 463×50g' }, /* soma TACO 37×120g + 404×70g + 463×50g */
  { id: 'lasanha-presunto', nome: 'Lasanha de presunto e queijo', busca: 'lasanha presunto queijo quatro queijos', p: 11.7, kcal: 195, carb: 19.6, gord: 7.7, fibra: null, gUn: 230, qtd: 1, un: 'pedaço', unp: 'pedaços', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 11.7, un: 'g', pct: 23 }, fonte: 'soma TACO 37×130g + 439×40g + 463×60g' }, /* soma TACO 37×130g + 439×40g + 463×60g */
  { id: 'nhoque', nome: 'Nhoque ao sugo', busca: 'nhoque gnocchi batata', p: 2.8, kcal: 66, carb: 10, gord: 1.7, fibra: null, gUn: 295, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', fonte: 'soma TACO 91×220g + 161×60g + 464×15g' }, /* soma TACO 91×220g + 161×60g + 464×15g */
  { id: 'parmegiana-frango', nome: 'Filé de frango à parmegiana', busca: 'parmegiana parmigiana frango milanesa com queijo', p: 23.2, kcal: 213, carb: 6.3, gord: 10.1, fibra: null, gUn: 200, qtd: 1, un: 'filé', unp: 'filés', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 23.2, un: 'g', pct: 46 }, fonte: 'soma TACO 401×130g + 463×40g + 161×30g' }, /* soma TACO 401×130g + 463×40g + 161×30g */
  { id: 'parmegiana-carne', nome: 'Filé de carne à parmegiana', busca: 'parmegiana parmigiana carne bife milanesa com queijo', p: 18, kcal: 298, carb: 9.3, gord: 20.6, fibra: null, gUn: 200, qtd: 1, un: 'filé', unp: 'filés', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 18, un: 'g', pct: 36 }, fonte: 'soma TACO 340×130g + 463×40g + 161×30g' }, /* soma TACO 340×130g + 463×40g + 161×30g */
  { id: 'bife-milanesa', nome: 'Bife à milanesa', busca: 'bife a milanesa empanado carne', p: 20.6, kcal: 352, carb: 12.2, gord: 24, fibra: null, gUn: 130, qtd: 1, un: 'filé', unp: 'filés', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 20.6, un: 'g', pct: 41 }, fonte: 'soma TACO 340×130g' }, /* soma TACO 340×130g */
  { id: 'galinhada', nome: 'Galinhada', busca: 'galinhada arroz com frango', p: 11, kcal: 144, carb: 17.4, gord: 2.8, fibra: null, gUn: 290, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 11, un: 'g', pct: 22 }, fonte: 'soma TACO 3×180g + 404×110g' }, /* soma TACO 3×180g + 404×110g */
  { id: 'escondidinho-carne', nome: 'Escondidinho de carne moída', busca: 'escondidinho carne moida pure', p: 10.1, kcal: 171, carb: 19, gord: 5.8, fibra: null, gUn: 290, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 10.1, un: 'g', pct: 20 }, fonte: 'soma TACO 129×180g + 326×80g + 463×30g' }, /* soma TACO 129×180g + 326×80g + 463×30g */
  { id: 'escondidinho-carne-seca', nome: 'Escondidinho de carne seca', busca: 'escondidinho carne seca charque pure', p: 10.1, kcal: 198, carb: 19, gord: 8.8, fibra: null, gUn: 290, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 10.1, un: 'g', pct: 20 }, fonte: 'soma TACO 129×180g + 384×80g + 463×30g' }, /* soma TACO 129×180g + 384×80g + 463×30g */
  { id: 'escondidinho-frango', nome: 'Escondidinho de frango', busca: 'escondidinho de frango pure', p: 9.6, kcal: 159, carb: 19, gord: 4.7, fibra: null, gUn: 290, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 9.6, un: 'g', pct: 19 }, fonte: 'soma TACO 129×180g + 404×80g + 463×30g' }, /* soma TACO 129×180g + 404×80g + 463×30g */
  { id: 'panqueca-carne', nome: 'Panqueca de carne', busca: 'panqueca de carne moida', p: 12.7, kcal: 155, carb: 15.2, gord: 4.6, fibra: null, gUn: 160, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 12.7, un: 'g', pct: 25 }, fonte: 'soma TACO 37×70g + 326×60g + 161×30g' }, /* soma TACO 37×70g + 326×60g + 161×30g */
  { id: 'panqueca-frango', nome: 'Panqueca de frango', busca: 'panqueca de frango', p: 12.1, kcal: 139, carb: 15.2, gord: 3.2, fibra: null, gUn: 160, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 12.1, un: 'g', pct: 24 }, fonte: 'soma TACO 37×70g + 404×60g + 161×30g' }, /* soma TACO 37×70g + 404×60g + 161×30g */
  { id: 'torta-frango', nome: 'Torta de frango', busca: 'torta salgada de frango empadao', p: 6.9, kcal: 358, carb: 47.5, gord: 15.6, fibra: null, gUn: 150, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Pratos prontos', fonte: 'soma TACO 389×150g' }, /* soma TACO 389×150g */
  { id: 'crepe-carne', nome: 'Crepe de carne', busca: 'crepe de carne moida', p: 14.9, kcal: 207, carb: 17.8, gord: 8.3, fibra: null, gUn: 170, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 14.9, un: 'g', pct: 30 }, fonte: 'soma TACO 37×90g + 326×50g + 463×30g' }, /* soma TACO 37×90g + 326×50g + 463×30g */
  { id: 'crepe-frango', nome: 'Crepe de frango', busca: 'crepe de frango com catupiry', p: 12.1, kcal: 190, carb: 18.2, gord: 7.5, fibra: null, gUn: 170, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 12.1, un: 'g', pct: 24 }, fonte: 'soma TACO 37×90g + 404×50g + 465×30g' }, /* soma TACO 37×90g + 404×50g + 465×30g */
  { id: 'crepe-queijo', nome: 'Crepe de queijo', busca: 'crepe de queijo presunto', p: 11.6, kcal: 192, carb: 19.5, gord: 7.5, fibra: null, gUn: 160, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 11.6, un: 'g', pct: 23 }, fonte: 'soma TACO 37×90g + 463×40g + 439×30g' }, /* soma TACO 37×90g + 463×40g + 439×30g */
  { id: 'pizza-mussarela', nome: 'Pizza de mussarela', busca: 'pizza mussarela marguerita', p: 11.2, kcal: 263, carb: 33.7, gord: 8.9, fibra: null, gUn: 135, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 11.2, un: 'g', pct: 22 }, fonte: 'soma TACO 54×70g + 463×40g + 161×25g' }, /* soma TACO 54×70g + 463×40g + 161×25g */
  { id: 'pizza-calabresa', nome: 'Pizza de calabresa', busca: 'pizza calabresa', p: 13.6, kcal: 299, carb: 35, gord: 11, fibra: null, gUn: 125, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 13.6, un: 'g', pct: 27 }, fonte: 'soma TACO 54×70g + 463×25g + 420×30g' }, /* soma TACO 54×70g + 463×25g + 420×30g */
  { id: 'pizza-frango', nome: 'Pizza de frango com catupiry', busca: 'pizza frango catupiry', p: 12.9, kcal: 273, carb: 33.1, gord: 9.4, fibra: null, gUn: 135, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 12.9, un: 'g', pct: 26 }, fonte: 'soma TACO 54×70g + 404×35g + 465×30g' }, /* soma TACO 54×70g + 404×35g + 465×30g */
  { id: 'pizza-portuguesa', nome: 'Pizza portuguesa', busca: 'pizza portuguesa presunto ovo', p: 12.7, kcal: 252, carb: 31.7, gord: 7.8, fibra: null, gUn: 140, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 12.7, un: 'g', pct: 25 }, fonte: 'soma TACO 54×70g + 463×25g + 439×25g + 488×20g' }, /* soma TACO 54×70g + 463×25g + 439×25g + 488×20g */
  { id: 'sanduiche-frango', nome: 'Sanduíche de frango', busca: 'sanduiche natural lanche de frango', p: 18.5, kcal: 174, carb: 20, gord: 2.6, fibra: null, gUn: 130, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 18.5, un: 'g', pct: 37 }, fonte: 'soma TACO 52×50g + 410×60g + 161×20g' }, /* soma TACO 52×50g + 410×60g + 161×20g */
  { id: 'sanduiche-atum', nome: 'Sanduíche de atum', busca: 'sanduiche natural lanche de atum', p: 15.4, kcal: 178, carb: 20.8, gord: 4.1, fibra: null, gUn: 125, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 15.4, un: 'g', pct: 31 }, fonte: 'soma TACO 52×50g + 277×55g + 161×20g' }, /* soma TACO 52×50g + 277×55g + 161×20g */
  { id: 'sanduiche-peru', nome: 'Sanduíche de peito de peru', busca: 'sanduiche peito de peru queijo branco', p: 17, kcal: 224, carb: 22.4, gord: 7.9, fibra: null, gUn: 115, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 17, un: 'g', pct: 34 }, fonte: 'soma TACO 52×50g + 425×40g + 461×25g' }, /* soma TACO 52×50g + 425×40g + 461×25g */
  { id: 'x-salada', nome: 'X-salada', busca: 'x salada hamburguer lanche burguer', p: 13.3, kcal: 239, carb: 22.6, gord: 10.5, fibra: null, gUn: 225, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 13.3, un: 'g', pct: 27 }, fonte: 'soma TACO 54×70g + 416×90g + 463×25g + 78×20g + 161×20g' }, /* soma TACO 54×70g + 416×90g + 463×25g + 78×20g + 161×20g */
  { id: 'misto-quente', nome: 'Misto quente', busca: 'misto quente queijo presunto', p: 14.4, kcal: 231, carb: 24.1, gord: 9.3, fibra: null, gUn: 110, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 14.4, un: 'g', pct: 29 }, fonte: 'soma TACO 52×50g + 463×30g + 439×30g' }, /* soma TACO 52×50g + 463×30g + 439×30g */
  { id: 'tapioca-frango', nome: 'Tapioca de frango', busca: 'tapioca recheada de frango', p: 10, kcal: 277, carb: 38.2, gord: 9.4, fibra: null, gUn: 150, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 10, un: 'g', pct: 20 }, fonte: 'soma TACO 551×90g + 404×60g' }, /* soma TACO 551×90g + 404×60g */
  { id: 'tapioca-queijo', nome: 'Tapioca de queijo', busca: 'tapioca recheada de queijo coco', p: 5.4, kcal: 322, carb: 45, gord: 13.8, fibra: null, gUn: 130, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', fonte: 'soma TACO 551×90g + 461×40g' }, /* soma TACO 551×90g + 461×40g */
  { id: 'esfiha', nome: 'Esfiha de carne', busca: 'esfiha esfirra kibe aberto', p: 15.9, kcal: 270, carb: 36.1, gord: 6.2, fibra: null, gUn: 85, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 15.9, un: 'g', pct: 32 }, fonte: 'soma TACO 54×50g + 326×35g' }, /* soma TACO 54×50g + 326×35g */
  { id: 'pastel-carne', nome: 'Pastel de carne', busca: 'pastel de carne salgado frito', p: 14.5, kcal: 278, carb: 41, gord: 5.5, fibra: null, gUn: 90, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 14.5, un: 'g', pct: 29 }, fonte: 'soma TACO 54×60g + 326×30g' }, /* soma TACO 54×60g + 326×30g */
  { id: 'pastel-queijo', nome: 'Pastel de queijo', busca: 'pastel de queijo salgado frito', p: 13.1, kcal: 317, carb: 42, gord: 10.3, fibra: null, gUn: 90, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 13.1, un: 'g', pct: 26 }, fonte: 'soma TACO 54×60g + 463×30g' }, /* soma TACO 54×60g + 463×30g */
  { id: 'croquete', nome: 'Croquete de carne', busca: 'croquete de carne salgado', p: 16.9, kcal: 347, carb: 18.1, gord: 22.7, fibra: null, gUn: 45, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 16.9, un: 'g', pct: 34 }, fonte: 'soma TACO 388×45g' }, /* soma TACO 388×45g */
  { id: 'empada-frango', nome: 'Empada de frango', busca: 'empada empadinha de frango', p: 6.9, kcal: 358, carb: 47.5, gord: 15.6, fibra: null, gUn: 70, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', fonte: 'soma TACO 389×70g' }, /* soma TACO 389×70g */
  { id: 'moqueca', nome: 'Moqueca de peixe', busca: 'moqueca peixe dende', p: 21.2, kcal: 101, carb: 1.1, gord: 0.7, fibra: null, gUn: 190, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 21.2, un: 'g', pct: 42 }, fonte: 'soma TACO 301×150g + 161×40g' }, /* soma TACO 301×150g + 161×40g */
  { id: 'bobo-camarao', nome: 'Bobó de camarão', busca: 'bobo de camarao', p: 7.8, kcal: 112, carb: 18.3, gord: 0.6, fibra: null, gUn: 230, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 7.8, un: 'g', pct: 16 }, fonte: 'soma TACO 284×90g + 129×140g' }, /* soma TACO 284×90g + 129×140g */
  { id: 'bacalhau-natas', nome: 'Bacalhau com batata', busca: 'bacalhau com natas batata portuguesa', p: 9.9, kcal: 108, carb: 6.9, gord: 4.5, fibra: null, gUn: 290, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 9.9, un: 'g', pct: 20 }, fonte: 'soma TACO 280×110g + 91×140g + 447×40g' }, /* soma TACO 280×110g + 91×140g + 447×40g */
  { id: 'sushi', nome: 'Sushi de salmão', busca: 'sushi sashimi temaki japonesa salmao', p: 11.9, kcal: 172, carb: 15.8, gord: 6.3, fibra: null, gUn: 160, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 11.9, un: 'g', pct: 24 }, fonte: 'soma TACO 3×90g + 315×70g' }, /* soma TACO 3×90g + 315×70g */
  { id: 'risoto-camarao', nome: 'Risoto de camarão', busca: 'risoto risotto de camarao', p: 8.7, kcal: 134, carb: 19.1, gord: 2.1, fibra: null, gUn: 295, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 8.7, un: 'g', pct: 17 }, fonte: 'soma TACO 3×200g + 284×80g + 464×15g' }, /* soma TACO 3×200g + 284×80g + 464×15g */
  { id: 'risoto-frango', nome: 'Risoto de frango', busca: 'risoto risotto de frango', p: 11.9, kcal: 158, carb: 19.5, gord: 3.1, fibra: null, gUn: 290, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 11.9, un: 'g', pct: 24 }, fonte: 'soma TACO 3×200g + 410×70g + 464×20g' }, /* soma TACO 3×200g + 410×70g + 464×20g */
  { id: 'canja', nome: 'Canja de galinha', busca: 'canja sopa de frango com arroz', p: 14.6, kcal: 151, carb: 13, gord: 3.9, fibra: null, gUn: 130, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 14.6, un: 'g', pct: 29 }, fonte: 'soma TACO 3×60g + 404×70g' }, /* soma TACO 3×60g + 404×70g */
  { id: 'sopa-legumes', nome: 'Sopa de legumes', busca: 'sopa caldo de legumes', p: 2, kcal: 35, carb: 7.1, gord: 0.3, fibra: null, gUn: 250, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', fonte: 'soma TACO 546×250g' }, /* soma TACO 546×250g */
  { id: 'sopa-feijao', nome: 'Caldo de feijão', busca: 'caldo sopa de feijao', p: 6.4, kcal: 96, carb: 12, gord: 2.7, fibra: null, gUn: 250, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', fonte: 'soma TACO 561×220g + 420×30g' }, /* soma TACO 561×220g + 420×30g */
  { id: 'sopa-carne', nome: 'Sopa de carne com legumes', busca: 'sopa de carne legumes musculo', p: 11.7, kcal: 88, carb: 4.7, gord: 2.4, fibra: null, gUn: 270, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 11.7, un: 'g', pct: 23 }, fonte: 'soma TACO 371×90g + 546×180g' }, /* soma TACO 371×90g + 546×180g */
  { id: 'mingau-aveia', nome: 'Mingau de aveia', busca: 'mingau de aveia leite overnight', p: 5, kcal: 116, carb: 15, gord: 4.1, fibra: null, gUn: 240, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Café da manhã', fonte: 'soma TACO 7×40g + leite TBCA×200g' }, /* soma TACO 7×40g + leite TBCA×200g */
  { id: 'vitamina-banana', nome: 'Vitamina de banana', busca: 'vitamina batida de banana leite', p: 3.3, kcal: 93, carb: 14.9, gord: 2.6, fibra: null, gUn: 310, qtd: 1, un: 'copo', unp: 'copos', onde: 'Café da manhã', fonte: 'soma TACO leite TBCA×200g + 182×90g + 7×20g' }, /* soma TACO leite TBCA×200g + 182×90g + 7×20g */
  { id: 'panqueca-americana', nome: 'Panquecas americanas', busca: 'panqueca americana pancake hotcake', p: 7.9, kcal: 177, carb: 26.1, gord: 4.1, fibra: null, gUn: 190, qtd: 1, un: 'porção', unp: 'porções', onde: 'Café da manhã', destaque: { nome: 'proteína', valor: 7.9, un: 'g', pct: 16 }, fonte: 'soma TACO 35×60g + 489×50g + leite TBCA×80g' }, /* soma TACO 35×60g + 489×50g + leite TBCA×80g */
  { id: 'waffle', nome: 'Waffle', busca: 'waffle belga', p: 8.1, kcal: 193, carb: 30.3, gord: 3.9, fibra: null, gUn: 160, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Café da manhã', destaque: { nome: 'proteína', valor: 8.1, un: 'g', pct: 16 }, fonte: 'soma TACO 35×60g + 489×40g + leite TBCA×60g' }, /* soma TACO 35×60g + 489×40g + leite TBCA×60g */
  { id: 'crepioca', nome: 'Crepioca de queijo', busca: 'crepioca tapioca com ovo', p: 9.8, kcal: 242, carb: 22.7, gord: 12.4, fibra: null, gUn: 120, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Café da manhã', destaque: { nome: 'proteína', valor: 9.8, un: 'g', pct: 20 }, fonte: 'soma TACO 551×40g + 489×50g + 461×30g' }, /* soma TACO 551×40g + 489×50g + 461×30g */
  { id: 'iogurte-granola', nome: 'Iogurte com granola e fruta', busca: 'iogurte granola parfait grego bowl', p: 4, kcal: 106, carb: 14.7, gord: 3.6, fibra: null, gUn: 260, qtd: 1, un: 'tigela', unp: 'tigelas', onde: 'Café da manhã', fonte: 'soma TACO 448×170g + granola rótulo×30g + 182×60g' }, /* soma TACO 448×170g + granola rótulo×30g + 182×60g */
  { id: 'smoothie-proteico', nome: 'Smoothie de banana com whey', busca: 'smoothie shake proteico batida', p: 9.9, kcal: 101, carb: 11, gord: 2.5, fibra: null, gUn: 320, qtd: 1, un: 'copo', unp: 'copos', onde: 'Café da manhã', destaque: { nome: 'proteína', valor: 9.9, un: 'g', pct: 20 }, fonte: 'soma TACO 182×90g + leite TBCA×200g + whey rótulo×30g' }, /* soma TACO 182×90g + leite TBCA×200g + whey rótulo×30g */
  { id: 'torrada-abacate-ovo', nome: 'Torrada com abacate e ovo', busca: 'avocado toast torrada abacate ovo', p: 8.6, kcal: 229, carb: 25.9, gord: 10, fibra: null, gUn: 160, qtd: 1, un: 'porção', unp: 'porções', onde: 'Café da manhã', destaque: { nome: 'proteína', valor: 8.6, un: 'g', pct: 17 }, fonte: 'soma TACO 63×50g + 163×60g + 490×50g' }, /* soma TACO 63×50g + 163×60g + 490×50g */
  { id: 'shakshuka', nome: 'Shakshuka', busca: 'shakshuka ovos no molho de tomate arabe', p: 5.6, kcal: 76, carb: 5.7, gord: 3.7, fibra: null, gUn: 280, qtd: 1, un: 'porção', unp: 'porções', onde: 'Café da manhã', fonte: 'soma TACO 489×100g + 159×150g + 107×30g' }, /* soma TACO 489×100g + 159×150g + 107×30g */
  { id: 'croissant-presunto-queijo', nome: 'Croissant de presunto e queijo', busca: 'croissant misto frances padaria', p: 13, kcal: 266, carb: 34.7, gord: 7.9, fibra: null, gUn: 110, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Café da manhã', destaque: { nome: 'proteína', valor: 13, un: 'g', pct: 26 }, fonte: 'soma TACO 54×60g + 439×25g + 463×25g' }, /* soma TACO 54×60g + 439×25g + 463×25g */
  { id: 'bagel-cream-cheese', nome: 'Bagel com cream cheese', busca: 'bagel cream cheese requeijao pao', p: 8.3, kcal: 301, carb: 45.4, gord: 9.2, fibra: null, gUn: 120, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Café da manhã', destaque: { nome: 'proteína', valor: 8.3, un: 'g', pct: 17 }, fonte: 'soma TACO 53×90g + 465×30g' }, /* soma TACO 53×90g + 465×30g */
  { id: 'sanduiche-ovo', nome: 'Sanduíche de ovo', busca: 'sanduiche de ovo egg sandwich', p: 12, kcal: 182, carb: 17.1, gord: 7.5, fibra: null, gUn: 150, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Café da manhã', destaque: { nome: 'proteína', valor: 12, un: 'g', pct: 24 }, fonte: 'soma TACO 52×50g + 488×100g' }, /* soma TACO 52×50g + 488×100g */
  { id: 'acai-tigela', nome: 'Açaí na tigela', busca: 'acai tigela com granola', p: 1.6, kcal: 98, carb: 14.9, gord: 4.1, fibra: null, gUn: 340, qtd: 1, un: 'tigela', unp: 'tigelas', onde: 'Café da manhã', fonte: 'soma TACO 168×250g + granola rótulo×30g + 182×60g' }, /* soma TACO 168×250g + granola rótulo×30g + 182×60g */
  { id: 'ramen-carne', nome: 'Lámen com carne e ovo', busca: 'ramen lamen miojo japones sopa macarrao', p: 15.2, kcal: 294, carb: 27.9, gord: 13.3, fibra: null, gUn: 180, qtd: 1, un: 'tigela', unp: 'tigelas', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 15.2, un: 'g', pct: 30 }, fonte: 'soma TACO 39×80g + 328×50g + 488×50g' }, /* soma TACO 39×80g + 328×50g + 488×50g */
  { id: 'temaki-salmao', nome: 'Temaki de salmão', busca: 'temaki cone japones salmao', p: 9.7, kcal: 146, carb: 16, gord: 4.3, fibra: null, gUn: 140, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 9.7, un: 'g', pct: 19 }, fonte: 'soma TACO 3×80g + 316×60g' }, /* soma TACO 3×80g + 316×60g */
  { id: 'poke-salmao', nome: 'Poke de salmão', busca: 'poke bowl havaiano salmao', p: 7.7, kcal: 137, carb: 15.9, gord: 4.4, fibra: null, gUn: 280, qtd: 1, un: 'tigela', unp: 'tigelas', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 7.7, un: 'g', pct: 15 }, fonte: 'soma TACO 3×150g + 316×90g + 163×40g' }, /* soma TACO 3×150g + 316×90g + 163×40g */
  { id: 'gyoza-porco', nome: 'Guioza de porco', busca: 'guioza gyoza pastel japones porco', p: 16.8, kcal: 259, carb: 33.8, gord: 5.4, fibra: null, gUn: 100, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 16.8, un: 'g', pct: 34 }, fonte: 'soma TACO 35×45g + 433×55g' }, /* soma TACO 35×45g + 433×55g */
  { id: 'frango-xadrez', nome: 'Frango xadrez', busca: 'frango xadrez chines castanha', p: 23.1, kcal: 176, carb: 4.7, gord: 7.1, fibra: null, gUn: 170, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 23.1, un: 'g', pct: 46 }, fonte: 'soma TACO 410×110g + 588×20g + 145×40g' }, /* soma TACO 410×110g + 588×20g + 145×40g */
  { id: 'arroz-frito', nome: 'Arroz frito com ovo', busca: 'arroz frito yakimeshi chines chaufa', p: 5.1, kcal: 126, carb: 21.4, gord: 1.9, fibra: null, gUn: 260, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', fonte: 'soma TACO 3×180g + 489×50g + 559×30g' }, /* soma TACO 3×180g + 489×50g + 559×30g */
  { id: 'pad-thai-camarao', nome: 'Pad thai de camarão', busca: 'pad thai tailandes macarrao camarao', p: 9.4, kcal: 149, carb: 14.8, gord: 5.8, fibra: null, gUn: 215, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 9.4, un: 'g', pct: 19 }, fonte: 'soma TACO 40×80g÷2,2 + 285×80g + 489×40g + 558×15g' }, /* soma TACO 40×80g÷2,2 + 285×80g + 489×40g + 558×15g */
  { id: 'bibimbap', nome: 'Bibimbap', busca: 'bibimbap coreano arroz carne ovo', p: 8.9, kcal: 150, carb: 16.4, gord: 4.9, fibra: null, gUn: 330, qtd: 1, un: 'tigela', unp: 'tigelas', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 8.9, un: 'g', pct: 18 }, fonte: 'soma TACO 3×180g + 328×60g + 490×50g + 110×40g' }, /* soma TACO 3×180g + 328×60g + 490×50g + 110×40g */
  { id: 'taco-carne', nome: 'Taco de carne', busca: 'taco tacos mexicano carne', p: 20.1, kcal: 273, carb: 24.8, gord: 10.2, fibra: null, gUn: 130, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 20.1, un: 'g', pct: 40 }, fonte: 'soma TACO 33×40g + 326×70g + 463×20g' }, /* soma TACO 33×40g + 326×70g + 463×20g */
  { id: 'burrito-frango', nome: 'Burrito de frango', busca: 'burrito mexicano frango feijao', p: 13.7, kcal: 186, carb: 28.7, gord: 1.3, fibra: null, gUn: 270, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 13.7, un: 'g', pct: 27 }, fonte: 'soma TACO 35×70g + 410×80g + 561×60g + 3×60g' }, /* soma TACO 35×70g + 410×80g + 561×60g + 3×60g */
  { id: 'quesadilla-queijo', nome: 'Quesadilla de queijo', busca: 'quesadilla mexicana queijo tortilla', p: 15.6, kcal: 347, carb: 42.3, gord: 12.2, fibra: null, gUn: 110, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 15.6, un: 'g', pct: 31 }, fonte: 'soma TACO 35×60g + 463×50g' }, /* soma TACO 35×60g + 463×50g */
  { id: 'chili-carne', nome: 'Chili com carne', busca: 'chili con carne mexicano feijao', p: 12.3, kcal: 120, carb: 7.2, gord: 4.6, fibra: null, gUn: 260, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 12.3, un: 'g', pct: 25 }, fonte: 'soma TACO 326×100g + 567×100g + 159×60g' }, /* soma TACO 326×100g + 567×100g + 159×60g */
  { id: 'guacamole-nachos', nome: 'Guacamole com nachos', busca: 'guacamole nachos abacate mexicano', p: 3.2, kcal: 181, carb: 30.4, gord: 6.1, fibra: null, gUn: 120, qtd: 1, un: 'porção', unp: 'porções', onde: 'Doces e lanches', fonte: 'soma TACO 163×80g + 33×40g' }, /* soma TACO 163×80g + 33×40g */
  { id: 'homus-pao', nome: 'Homus com pão sírio', busca: 'homus hummus grao de bico arabe', p: 8.5, kcal: 213, carb: 38.9, gord: 2.6, fibra: null, gUn: 140, qtd: 1, un: 'porção', unp: 'porções', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 8.5, un: 'g', pct: 17 }, fonte: 'soma TACO 575×80g÷2,4 + 53×60g' }, /* soma TACO 575×80g÷2,4 + 53×60g */
  { id: 'falafel', nome: 'Falafel', busca: 'falafel bolinho de grao de bico arabe', p: 9, kcal: 178, carb: 31.4, gord: 2.1, fibra: null, gUn: 140, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 9, un: 'g', pct: 18 }, fonte: 'soma TACO 575×120g÷2,4 + 35×20g' }, /* soma TACO 575×120g÷2,4 + 35×20g */
  { id: 'shawarma-frango', nome: 'Shawarma de frango', busca: 'shawarma shauarma churrasco grego frango', p: 19.4, kcal: 192, carb: 20.8, gord: 2.8, fibra: null, gUn: 200, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 19.4, un: 'g', pct: 39 }, fonte: 'soma TACO 53×70g + 410×100g + 448×30g' }, /* soma TACO 53×70g + 410×100g + 448×30g */
  { id: 'kebab-carne', nome: 'Kebab de carne', busca: 'kebab kebap doner carne arabe turco', p: 15.9, kcal: 221, carb: 23.1, gord: 6.6, fibra: null, gUn: 180, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 15.9, un: 'g', pct: 32 }, fonte: 'soma TACO 53×70g + 328×80g + 448×30g' }, /* soma TACO 53×70g + 328×80g + 448×30g */
  { id: 'souvlaki-frango', nome: 'Espetinho grego de frango', busca: 'souvlaki espetinho grego frango tzatziki', p: 25, kcal: 132, carb: 0.5, gord: 2.6, fibra: null, gUn: 160, qtd: 1, un: 'espetinho', unp: 'espetinhos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 25, un: 'g', pct: 50 }, fonte: 'soma TACO 410×120g + 448×40g' }, /* soma TACO 410×120g + 448×40g */
  { id: 'tikka-masala', nome: 'Frango tikka masala', busca: 'tikka masala curry indiano frango', p: 16.1, kcal: 144, carb: 3.2, gord: 7.3, fibra: null, gUn: 230, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 16.1, un: 'g', pct: 32 }, fonte: 'soma TACO 410×110g + 447×60g + 159×60g' }, /* soma TACO 410×110g + 447×60g + 159×60g */
  { id: 'curry-grao-de-bico', nome: 'Curry de grão-de-bico', busca: 'curry indiano grao de bico vegetariano channa', p: 4.8, kcal: 132, carb: 13.8, gord: 7.1, fibra: null, gUn: 250, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', fonte: 'soma TACO 575×120g÷2,4 + 523×80g + 159×50g' }, /* soma TACO 575×120g÷2,4 + 523×80g + 159×50g */
  { id: 'paella-frutos-do-mar', nome: 'Paella de frutos do mar', busca: 'paella espanhola arroz camarao', p: 4.8, kcal: 103, carb: 19.4, gord: 0.3, fibra: null, gUn: 290, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', fonte: 'soma TACO 3×200g + 285×90g' }, /* soma TACO 3×200g + 285×90g */
  { id: 'tortilla-espanhola', nome: 'Tortilha espanhola', busca: 'tortilla espanhola omelete de batata', p: 5.9, kcal: 88, carb: 7.8, gord: 3.6, fibra: null, gUn: 250, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Pratos prontos', fonte: 'soma TACO 489×100g + 91×150g' }, /* soma TACO 489×100g + 91×150g */
  { id: 'quiche-queijo', nome: 'Quiche de queijo', busca: 'quiche torta francesa queijo', p: 12.1, kcal: 257, carb: 21.4, gord: 13.4, fibra: null, gUn: 175, qtd: 1, un: 'fatia', unp: 'fatias', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 12.1, un: 'g', pct: 24 }, fonte: 'soma TACO 35×45g + 489×55g + 463×40g + 447×35g' }, /* soma TACO 35×45g + 489×55g + 463×40g + 447×35g */
  { id: 'mac-and-cheese', nome: 'Macarrão com queijo cheddar', busca: 'mac and cheese macarrao queijo americano', p: 7.4, kcal: null, carb: null, gord: null, fibra: null, gUn: 280, qtd: 1, un: 'prato', unp: 'pratos', onde: 'Pratos prontos', fonte: 'soma TACO 40×150g÷2,2 + 467×50g + leite TBCA×80g' }, /* soma TACO 40×150g÷2,2 + 467×50g + leite TBCA×80g */
  { id: 'wrap-frango', nome: 'Wrap de frango', busca: 'wrap enrolado frango tortilla', p: 18.7, kcal: 206, carb: 27.4, gord: 1.7, fibra: null, gUn: 170, qtd: 1, un: 'unidade', unp: 'unidades', onde: 'Doces e lanches', destaque: { nome: 'proteína', valor: 18.7, un: 'g', pct: 37 }, fonte: 'soma TACO 35×60g + 410×80g + 161×30g' }, /* soma TACO 35×60g + 410×80g + 161×30g */
  { id: 'ceviche-peixe', nome: 'Ceviche de peixe', busca: 'ceviche peruano peixe limao', p: 14.2, kcal: 96, carb: 1.5, gord: 3.3, fibra: null, gUn: 180, qtd: 1, un: 'porção', unp: 'porções', onde: 'Pratos prontos', destaque: { nome: 'proteína', valor: 14.2, un: 'g', pct: 28 }, fonte: 'soma TACO 307×150g + 107×30g' }, /* soma TACO 307×150g + 107×30g */
];

/** "2 colheres", "1 filé" — o plural só quando é mais de um. */
export function medidaDe(a: Alimento, qtd: number): string {
  return `${qtd} ${qtd === 1 ? a.un : a.unp}`;
}

const semAcento = (s: string) =>
  s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();

/* Busca por prefixo de palavra, e não por trecho solto: "ova" não devia
   trazer "Ovo cozido" pelo meio de "abacate". O que começa igual ao que
   foi digitado vem primeiro; o resto vem depois, na ordem da lista. */
export function buscarAlimento(termo: string, limite = 6): Alimento[] {
  const t = semAcento(termo);
  if (t.length < 2) return [];
  const comeca: Alimento[] = [];
  const contem: Alimento[] = [];
  for (const a of ALIMENTOS) {
    const palavras = semAcento(a.nome + ' ' + a.busca).split(/[\s,]+/);
    if (palavras.some((p) => p.startsWith(t))) comeca.push(a);
    else if (palavras.some((p) => p.includes(t))) contem.push(a);
  }
  return [...comeca, ...contem].slice(0, limite);
}

/** Gramas de proteína de N unidades. Sempre arredondado: a precisão que
    existe aqui não chega na casa decimal. */
export function gramasDe(a: Alimento, qtd: number): number {
  return Math.round((a.p / 100) * a.gUn * Math.max(0, qtd));
}
