/* ============================================================
   OS NOMES DE PAÍS, NOS CINCO IDIOMAS

   ⚠️⚠️ ARQUIVO GERADO. Não edite à mão: rode

     node scripts/nomes-de-pais.mjs

   e ele reescreve tudo. O que se edita é a LISTA DE CÓDIGOS, em
   logic/pais — quem entra é decisão; como se escreve é o CLDR.

   ⚠️ E ELE É GERADO, E NÃO RESOLVIDO NO APARELHO, porque o aplicativo não
   usa `Intl` em tempo de execução e o Hermes não garante
   `Intl.DisplayNames`. Ver o alto do gerador.
   ============================================================ */

export const NOMES_DE_PAIS: Record<string, Record<string, string>> = {
  "pt-BR": {
    BR: "Brasil", PT: "Portugal", AO: "Angola", MZ: "Moçambique", CV: "Cabo Verde",
    GW: "Guiné-Bissau", ST: "São Tomé e Príncipe", TL: "Timor-Leste", US: "Estados Unidos",
    GB: "Reino Unido", AU: "Austrália", CA: "Canadá", NZ: "Nova Zelândia", IE: "Irlanda",
    ZA: "África do Sul", NG: "Nigéria", KE: "Quênia", GH: "Gana", PH: "Filipinas",
    SG: "Singapura", MY: "Malásia", PK: "Paquistão", ES: "Espanha", MX: "México",
    AR: "Argentina", CO: "Colômbia", CL: "Chile", PE: "Peru", VE: "Venezuela",
    EC: "Equador", GT: "Guatemala", CU: "Cuba", BO: "Bolívia", DO: "República Dominicana",
    HN: "Honduras", PY: "Paraguai", SV: "El Salvador", NI: "Nicarágua", CR: "Costa Rica",
    PA: "Panamá", UY: "Uruguai", PR: "Porto Rico", DE: "Alemanha", AT: "Áustria",
    CH: "Suíça", LI: "Liechtenstein", FR: "França", BE: "Bélgica", LU: "Luxemburgo",
    MC: "Mônaco", SN: "Senegal", CI: "Costa do Marfim", CM: "Camarões",
    CD: "Congo - Kinshasa", IT: "Itália", SM: "San Marino", VA: "Cidade do Vaticano",
    NL: "Países Baixos", SR: "Suriname", SE: "Suécia", NO: "Noruega", DK: "Dinamarca",
    FI: "Finlândia", IS: "Islândia", PL: "Polônia", CZ: "Tchéquia", SK: "Eslováquia",
    HU: "Hungria", RO: "Romênia", BG: "Bulgária", GR: "Grécia", RU: "Rússia", UA: "Ucrânia",
    BY: "Bielorrússia", KZ: "Cazaquistão", RS: "Sérvia", HR: "Croácia", SI: "Eslovênia",
    JP: "Japão", KR: "Coreia do Sul", CN: "China", TW: "Taiwan",
    HK: "Hong Kong, RAE da China", TH: "Tailândia", VN: "Vietnã", ID: "Indonésia",
    IN: "Índia", BD: "Bangladesh", LK: "Sri Lanka", NP: "Nepal", MM: "Mianmar (Birmânia)",
    KH: "Camboja", MA: "Marrocos", DZ: "Argélia", TN: "Tunísia", SA: "Arábia Saudita",
    AE: "Emirados Árabes Unidos", EG: "Egito", IQ: "Iraque", JO: "Jordânia", KW: "Kuwait",
    QA: "Catar", OM: "Omã", LB: "Líbano", LY: "Líbia", YE: "Iêmen", BH: "Barein",
    SY: "Síria", IL: "Israel", TR: "Turquia", IR: "Irã", AD: "Andorra", AF: "Afeganistão",
    AG: "Antígua e Barbuda", AI: "Anguila", AL: "Albânia", AM: "Armênia",
    AS: "Samoa Americana", AW: "Aruba", AX: "Ilhas Aland", AZ: "Azerbaijão",
    BA: "Bósnia e Herzegovina", BB: "Barbados", BF: "Burquina Faso", BI: "Burundi",
    BJ: "Benin", BL: "São Bartolomeu", BM: "Bermudas", BN: "Brunei",
    BQ: "Países Baixos Caribenhos", BS: "Bahamas", BT: "Butão", BW: "Botsuana",
    BZ: "Belize", CC: "Ilhas Cocos (Keeling)", CF: "República Centro-Africana",
    CG: "República do Congo", CK: "Ilhas Cook", CW: "Curaçao", CX: "Ilha Christmas",
    CY: "Chipre", DJ: "Djibuti", DM: "Dominica", EE: "Estônia", EH: "Saara Ocidental",
    ER: "Eritreia", ET: "Etiópia", FJ: "Fiji", FK: "Ilhas Malvinas", FM: "Micronésia",
    FO: "Ilhas Faroé", GA: "Gabão", GD: "Granada", GE: "Geórgia", GF: "Guiana Francesa",
    GG: "Guernsey", GI: "Gibraltar", GL: "Groenlândia", GM: "Gâmbia", GN: "Guiné",
    GP: "Guadalupe", GQ: "Guiné Equatorial", GU: "Guam", GY: "Guiana", HT: "Haiti",
    IM: "Ilha de Man", JE: "Jersey", JM: "Jamaica", KG: "Quirguistão", KI: "Quiribati",
    KM: "Comores", KN: "São Cristóvão e Névis", KP: "Coreia do Norte", KY: "Ilhas Cayman",
    LA: "Laos", LC: "Santa Lúcia", LR: "Libéria", LS: "Lesoto", LT: "Lituânia",
    LV: "Letônia", MD: "Moldávia", ME: "Montenegro", MF: "São Martinho", MG: "Madagascar",
    MH: "Ilhas Marshall", MK: "Macedônia do Norte", ML: "Mali", MN: "Mongólia",
    MO: "Macau, RAE da China", MP: "Ilhas Marianas do Norte", MQ: "Martinica",
    MR: "Mauritânia", MS: "Montserrat", MT: "Malta", MU: "Maurício", MV: "Maldivas",
    MW: "Malaui", NA: "Namíbia", NC: "Nova Caledônia", NE: "Níger", NF: "Ilha Norfolk",
    NR: "Nauru", NU: "Niue", PF: "Polinésia Francesa", PG: "Papua-Nova Guiné",
    PM: "São Pedro e Miquelão", PN: "Ilhas Pitcairn", PS: "Territórios palestinos",
    PW: "Palau", RE: "Reunião", RW: "Ruanda", SB: "Ilhas Salomão", SC: "Seicheles",
    SD: "Sudão", SH: "Santa Helena", SJ: "Svalbard e Jan Mayen", SL: "Serra Leoa",
    SO: "Somália", SS: "Sudão do Sul", SX: "Sint Maarten", SZ: "Essuatíni",
    TC: "Ilhas Turcas e Caicos", TD: "Chade", TG: "Togo", TJ: "Tadjiquistão", TK: "Tokelau",
    TM: "Turcomenistão", TO: "Tonga", TT: "Trinidad e Tobago", TV: "Tuvalu", TZ: "Tanzânia",
    UG: "Uganda", UZ: "Uzbequistão", VC: "São Vicente e Granadinas",
    VG: "Ilhas Virgens Britânicas", VI: "Ilhas Virgens Americanas", VU: "Vanuatu",
    WF: "Wallis e Futuna", WS: "Samoa", XK: "Kosovo", YT: "Mayotte", ZM: "Zâmbia",
    ZW: "Zimbábue",
  },

  "en-US": {
    BR: "Brazil", PT: "Portugal", AO: "Angola", MZ: "Mozambique", CV: "Cape Verde",
    GW: "Guinea-Bissau", ST: "São Tomé & Príncipe", TL: "Timor-Leste", US: "United States",
    GB: "United Kingdom", AU: "Australia", CA: "Canada", NZ: "New Zealand", IE: "Ireland",
    ZA: "South Africa", NG: "Nigeria", KE: "Kenya", GH: "Ghana", PH: "Philippines",
    SG: "Singapore", MY: "Malaysia", PK: "Pakistan", ES: "Spain", MX: "Mexico",
    AR: "Argentina", CO: "Colombia", CL: "Chile", PE: "Peru", VE: "Venezuela",
    EC: "Ecuador", GT: "Guatemala", CU: "Cuba", BO: "Bolivia", DO: "Dominican Republic",
    HN: "Honduras", PY: "Paraguay", SV: "El Salvador", NI: "Nicaragua", CR: "Costa Rica",
    PA: "Panama", UY: "Uruguay", PR: "Puerto Rico", DE: "Germany", AT: "Austria",
    CH: "Switzerland", LI: "Liechtenstein", FR: "France", BE: "Belgium", LU: "Luxembourg",
    MC: "Monaco", SN: "Senegal", CI: "Côte d’Ivoire", CM: "Cameroon",
    CD: "Congo - Kinshasa", IT: "Italy", SM: "San Marino", VA: "Vatican City",
    NL: "Netherlands", SR: "Suriname", SE: "Sweden", NO: "Norway", DK: "Denmark",
    FI: "Finland", IS: "Iceland", PL: "Poland", CZ: "Czechia", SK: "Slovakia",
    HU: "Hungary", RO: "Romania", BG: "Bulgaria", GR: "Greece", RU: "Russia", UA: "Ukraine",
    BY: "Belarus", KZ: "Kazakhstan", RS: "Serbia", HR: "Croatia", SI: "Slovenia",
    JP: "Japan", KR: "South Korea", CN: "China", TW: "Taiwan", HK: "Hong Kong SAR China",
    TH: "Thailand", VN: "Vietnam", ID: "Indonesia", IN: "India", BD: "Bangladesh",
    LK: "Sri Lanka", NP: "Nepal", MM: "Myanmar (Burma)", KH: "Cambodia", MA: "Morocco",
    DZ: "Algeria", TN: "Tunisia", SA: "Saudi Arabia", AE: "United Arab Emirates",
    EG: "Egypt", IQ: "Iraq", JO: "Jordan", KW: "Kuwait", QA: "Qatar", OM: "Oman",
    LB: "Lebanon", LY: "Libya", YE: "Yemen", BH: "Bahrain", SY: "Syria", IL: "Israel",
    TR: "Türkiye", IR: "Iran", AD: "Andorra", AF: "Afghanistan", AG: "Antigua & Barbuda",
    AI: "Anguilla", AL: "Albania", AM: "Armenia", AS: "American Samoa", AW: "Aruba",
    AX: "Åland Islands", AZ: "Azerbaijan", BA: "Bosnia & Herzegovina", BB: "Barbados",
    BF: "Burkina Faso", BI: "Burundi", BJ: "Benin", BL: "St. Barthélemy", BM: "Bermuda",
    BN: "Brunei", BQ: "Caribbean Netherlands", BS: "Bahamas", BT: "Bhutan", BW: "Botswana",
    BZ: "Belize", CC: "Cocos (Keeling) Islands", CF: "Central African Republic",
    CG: "Congo - Brazzaville", CK: "Cook Islands", CW: "Curaçao", CX: "Christmas Island",
    CY: "Cyprus", DJ: "Djibouti", DM: "Dominica", EE: "Estonia", EH: "Western Sahara",
    ER: "Eritrea", ET: "Ethiopia", FJ: "Fiji", FK: "Falkland Islands", FM: "Micronesia",
    FO: "Faroe Islands", GA: "Gabon", GD: "Grenada", GE: "Georgia", GF: "French Guiana",
    GG: "Guernsey", GI: "Gibraltar", GL: "Greenland", GM: "Gambia", GN: "Guinea",
    GP: "Guadeloupe", GQ: "Equatorial Guinea", GU: "Guam", GY: "Guyana", HT: "Haiti",
    IM: "Isle of Man", JE: "Jersey", JM: "Jamaica", KG: "Kyrgyzstan", KI: "Kiribati",
    KM: "Comoros", KN: "St. Kitts & Nevis", KP: "North Korea", KY: "Cayman Islands",
    LA: "Laos", LC: "St. Lucia", LR: "Liberia", LS: "Lesotho", LT: "Lithuania",
    LV: "Latvia", MD: "Moldova", ME: "Montenegro", MF: "St. Martin", MG: "Madagascar",
    MH: "Marshall Islands", MK: "North Macedonia", ML: "Mali", MN: "Mongolia",
    MO: "Macao SAR China", MP: "Northern Mariana Islands", MQ: "Martinique",
    MR: "Mauritania", MS: "Montserrat", MT: "Malta", MU: "Mauritius", MV: "Maldives",
    MW: "Malawi", NA: "Namibia", NC: "New Caledonia", NE: "Niger", NF: "Norfolk Island",
    NR: "Nauru", NU: "Niue", PF: "French Polynesia", PG: "Papua New Guinea",
    PM: "St. Pierre & Miquelon", PN: "Pitcairn Islands", PS: "Palestinian Territories",
    PW: "Palau", RE: "Réunion", RW: "Rwanda", SB: "Solomon Islands", SC: "Seychelles",
    SD: "Sudan", SH: "St. Helena", SJ: "Svalbard & Jan Mayen", SL: "Sierra Leone",
    SO: "Somalia", SS: "South Sudan", SX: "Sint Maarten", SZ: "Eswatini",
    TC: "Turks & Caicos Islands", TD: "Chad", TG: "Togo", TJ: "Tajikistan", TK: "Tokelau",
    TM: "Turkmenistan", TO: "Tonga", TT: "Trinidad & Tobago", TV: "Tuvalu", TZ: "Tanzania",
    UG: "Uganda", UZ: "Uzbekistan", VC: "St. Vincent & Grenadines",
    VG: "British Virgin Islands", VI: "U.S. Virgin Islands", VU: "Vanuatu",
    WF: "Wallis & Futuna", WS: "Samoa", XK: "Kosovo", YT: "Mayotte", ZM: "Zambia",
    ZW: "Zimbabwe",
  },

  "es-419": {
    BR: "Brasil", PT: "Portugal", AO: "Angola", MZ: "Mozambique", CV: "Cabo Verde",
    GW: "Guinea-Bisáu", ST: "Santo Tomé y Príncipe", TL: "Timor Oriental",
    US: "Estados Unidos", GB: "Reino Unido", AU: "Australia", CA: "Canadá",
    NZ: "Nueva Zelanda", IE: "Irlanda", ZA: "Sudáfrica", NG: "Nigeria", KE: "Kenia",
    GH: "Ghana", PH: "Filipinas", SG: "Singapur", MY: "Malasia", PK: "Pakistán",
    ES: "España", MX: "México", AR: "Argentina", CO: "Colombia", CL: "Chile", PE: "Perú",
    VE: "Venezuela", EC: "Ecuador", GT: "Guatemala", CU: "Cuba", BO: "Bolivia",
    DO: "República Dominicana", HN: "Honduras", PY: "Paraguay", SV: "El Salvador",
    NI: "Nicaragua", CR: "Costa Rica", PA: "Panamá", UY: "Uruguay", PR: "Puerto Rico",
    DE: "Alemania", AT: "Austria", CH: "Suiza", LI: "Liechtenstein", FR: "Francia",
    BE: "Bélgica", LU: "Luxemburgo", MC: "Mónaco", SN: "Senegal", CI: "Costa de Marfil",
    CM: "Camerún", CD: "República Democrática del Congo", IT: "Italia", SM: "San Marino",
    VA: "Ciudad del Vaticano", NL: "Países Bajos", SR: "Surinam", SE: "Suecia",
    NO: "Noruega", DK: "Dinamarca", FI: "Finlandia", IS: "Islandia", PL: "Polonia",
    CZ: "Chequia", SK: "Eslovaquia", HU: "Hungría", RO: "Rumania", BG: "Bulgaria",
    GR: "Grecia", RU: "Rusia", UA: "Ucrania", BY: "Bielorrusia", KZ: "Kazajistán",
    RS: "Serbia", HR: "Croacia", SI: "Eslovenia", JP: "Japón", KR: "Corea del Sur",
    CN: "China", TW: "Taiwán", HK: "RAE de Hong Kong (China)", TH: "Tailandia",
    VN: "Vietnam", ID: "Indonesia", IN: "India", BD: "Bangladés", LK: "Sri Lanka",
    NP: "Nepal", MM: "Myanmar (Birmania)", KH: "Camboya", MA: "Marruecos", DZ: "Argelia",
    TN: "Túnez", SA: "Arabia Saudita", AE: "Emiratos Árabes Unidos", EG: "Egipto",
    IQ: "Irak", JO: "Jordania", KW: "Kuwait", QA: "Catar", OM: "Omán", LB: "Líbano",
    LY: "Libia", YE: "Yemen", BH: "Baréin", SY: "Siria", IL: "Israel", TR: "Turquía",
    IR: "Irán", AD: "Andorra", AF: "Afganistán", AG: "Antigua y Barbuda", AI: "Anguila",
    AL: "Albania", AM: "Armenia", AS: "Samoa Americana", AW: "Aruba", AX: "Islas Åland",
    AZ: "Azerbaiyán", BA: "Bosnia-Herzegovina", BB: "Barbados", BF: "Burkina Faso",
    BI: "Burundi", BJ: "Benín", BL: "San Bartolomé", BM: "Bermudas", BN: "Brunéi",
    BQ: "Caribe neerlandés", BS: "Bahamas", BT: "Bután", BW: "Botsuana", BZ: "Belice",
    CC: "Islas Cocos", CF: "República Centroafricana", CG: "República del Congo",
    CK: "Islas Cook", CW: "Curazao", CX: "Isla de Navidad", CY: "Chipre", DJ: "Yibuti",
    DM: "Dominica", EE: "Estonia", EH: "Sáhara Occidental", ER: "Eritrea", ET: "Etiopía",
    FJ: "Fiyi", FK: "Islas Malvinas", FM: "Micronesia", FO: "Islas Feroe", GA: "Gabón",
    GD: "Granada", GE: "Georgia", GF: "Guayana Francesa", GG: "Guernesey", GI: "Gibraltar",
    GL: "Groenlandia", GM: "Gambia", GN: "Guinea", GP: "Guadalupe", GQ: "Guinea Ecuatorial",
    GU: "Guam", GY: "Guyana", HT: "Haití", IM: "Isla de Man", JE: "Jersey", JM: "Jamaica",
    KG: "Kirguistán", KI: "Kiribati", KM: "Comoras", KN: "San Cristóbal y Nieves",
    KP: "Corea del Norte", KY: "Islas Caimán", LA: "Laos", LC: "Santa Lucía", LR: "Liberia",
    LS: "Lesoto", LT: "Lituania", LV: "Letonia", MD: "Moldavia", ME: "Montenegro",
    MF: "San Martín", MG: "Madagascar", MH: "Islas Marshall", MK: "Macedonia del Norte",
    ML: "Mali", MN: "Mongolia", MO: "RAE de Macao (China)", MP: "Islas Marianas del Norte",
    MQ: "Martinica", MR: "Mauritania", MS: "Montserrat", MT: "Malta", MU: "Mauricio",
    MV: "Maldivas", MW: "Malaui", NA: "Namibia", NC: "Nueva Caledonia", NE: "Níger",
    NF: "Isla Norfolk", NR: "Nauru", NU: "Niue", PF: "Polinesia Francesa",
    PG: "Papúa Nueva Guinea", PM: "San Pedro y Miquelón", PN: "Islas Pitcairn",
    PS: "Territorios Palestinos", PW: "Palaos", RE: "Reunión", RW: "Ruanda",
    SB: "Islas Salomón", SC: "Seychelles", SD: "Sudán", SH: "Santa Elena",
    SJ: "Svalbard y Jan Mayen", SL: "Sierra Leona", SO: "Somalia", SS: "Sudán del Sur",
    SX: "Sint Maarten", SZ: "Esuatini", TC: "Islas Turcas y Caicos", TD: "Chad", TG: "Togo",
    TJ: "Tayikistán", TK: "Tokelau", TM: "Turkmenistán", TO: "Tonga",
    TT: "Trinidad y Tobago", TV: "Tuvalu", TZ: "Tanzania", UG: "Uganda", UZ: "Uzbekistán",
    VC: "San Vicente y las Granadinas", VG: "Islas Vírgenes Británicas",
    VI: "Islas Vírgenes de EE. UU.", VU: "Vanuatu", WF: "Wallis y Futuna", WS: "Samoa",
    XK: "Kosovo", YT: "Mayotte", ZM: "Zambia", ZW: "Zimbabue",
  },

  "fr-FR": {
    BR: "Brésil", PT: "Portugal", AO: "Angola", MZ: "Mozambique", CV: "Cap-Vert",
    GW: "Guinée-Bissau", ST: "Sao Tomé-et-Principe", TL: "Timor oriental", US: "États-Unis",
    GB: "Royaume-Uni", AU: "Australie", CA: "Canada", NZ: "Nouvelle-Zélande", IE: "Irlande",
    ZA: "Afrique du Sud", NG: "Nigeria", KE: "Kenya", GH: "Ghana", PH: "Philippines",
    SG: "Singapour", MY: "Malaisie", PK: "Pakistan", ES: "Espagne", MX: "Mexique",
    AR: "Argentine", CO: "Colombie", CL: "Chili", PE: "Pérou", VE: "Venezuela",
    EC: "Équateur", GT: "Guatemala", CU: "Cuba", BO: "Bolivie",
    DO: "République dominicaine", HN: "Honduras", PY: "Paraguay", SV: "Salvador",
    NI: "Nicaragua", CR: "Costa Rica", PA: "Panama", UY: "Uruguay", PR: "Porto Rico",
    DE: "Allemagne", AT: "Autriche", CH: "Suisse", LI: "Liechtenstein", FR: "France",
    BE: "Belgique", LU: "Luxembourg", MC: "Monaco", SN: "Sénégal", CI: "Côte d’Ivoire",
    CM: "Cameroun", CD: "Congo-Kinshasa", IT: "Italie", SM: "Saint-Marin",
    VA: "État de la Cité du Vatican", NL: "Pays-Bas", SR: "Suriname", SE: "Suède",
    NO: "Norvège", DK: "Danemark", FI: "Finlande", IS: "Islande", PL: "Pologne",
    CZ: "Tchéquie", SK: "Slovaquie", HU: "Hongrie", RO: "Roumanie", BG: "Bulgarie",
    GR: "Grèce", RU: "Russie", UA: "Ukraine", BY: "Biélorussie", KZ: "Kazakhstan",
    RS: "Serbie", HR: "Croatie", SI: "Slovénie", JP: "Japon", KR: "Corée du Sud",
    CN: "Chine", TW: "Taïwan", HK: "R.A.S. chinoise de Hong Kong", TH: "Thaïlande",
    VN: "Viêt Nam", ID: "Indonésie", IN: "Inde", BD: "Bangladesh", LK: "Sri Lanka",
    NP: "Népal", MM: "Myanmar (Birmanie)", KH: "Cambodge", MA: "Maroc", DZ: "Algérie",
    TN: "Tunisie", SA: "Arabie saoudite", AE: "Émirats arabes unis", EG: "Égypte",
    IQ: "Irak", JO: "Jordanie", KW: "Koweït", QA: "Qatar", OM: "Oman", LB: "Liban",
    LY: "Libye", YE: "Yémen", BH: "Bahreïn", SY: "Syrie", IL: "Israël", TR: "Turquie",
    IR: "Iran", AD: "Andorre", AF: "Afghanistan", AG: "Antigua-et-Barbuda", AI: "Anguilla",
    AL: "Albanie", AM: "Arménie", AS: "Samoa américaines", AW: "Aruba", AX: "Îles Åland",
    AZ: "Azerbaïdjan", BA: "Bosnie-Herzégovine", BB: "Barbade", BF: "Burkina Faso",
    BI: "Burundi", BJ: "Bénin", BL: "Saint-Barthélemy", BM: "Bermudes", BN: "Brunei",
    BQ: "Pays-Bas caribéens", BS: "Bahamas", BT: "Bhoutan", BW: "Botswana", BZ: "Belize",
    CC: "Îles Cocos", CF: "République centrafricaine", CG: "Congo-Brazzaville",
    CK: "Îles Cook", CW: "Curaçao", CX: "Île Christmas", CY: "Chypre", DJ: "Djibouti",
    DM: "Dominique", EE: "Estonie", EH: "Sahara occidental", ER: "Érythrée", ET: "Éthiopie",
    FJ: "Fidji", FK: "Îles Malouines", FM: "Micronésie", FO: "Îles Féroé", GA: "Gabon",
    GD: "Grenade", GE: "Géorgie", GF: "Guyane française", GG: "Guernesey", GI: "Gibraltar",
    GL: "Groenland", GM: "Gambie", GN: "Guinée", GP: "Guadeloupe", GQ: "Guinée équatoriale",
    GU: "Guam", GY: "Guyana", HT: "Haïti", IM: "Île de Man", JE: "Jersey", JM: "Jamaïque",
    KG: "Kirghizstan", KI: "Kiribati", KM: "Comores", KN: "Saint-Christophe-et-Niévès",
    KP: "Corée du Nord", KY: "Îles Caïmans", LA: "Laos", LC: "Sainte-Lucie", LR: "Liberia",
    LS: "Lesotho", LT: "Lituanie", LV: "Lettonie", MD: "Moldavie", ME: "Monténégro",
    MF: "Saint-Martin", MG: "Madagascar", MH: "Îles Marshall", MK: "Macédoine du Nord",
    ML: "Mali", MN: "Mongolie", MO: "R.A.S. chinoise de Macao",
    MP: "Îles Mariannes du Nord", MQ: "Martinique", MR: "Mauritanie", MS: "Montserrat",
    MT: "Malte", MU: "Maurice", MV: "Maldives", MW: "Malawi", NA: "Namibie",
    NC: "Nouvelle-Calédonie", NE: "Niger", NF: "Île Norfolk", NR: "Nauru", NU: "Niue",
    PF: "Polynésie française", PG: "Papouasie-Nouvelle-Guinée",
    PM: "Saint-Pierre-et-Miquelon", PN: "Îles Pitcairn", PS: "Territoires palestiniens",
    PW: "Palaos", RE: "La Réunion", RW: "Rwanda", SB: "Îles Salomon", SC: "Seychelles",
    SD: "Soudan", SH: "Sainte-Hélène", SJ: "Svalbard et Jan Mayen", SL: "Sierra Leone",
    SO: "Somalie", SS: "Soudan du Sud", SX: "Saint-Martin (partie néerlandaise)",
    SZ: "Eswatini", TC: "Îles Turques-et-Caïques", TD: "Tchad", TG: "Togo",
    TJ: "Tadjikistan", TK: "Tokelau", TM: "Turkménistan", TO: "Tonga",
    TT: "Trinité-et-Tobago", TV: "Tuvalu", TZ: "Tanzanie", UG: "Ouganda", UZ: "Ouzbékistan",
    VC: "Saint-Vincent-et-les Grenadines", VG: "Îles Vierges britanniques",
    VI: "Îles Vierges des États-Unis", VU: "Vanuatu", WF: "Wallis-et-Futuna", WS: "Samoa",
    XK: "Kosovo", YT: "Mayotte", ZM: "Zambie", ZW: "Zimbabwe",
  },

  "de-DE": {
    BR: "Brasilien", PT: "Portugal", AO: "Angola", MZ: "Mosambik", CV: "Cabo Verde",
    GW: "Guinea-Bissau", ST: "São Tomé und Príncipe", TL: "Timor-Leste",
    US: "Vereinigte Staaten", GB: "Vereinigtes Königreich", AU: "Australien", CA: "Kanada",
    NZ: "Neuseeland", IE: "Irland", ZA: "Südafrika", NG: "Nigeria", KE: "Kenia",
    GH: "Ghana", PH: "Philippinen", SG: "Singapur", MY: "Malaysia", PK: "Pakistan",
    ES: "Spanien", MX: "Mexiko", AR: "Argentinien", CO: "Kolumbien", CL: "Chile",
    PE: "Peru", VE: "Venezuela", EC: "Ecuador", GT: "Guatemala", CU: "Kuba", BO: "Bolivien",
    DO: "Dominikanische Republik", HN: "Honduras", PY: "Paraguay", SV: "El Salvador",
    NI: "Nicaragua", CR: "Costa Rica", PA: "Panama", UY: "Uruguay", PR: "Puerto Rico",
    DE: "Deutschland", AT: "Österreich", CH: "Schweiz", LI: "Liechtenstein",
    FR: "Frankreich", BE: "Belgien", LU: "Luxemburg", MC: "Monaco", SN: "Senegal",
    CI: "Côte d’Ivoire", CM: "Kamerun", CD: "Kongo-Kinshasa", IT: "Italien",
    SM: "San Marino", VA: "Vatikanstadt", NL: "Niederlande", SR: "Suriname", SE: "Schweden",
    NO: "Norwegen", DK: "Dänemark", FI: "Finnland", IS: "Island", PL: "Polen",
    CZ: "Tschechien", SK: "Slowakei", HU: "Ungarn", RO: "Rumänien", BG: "Bulgarien",
    GR: "Griechenland", RU: "Russland", UA: "Ukraine", BY: "Belarus", KZ: "Kasachstan",
    RS: "Serbien", HR: "Kroatien", SI: "Slowenien", JP: "Japan", KR: "Südkorea",
    CN: "China", TW: "Taiwan", HK: "Sonderverwaltungsregion Hongkong", TH: "Thailand",
    VN: "Vietnam", ID: "Indonesien", IN: "Indien", BD: "Bangladesch", LK: "Sri Lanka",
    NP: "Nepal", MM: "Myanmar", KH: "Kambodscha", MA: "Marokko", DZ: "Algerien",
    TN: "Tunesien", SA: "Saudi-Arabien", AE: "Vereinigte Arabische Emirate", EG: "Ägypten",
    IQ: "Irak", JO: "Jordanien", KW: "Kuwait", QA: "Katar", OM: "Oman", LB: "Libanon",
    LY: "Libyen", YE: "Jemen", BH: "Bahrain", SY: "Syrien", IL: "Israel", TR: "Türkei",
    IR: "Iran", AD: "Andorra", AF: "Afghanistan", AG: "Antigua und Barbuda", AI: "Anguilla",
    AL: "Albanien", AM: "Armenien", AS: "Amerikanisch-Samoa", AW: "Aruba",
    AX: "Ålandinseln", AZ: "Aserbaidschan", BA: "Bosnien und Herzegowina", BB: "Barbados",
    BF: "Burkina Faso", BI: "Burundi", BJ: "Benin", BL: "St. Barthélemy", BM: "Bermuda",
    BN: "Brunei Darussalam", BQ: "Karibische Niederlande", BS: "Bahamas", BT: "Bhutan",
    BW: "Botsuana", BZ: "Belize", CC: "Kokosinseln", CF: "Zentralafrikanische Republik",
    CG: "Kongo-Brazzaville", CK: "Cookinseln", CW: "Curaçao", CX: "Weihnachtsinsel",
    CY: "Zypern", DJ: "Dschibuti", DM: "Dominica", EE: "Estland", EH: "Westsahara",
    ER: "Eritrea", ET: "Äthiopien", FJ: "Fidschi", FK: "Falklandinseln", FM: "Mikronesien",
    FO: "Färöer", GA: "Gabun", GD: "Grenada", GE: "Georgien", GF: "Französisch-Guayana",
    GG: "Guernsey", GI: "Gibraltar", GL: "Grönland", GM: "Gambia", GN: "Guinea",
    GP: "Guadeloupe", GQ: "Äquatorialguinea", GU: "Guam", GY: "Guyana", HT: "Haiti",
    IM: "Isle of Man", JE: "Jersey", JM: "Jamaika", KG: "Kirgisistan", KI: "Kiribati",
    KM: "Komoren", KN: "St. Kitts und Nevis", KP: "Nordkorea", KY: "Kaimaninseln",
    LA: "Laos", LC: "St. Lucia", LR: "Liberia", LS: "Lesotho", LT: "Litauen",
    LV: "Lettland", MD: "Republik Moldau", ME: "Montenegro", MF: "St. Martin",
    MG: "Madagaskar", MH: "Marshallinseln", MK: "Nordmazedonien", ML: "Mali",
    MN: "Mongolei", MO: "Sonderverwaltungsregion Macau", MP: "Nördliche Marianen",
    MQ: "Martinique", MR: "Mauretanien", MS: "Montserrat", MT: "Malta", MU: "Mauritius",
    MV: "Malediven", MW: "Malawi", NA: "Namibia", NC: "Neukaledonien", NE: "Niger",
    NF: "Norfolkinsel", NR: "Nauru", NU: "Niue", PF: "Französisch-Polynesien",
    PG: "Papua-Neuguinea", PM: "St. Pierre und Miquelon", PN: "Pitcairninseln",
    PS: "Palästinensische Autonomiegebiete", PW: "Palau", RE: "Réunion", RW: "Ruanda",
    SB: "Salomonen", SC: "Seychellen", SD: "Sudan", SH: "St. Helena",
    SJ: "Spitzbergen und Jan Mayen", SL: "Sierra Leone", SO: "Somalia", SS: "Südsudan",
    SX: "Sint Maarten", SZ: "Eswatini", TC: "Turks- und Caicosinseln", TD: "Tschad",
    TG: "Togo", TJ: "Tadschikistan", TK: "Tokelau", TM: "Turkmenistan", TO: "Tonga",
    TT: "Trinidad und Tobago", TV: "Tuvalu", TZ: "Tansania", UG: "Uganda", UZ: "Usbekistan",
    VC: "St. Vincent und die Grenadinen", VG: "Britische Jungferninseln",
    VI: "Amerikanische Jungferninseln", VU: "Vanuatu", WF: "Wallis und Futuna", WS: "Samoa",
    XK: "Kosovo", YT: "Mayotte", ZM: "Sambia", ZW: "Simbabwe",
  },
};
