/* As comidas que a lista ganhou quando deixou de ser só brasileira.

   Cada uma diz de onde vêm os números:
     usda    o número NDB da SR Legacy (USDA, abril de 2018, domínio
             público) — a mesma linha que o gerador lê;
     rotulo  valores de rótulo de produto comum no mercado, quando a
             SR Legacy não analisou o alimento (skyr, quark, bebida de
             aveia, presunto cru). Mesma regra dos poucos itens de rótulo
             da lista brasileira: a tela diz de onde veio.

   rend     o rendimento de cozimento, quando a SR Legacy só traz o
            alimento cru: os valores são divididos por ele.

   gUn é o peso de UMA medida caseira, e quase sempre saiu das porções
   da própria SR Legacy ("1 medium bagel = 105 g"); onde ela não traz
   porção, é medida de cozinha, como na lista brasileira.

   `contem` é o julgamento de restrição (ver logic/restricoes) quando o
   corredor não diz sozinho: ave em "Carnes e aves", bebida vegetal em
   "Leite e queijos", ovo e leite num doce.

   nomes: [português, inglês, espanhol, francês, alemão, italiano] —
   traduções minhas, para a revisão nativa (PENDENCIAS, item 20). */
export const NOVAS = [
  /* --- carnes e aves ------------------------------------------------ */
  { id: 'bacon', usda: 10862, gUn: 11, qtd: 2, un: 'fatia', onde: 'Carnes e aves',
    nomes: ['Bacon frito', 'Fried bacon', 'Tocino frito', 'Bacon grillé', 'Gebratener Speck', 'Pancetta croccante'] },
  { id: 'salsicha', usda: 7950, gUn: 50, qtd: 1, un: 'unidade', onde: 'Carnes e aves', contem: ['carne', 'ave'], busca: 'hot dog cachorro quente frankfurt wurstel',
    nomes: ['Salsicha', 'Frankfurter (hot dog)', 'Salchicha', 'Saucisse de Francfort', 'Wiener Würstchen', 'Würstel'] },
  { id: 'bratwurst', usda: 7013, gUn: 85, qtd: 1, un: 'unidade', onde: 'Carnes e aves',
    nomes: ['Bratwurst (salsichão alemão)', 'Bratwurst', 'Salchicha bratwurst', 'Bratwurst (saucisse allemande)', 'Bratwurst', 'Bratwurst (salsiccia tedesca)'] },
  /* A SR Legacy só traz o chorizo cru, e ninguém come chorizo cru: o
     rendimento de cozimento de 70% (perda de água e gordura na frigideira)
     leva o número ao que vai para o prato. É estimativa minha. */
  { id: 'chorizo', usda: 7019, rend: 0.7, gUn: 60, qtd: 1, un: 'unidade', onde: 'Carnes e aves',
    nomes: ['Chorizo', 'Chorizo', 'Chorizo', 'Chorizo', 'Chorizo', 'Chorizo'] },
  { id: 'presunto-cru', rotulo: { p: 25.9, kcal: 250, carb: 0.3, gord: 18, fibra: 0 }, gUn: 15, qtd: 2, un: 'fatia', onde: 'Carnes e aves', busca: 'parma serrano cru curado',
    nomes: ['Presunto cru (parma, serrano)', 'Prosciutto (cured ham)', 'Jamón serrano', 'Jambon cru', 'Rohschinken', 'Prosciutto crudo'] },
  { id: 'salame', usda: 7072, gUn: 10, qtd: 3, un: 'fatia', onde: 'Carnes e aves',
    nomes: ['Salame', 'Salami', 'Salami', 'Salami', 'Salami', 'Salame'] },
  { id: 'cordeiro', usda: 17018, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves',
    nomes: ['Cordeiro assado', 'Roast lamb', 'Cordero asado', 'Gigot d’agneau rôti', 'Lammbraten', 'Agnello arrosto'] },
  { id: 'costeleta-porco', usda: 10038, gUn: 150, qtd: 1, un: 'unidade', onde: 'Carnes e aves', busca: 'bisteca suina',
    nomes: ['Costeleta de porco grelhada', 'Grilled pork chop', 'Chuleta de cerdo a la plancha', 'Côte de porc grillée', 'Gegrilltes Schweinekotelett', 'Braciola di maiale alla griglia'] },
  { id: 'pato', usda: 5142, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves', contem: ['ave'],
    nomes: ['Pato assado', 'Roast duck', 'Pato asado', 'Canard rôti', 'Entenbraten', 'Anatra arrosto'] },
  { id: 'peito-peru-fatiado', usda: 42128, gUn: 15, qtd: 2, un: 'fatia', onde: 'Carnes e aves', contem: ['ave'], busca: 'blanquet frios',
    nomes: ['Peito de peru fatiado', 'Sliced turkey breast', 'Pechuga de pavo en rebanadas', 'Blanc de dinde', 'Putenbrust-Aufschnitt', 'Fesa di tacchino a fette'] },
  { id: 'alcatra-grelhada', usda: 13491, gUn: 150, qtd: 1, un: 'bife', onde: 'Carnes e aves', busca: 'steak bife magro',
    nomes: ['Bife magro grelhado (alcatra)', 'Grilled lean steak (top sirloin)', 'Bistec magro de res a la parrilla', 'Pavé de bœuf grillé', 'Gegrilltes Hüftsteak', 'Bistecca magra di manzo alla griglia (scamone)'] },
  { id: 'pernil-magro', usda: 10011, gUn: 100, qtd: 1, un: 'fatia', onde: 'Carnes e aves',
    nomes: ['Pernil de porco magro assado', 'Lean roast pork leg', 'Pierna de cerdo magra asada', 'Rôti de porc maigre', 'Magerer Schweinebraten', 'Arrosto di maiale magro'] },

  /* --- peixes e frutos do mar --------------------------------------- */
  { id: 'atum-fresco', usda: 15221, gUn: 120, qtd: 1, un: 'posta', onde: 'Peixes e frutos do mar',
    nomes: ['Atum fresco grelhado', 'Grilled fresh tuna', 'Atún fresco a la plancha', 'Thon frais grillé', 'Gegrillter frischer Thunfisch', 'Tonno fresco alla griglia'] },
  { id: 'bacalhau-fresco', usda: 15016, gUn: 150, qtd: 1, un: 'filé', onde: 'Peixes e frutos do mar', busca: 'cod',
    nomes: ['Bacalhau fresco assado', 'Baked cod', 'Bacalao fresco al horno', 'Cabillaud au four', 'Kabeljau aus dem Ofen', 'Merluzzo al forno'] },
  { id: 'tilapia', usda: 15262, gUn: 110, qtd: 1, un: 'filé', onde: 'Peixes e frutos do mar',
    nomes: ['Tilápia grelhada', 'Grilled tilapia', 'Tilapia a la plancha', 'Tilapia grillé', 'Gegrillte Tilapia', 'Tilapia alla griglia'] },
  { id: 'truta', usda: 15241, gUn: 110, qtd: 1, un: 'filé', onde: 'Peixes e frutos do mar',
    nomes: ['Truta grelhada', 'Grilled trout', 'Trucha a la plancha', 'Truite grillée', 'Gegrillte Forelle', 'Trota alla griglia'] },
  { id: 'salmao-defumado', usda: 15077, gUn: 20, qtd: 2, un: 'fatia', onde: 'Peixes e frutos do mar',
    nomes: ['Salmão defumado', 'Smoked salmon', 'Salmón ahumado', 'Saumon fumé', 'Räucherlachs', 'Salmone affumicato'] },
  { id: 'cavala', usda: 15047, gUn: 100, qtd: 1, un: 'filé', onde: 'Peixes e frutos do mar',
    nomes: ['Cavala grelhada', 'Grilled mackerel', 'Caballa a la plancha', 'Maquereau grillé', 'Gegrillte Makrele', 'Sgombro alla griglia'] },
  { id: 'mexilhao', usda: 15165, gUn: 100, qtd: 1, un: 'porção', onde: 'Peixes e frutos do mar',
    nomes: ['Mexilhões cozidos', 'Steamed mussels', 'Mejillones al vapor', 'Moules cuites', 'Gekochte Miesmuscheln', 'Cozze al vapore'] },
  { id: 'lula', usda: 15176, gUn: 100, qtd: 1, un: 'porção', onde: 'Peixes e frutos do mar', busca: 'calamari anel',
    nomes: ['Lula frita', 'Fried calamari', 'Calamares fritos', 'Calamars frits', 'Frittierte Calamari', 'Calamari fritti'] },
  { id: 'polvo', usda: 15230, gUn: 100, qtd: 1, un: 'porção', onde: 'Peixes e frutos do mar',
    nomes: ['Polvo cozido', 'Cooked octopus', 'Pulpo cocido', 'Poulpe cuit', 'Gekochter Oktopus', 'Polpo lesso'] },
  { id: 'caranguejo', usda: 15140, gUn: 100, qtd: 1, un: 'porção', onde: 'Peixes e frutos do mar', busca: 'siri',
    nomes: ['Carne de caranguejo', 'Crab meat', 'Carne de cangrejo', 'Chair de crabe', 'Krabbenfleisch', 'Polpa di granchio'] },
  { id: 'anchova-lata', usda: 15002, gUn: 4, qtd: 3, un: 'filé', onde: 'Peixes e frutos do mar', busca: 'aliche',
    nomes: ['Anchovas em conserva', 'Canned anchovies', 'Anchoas en aceite', 'Anchois à l’huile', 'Sardellen in Öl', 'Acciughe sott’olio'] },

  /* --- ovos --------------------------------------------------------- */
  { id: 'clara-ovo', usda: 1124, gUn: 33, qtd: 2, un: 'unidade', onde: 'Ovos',
    nomes: ['Clara de ovo', 'Egg white', 'Clara de huevo', 'Blanc d’œuf', 'Eiweiß', 'Albume d’uovo'] },

  /* --- leite e queijos ---------------------------------------------- */
  { id: 'iogurte-grego', usda: 1256, gUn: 170, qtd: 1, un: 'pote', onde: 'Leite e queijos',
    nomes: ['Iogurte grego natural desnatado', 'Nonfat plain Greek yogurt', 'Yogur griego natural descremado', 'Yaourt grec nature 0 %', 'Griechischer Joghurt, mager', 'Yogurt greco bianco magro'] },
  { id: 'skyr', rotulo: { p: 11, kcal: 63, carb: 4, gord: 0.2, fibra: 0 }, gUn: 150, qtd: 1, un: 'pote', onde: 'Leite e queijos',
    nomes: ['Skyr', 'Skyr', 'Skyr', 'Skyr', 'Skyr', 'Skyr'] },
  { id: 'quark', rotulo: { p: 12, kcal: 67, carb: 4, gord: 0.2, fibra: 0 }, gUn: 30, qtd: 3, un: 'colher', onde: 'Leite e queijos', busca: 'fromage blanc magerquark',
    nomes: ['Quark (queijo fresco magro)', 'Quark', 'Quark (queso fresco batido)', 'Fromage blanc 0 %', 'Magerquark', 'Quark magro'] },
  { id: 'kefir', usda: 1289, gUn: 200, qtd: 1, un: 'copo', onde: 'Leite e queijos',
    nomes: ['Kefir', 'Kefir', 'Kéfir', 'Kéfir', 'Kefir', 'Kefir'] },
  { id: 'leite-desnatado', usda: 1085, gUn: 200, qtd: 1, un: 'copo', onde: 'Leite e queijos',
    nomes: ['Leite desnatado', 'Skim milk', 'Leche descremada', 'Lait écrémé', 'Magermilch', 'Latte scremato'] },
  { id: 'bebida-soja', usda: 16139, gUn: 200, qtd: 1, un: 'copo', onde: 'Leite e queijos', contem: [], busca: 'leite de soja vegetal',
    nomes: ['Bebida de soja', 'Soy milk', 'Bebida de soya', 'Boisson au soja', 'Sojadrink', 'Bevanda di soia'] },
  { id: 'bebida-aveia', rotulo: { p: 1, kcal: 46, carb: 6.7, gord: 1.5, fibra: 0.8 }, gUn: 200, qtd: 1, un: 'copo', onde: 'Leite e queijos', contem: [], busca: 'leite de aveia vegetal oat',
    nomes: ['Bebida de aveia', 'Oat milk', 'Bebida de avena', 'Boisson à l’avoine', 'Haferdrink', 'Bevanda d’avena'] },
  { id: 'bebida-amendoa', usda: 14091, gUn: 200, qtd: 1, un: 'copo', onde: 'Leite e queijos', contem: [], busca: 'leite de amendoas vegetal',
    nomes: ['Bebida de amêndoas sem açúcar', 'Unsweetened almond milk', 'Bebida de almendras sin azúcar', 'Boisson à l’amande sans sucre', 'Mandeldrink ungesüßt', 'Bevanda di mandorla senza zucchero'] },
  { id: 'cream-cheese', usda: 1017, gUn: 15, qtd: 2, un: 'colher', onde: 'Leite e queijos', busca: 'queijo cremoso philadelphia',
    nomes: ['Cream cheese', 'Cream cheese', 'Queso crema', 'Fromage frais à tartiner', 'Frischkäse', 'Formaggio spalmabile'] },
  { id: 'feta', usda: 1019, gUn: 30, qtd: 1, un: 'porção', onde: 'Leite e queijos',
    nomes: ['Queijo feta', 'Feta cheese', 'Queso feta', 'Feta', 'Fetakäse', 'Feta'] },
  { id: 'brie', usda: 1006, gUn: 30, qtd: 1, un: 'fatia', onde: 'Leite e queijos', busca: 'camembert',
    nomes: ['Queijo brie ou camembert', 'Brie or camembert', 'Queso brie o camembert', 'Brie ou camembert', 'Brie oder Camembert', 'Brie o camembert'] },
  { id: 'gouda', usda: 1022, gUn: 20, qtd: 1, un: 'fatia', onde: 'Leite e queijos',
    nomes: ['Queijo gouda', 'Gouda cheese', 'Queso gouda', 'Gouda', 'Gouda', 'Gouda'] },
  { id: 'emmental', usda: 1040, gUn: 20, qtd: 1, un: 'fatia', onde: 'Leite e queijos', busca: 'queijo suico swiss',
    nomes: ['Queijo emmental', 'Swiss cheese (Emmental)', 'Queso emmental', 'Emmental', 'Emmentaler', 'Emmental'] },
  { id: 'cheddar', usda: 1009, gUn: 20, qtd: 1, un: 'fatia', onde: 'Leite e queijos',
    nomes: ['Queijo cheddar', 'Cheddar cheese', 'Queso cheddar', 'Cheddar', 'Cheddar', 'Cheddar'] },
  { id: 'mussarela-fresca', usda: 1026, gUn: 60, qtd: 1, un: 'porção', onde: 'Leite e queijos', busca: 'bufala burrata bola',
    nomes: ['Mussarela fresca (de bola)', 'Fresh mozzarella', 'Mozzarella fresca', 'Mozzarella fraîche', 'Frische Mozzarella', 'Mozzarella fresca'] },
  { id: 'parmesao-lasca', usda: 1033, gUn: 20, qtd: 1, un: 'porção', onde: 'Leite e queijos', busca: 'parmigiano grana',
    nomes: ['Parmesão em lascas', 'Shaved parmesan', 'Parmesano en lascas', 'Copeaux de parmesan', 'Gehobelter Parmesan', 'Parmigiano a scaglie'] },
  { id: 'manteiga', usda: 1001, gUn: 10, qtd: 1, un: 'colher', onde: 'Leite e queijos',
    nomes: ['Manteiga', 'Butter', 'Mantequilla', 'Beurre', 'Butter', 'Burro'] },
  { id: 'creme-azedo', usda: 1056, gUn: 15, qtd: 2, un: 'colher', onde: 'Leite e queijos', busca: 'sour cream nata creme fraiche',
    nomes: ['Creme azedo', 'Sour cream', 'Crema agria', 'Crème fraîche', 'Saure Sahne', 'Panna acida'] },

  /* --- grãos e feijões ---------------------------------------------- */
  { id: 'feijao-branco', usda: 16050, gUn: 80, qtd: 1, un: 'concha', onde: 'Grãos e feijões',
    nomes: ['Feijão-branco cozido', 'Cooked white beans', 'Frijoles blancos cocidos', 'Haricots blancs cuits', 'Gekochte weiße Bohnen', 'Fagioli cannellini lessati'] },
  { id: 'feijao-vermelho', usda: 16033, gUn: 80, qtd: 1, un: 'concha', onde: 'Grãos e feijões', busca: 'kidney rajado',
    nomes: ['Feijão-vermelho cozido', 'Cooked kidney beans', 'Frijoles rojos cocidos', 'Haricots rouges cuits', 'Gekochte Kidneybohnen', 'Fagioli rossi lessati'] },
  { id: 'edamame', usda: 11212, gUn: 80, qtd: 1, un: 'porção', onde: 'Grãos e feijões',
    nomes: ['Edamame', 'Edamame', 'Edamame', 'Edamame', 'Edamame', 'Edamame'] },
  { id: 'quinoa', usda: 20137, gUn: 30, qtd: 3, un: 'colher', onde: 'Grãos e feijões',
    nomes: ['Quinoa cozida', 'Cooked quinoa', 'Quinoa cocida', 'Quinoa cuit', 'Gekochte Quinoa', 'Quinoa cotta'] },
  { id: 'homus', usda: 16158, gUn: 30, qtd: 2, un: 'colher', onde: 'Grãos e feijões', busca: 'hummus pasta de grao de bico',
    nomes: ['Homus', 'Hummus', 'Hummus', 'Houmous', 'Hummus', 'Hummus'] },
  { id: 'tempeh', usda: 16174, gUn: 60, qtd: 1, un: 'fatia', onde: 'Grãos e feijões',
    nomes: ['Tempeh', 'Tempeh', 'Tempeh', 'Tempeh', 'Tempeh', 'Tempeh'] },

  /* --- arroz, massas e pães ----------------------------------------- */
  { id: 'cuscuz-marroquino', usda: 20029, gUn: 30, qtd: 3, un: 'colher', onde: 'Arroz, massas e pães',
    nomes: ['Cuscuz marroquino', 'Couscous', 'Cuscús', 'Semoule de couscous', 'Couscous', 'Cuscus'] },
  { id: 'bulgur', usda: 20013, gUn: 30, qtd: 3, un: 'colher', onde: 'Arroz, massas e pães', busca: 'trigo para quibe',
    nomes: ['Triguilho (bulgur) cozido', 'Cooked bulgur', 'Bulgur cocido', 'Boulgour cuit', 'Gekochter Bulgur', 'Bulgur cotto'] },
  { id: 'baguete', usda: 18029, gUn: 30, qtd: 2, un: 'fatia', onde: 'Arroz, massas e pães', busca: 'pao frances fermentacao natural sourdough',
    nomes: ['Baguete ou pão de fermentação natural', 'Baguette or sourdough bread', 'Baguette o pan de masa madre', 'Baguette ou pain au levain', 'Baguette oder Sauerteigbrot', 'Baguette o pane a lievitazione naturale'] },
  { id: 'pao-centeio', usda: 18060, gUn: 30, qtd: 2, un: 'fatia', onde: 'Arroz, massas e pães',
    nomes: ['Pão de centeio', 'Rye bread', 'Pan de centeno', 'Pain de seigle', 'Roggenbrot', 'Pane di segale'] },
  { id: 'pao-integral-fatia', usda: 18075, gUn: 32, qtd: 2, un: 'fatia', onde: 'Arroz, massas e pães', busca: 'vollkornbrot',
    nomes: ['Pão integral de padaria', 'Whole wheat bread', 'Pan integral', 'Pain complet', 'Vollkornbrot', 'Pane integrale'] },
  { id: 'croissant', usda: 18239, gUn: 57, qtd: 1, un: 'unidade', onde: 'Arroz, massas e pães', contem: ['leite', 'ovo'],
    nomes: ['Croissant', 'Croissant', 'Croissant', 'Croissant', 'Croissant', 'Cornetto'] },
  { id: 'pao-sirio', usda: 18041, gUn: 60, qtd: 1, un: 'unidade', onde: 'Arroz, massas e pães', busca: 'pita arabe',
    nomes: ['Pão sírio', 'Pita bread', 'Pan árabe', 'Pain pita', 'Pita-Brot', 'Pane pita'] },
  { id: 'tortilla-trigo', usda: 18364, gUn: 48, qtd: 1, un: 'unidade', onde: 'Arroz, massas e pães', busca: 'wrap rap10',
    nomes: ['Tortilha de trigo', 'Flour tortilla', 'Tortilla de harina', 'Tortilla de blé', 'Weizentortilla', 'Tortilla di frumento'] },
  { id: 'tortilla-milho', usda: 18363, gUn: 24, qtd: 2, un: 'unidade', onde: 'Arroz, massas e pães',
    nomes: ['Tortilha de milho', 'Corn tortilla', 'Tortilla de maíz', 'Tortilla de maïs', 'Maistortilla', 'Tortilla di mais'] },
  { id: 'bagel', usda: 18001, gUn: 105, qtd: 1, un: 'unidade', onde: 'Arroz, massas e pães',
    nomes: ['Bagel', 'Bagel', 'Bagel', 'Bagel', 'Bagel', 'Bagel'] },
  { id: 'macarrao-integral', usda: 20125, gUn: 150, qtd: 1, un: 'prato', onde: 'Arroz, massas e pães',
    nomes: ['Macarrão integral cozido', 'Cooked whole wheat pasta', 'Pasta integral cocida', 'Pâtes complètes cuites', 'Gekochte Vollkornnudeln', 'Pasta integrale cotta'] },
  { id: 'macarrao-arroz', usda: 20134, gUn: 150, qtd: 1, un: 'prato', onde: 'Arroz, massas e pães', busca: 'bifum noodles',
    nomes: ['Macarrão de arroz cozido', 'Cooked rice noodles', 'Fideos de arroz cocidos', 'Nouilles de riz cuites', 'Gekochte Reisnudeln', 'Spaghetti di riso cotti'] },
  { id: 'macarrao-ovo', usda: 20310, gUn: 150, qtd: 1, un: 'prato', onde: 'Arroz, massas e pães', contem: ['ovo'], busca: 'spatzle noodles',
    nomes: ['Macarrão com ovos cozido', 'Cooked egg noodles', 'Fideos de huevo cocidos', 'Nouilles aux œufs cuites', 'Gekochte Eiernudeln', 'Pasta all’uovo cotta'] },
  { id: 'arroz-agulha', usda: 20045, gUn: 30, qtd: 4, un: 'colher', onde: 'Arroz, massas e pães', busca: 'basmati jasmim long grain',
    nomes: ['Arroz agulhinha ou basmati', 'Long-grain or basmati rice', 'Arroz de grano largo o basmati', 'Riz long ou basmati', 'Langkorn- oder Basmatireis', 'Riso a chicco lungo o basmati'] },

  /* --- verduras e legumes ------------------------------------------- */
  { id: 'abobrinha', usda: 11478, gUn: 90, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Abobrinha', 'Zucchini', 'Calabacín (zucchini)', 'Courgette', 'Zucchini', 'Zucchine'] },
  { id: 'berinjela', usda: 11210, gUn: 100, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Berinjela', 'Eggplant', 'Berenjena', 'Aubergine', 'Aubergine', 'Melanzane'] },
  { id: 'cogumelo', usda: 11263, gUn: 70, qtd: 1, un: 'porção', onde: 'Verduras e legumes', busca: 'champignon paris',
    nomes: ['Cogumelos refogados', 'Sautéed mushrooms', 'Champiñones salteados', 'Champignons sautés', 'Gebratene Champignons', 'Funghi trifolati'] },
  { id: 'aspargo', usda: 11012, gUn: 60, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Aspargos', 'Asparagus', 'Espárragos', 'Asperges', 'Spargel', 'Asparagi'] },
  { id: 'couve-bruxelas', usda: 11099, gUn: 80, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Couve-de-bruxelas', 'Brussels sprouts', 'Coles de Bruselas', 'Choux de Bruxelles', 'Rosenkohl', 'Cavolini di Bruxelles'] },
  { id: 'pure-batata', usda: 11934, gUn: 50, qtd: 2, un: 'colher', onde: 'Verduras e legumes', contem: ['leite'],
    nomes: ['Purê de batata', 'Mashed potatoes', 'Puré de papa', 'Purée de pommes de terre', 'Kartoffelpüree', 'Purè di patate'] },
  { id: 'batata-assada', usda: 11674, gUn: 170, qtd: 1, un: 'unidade', onde: 'Verduras e legumes',
    nomes: ['Batata assada com casca', 'Baked potato', 'Papa al horno', 'Pomme de terre au four', 'Ofenkartoffel', 'Patata al forno con la buccia'] },
  { id: 'azeitona', usda: 9193, gUn: 4, qtd: 5, un: 'unidade', onde: 'Verduras e legumes',
    nomes: ['Azeitona', 'Olives', 'Aceitunas', 'Olives', 'Oliven', 'Olive'] },
  { id: 'chucrute', usda: 11439, gUn: 70, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Chucrute', 'Sauerkraut', 'Chucrut', 'Choucroute', 'Sauerkraut', 'Crauti'] },
  { id: 'espinafre-cru', usda: 11457, gUn: 30, qtd: 1, un: 'porção', onde: 'Verduras e legumes', busca: 'baby spinach',
    nomes: ['Espinafre cru', 'Raw spinach', 'Espinacas crudas', 'Pousses d’épinard', 'Babyspinat', 'Spinaci crudi'] },
  { id: 'cenoura-crua', usda: 11124, gUn: 60, qtd: 1, un: 'unidade', onde: 'Verduras e legumes',
    nomes: ['Cenoura crua', 'Raw carrot', 'Zanahoria cruda', 'Carotte crue', 'Rohe Karotte', 'Carota cruda'] },

  /* --- frutas ------------------------------------------------------- */
  { id: 'pera', usda: 9412, gUn: 170, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Pera', 'Pear', 'Pera', 'Poire', 'Birne', 'Pera'] },
  { id: 'pessego', usda: 9236, gUn: 150, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Pêssego', 'Peach', 'Durazno', 'Pêche', 'Pfirsich', 'Pesca'] },
  { id: 'ameixa', usda: 9279, gUn: 66, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Ameixa', 'Plum', 'Ciruela', 'Prune', 'Pflaume', 'Susina'] },
  { id: 'kiwi', usda: 9148, gUn: 70, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Kiwi', 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi'] },
  { id: 'mirtilo', usda: 9050, gUn: 70, qtd: 1, un: 'punhado', onde: 'Frutas', busca: 'blueberry',
    nomes: ['Mirtilo', 'Blueberries', 'Arándanos', 'Myrtilles', 'Heidelbeeren', 'Mirtilli'] },
  { id: 'framboesa', usda: 9302, gUn: 60, qtd: 1, un: 'punhado', onde: 'Frutas',
    nomes: ['Framboesa', 'Raspberries', 'Frambuesas', 'Framboises', 'Himbeeren', 'Lamponi'] },
  { id: 'cereja', usda: 9070, gUn: 70, qtd: 1, un: 'punhado', onde: 'Frutas',
    nomes: ['Cereja', 'Cherries', 'Cerezas', 'Cerises', 'Kirschen', 'Ciliegie'] },
  { id: 'melao', usda: 9184, gUn: 100, qtd: 1, un: 'fatia', onde: 'Frutas',
    nomes: ['Melão', 'Honeydew melon', 'Melón', 'Melon', 'Honigmelone', 'Melone'] },
  { id: 'tangerina', usda: 9218, gUn: 90, qtd: 1, un: 'unidade', onde: 'Frutas', busca: 'mexerica bergamota clementina',
    nomes: ['Tangerina', 'Tangerine', 'Mandarina', 'Mandarine', 'Mandarine', 'Mandarino'] },
  { id: 'figo', usda: 9089, gUn: 50, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Figo', 'Fig', 'Higo', 'Figue', 'Feige', 'Fico'] },
  { id: 'tamara', usda: 9421, gUn: 24, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Tâmara', 'Date', 'Dátil', 'Datte', 'Dattel', 'Dattero'] },
  { id: 'uva-passa', usda: 9298, gUn: 14, qtd: 1, un: 'colher', onde: 'Frutas',
    nomes: ['Uva-passa', 'Raisins', 'Pasas', 'Raisins secs', 'Rosinen', 'Uvetta'] },
  { id: 'damasco-seco', usda: 9032, gUn: 7, qtd: 3, un: 'unidade', onde: 'Frutas',
    nomes: ['Damasco seco', 'Dried apricot', 'Damasco seco (chabacano)', 'Abricot sec', 'Getrocknete Aprikose', 'Albicocca secca'] },
  { id: 'suco-maca', usda: 9016, gUn: 200, qtd: 1, un: 'copo', onde: 'Frutas',
    nomes: ['Suco de maçã', 'Apple juice', 'Jugo de manzana', 'Jus de pomme', 'Apfelsaft', 'Succo di mela'] },

  /* --- castanhas e sementes ----------------------------------------- */
  { id: 'nozes', usda: 12155, gUn: 30, qtd: 1, un: 'punhado', onde: 'Castanhas e sementes',
    nomes: ['Nozes', 'Walnuts', 'Nueces', 'Noix', 'Walnüsse', 'Noci'] },
  { id: 'pistache', usda: 12152, gUn: 30, qtd: 1, un: 'punhado', onde: 'Castanhas e sementes',
    nomes: ['Pistache', 'Pistachios', 'Pistachos', 'Pistaches', 'Pistazien', 'Pistacchi'] },
  { id: 'avela', usda: 12120, gUn: 30, qtd: 1, un: 'punhado', onde: 'Castanhas e sementes',
    nomes: ['Avelãs', 'Hazelnuts', 'Avellanas', 'Noisettes', 'Haselnüsse', 'Nocciole'] },
  { id: 'chia', usda: 12006, gUn: 12, qtd: 1, un: 'colher', onde: 'Castanhas e sementes',
    nomes: ['Semente de chia', 'Chia seeds', 'Semillas de chía', 'Graines de chia', 'Chiasamen', 'Semi di chia'] },
  { id: 'linhaca', usda: 12220, gUn: 10, qtd: 1, un: 'colher', onde: 'Castanhas e sementes',
    nomes: ['Linhaça', 'Flaxseed', 'Linaza', 'Graines de lin', 'Leinsamen', 'Semi di lino'] },
  { id: 'semente-abobora', usda: 12014, gUn: 10, qtd: 1, un: 'colher', onde: 'Castanhas e sementes',
    nomes: ['Semente de abóbora', 'Pumpkin seeds', 'Pepitas de calabaza', 'Graines de courge', 'Kürbiskerne', 'Semi di zucca'] },
  { id: 'semente-girassol', usda: 12036, gUn: 10, qtd: 1, un: 'colher', onde: 'Castanhas e sementes',
    nomes: ['Semente de girassol', 'Sunflower seeds', 'Semillas de girasol', 'Graines de tournesol', 'Sonnenblumenkerne', 'Semi di girasole'] },
  { id: 'tahine', usda: 12166, gUn: 15, qtd: 1, un: 'colher', onde: 'Castanhas e sementes',
    nomes: ['Tahine (pasta de gergelim)', 'Tahini', 'Tahini', 'Tahini (purée de sésame)', 'Tahini (Sesammus)', 'Tahina'] },

  /* --- doces e lanches ---------------------------------------------- */
  { id: 'sorvete', usda: 19095, gUn: 60, qtd: 2, un: 'bola', onde: 'Doces e lanches', contem: ['leite'], busca: 'gelato',
    nomes: ['Sorvete de creme', 'Vanilla ice cream', 'Helado de vainilla', 'Glace à la vanille', 'Vanilleeis', 'Gelato alla vaniglia'] },
  { id: 'chocolate-amargo', usda: 19904, gUn: 20, qtd: 1, un: 'porção', onde: 'Doces e lanches', busca: 'meio amargo 70 cacau',
    nomes: ['Chocolate amargo 70%', 'Dark chocolate 70%', 'Chocolate amargo 70 %', 'Chocolat noir 70 %', 'Zartbitterschokolade 70 %', 'Cioccolato fondente 70%'] },
  { id: 'cookie', usda: 18159, gUn: 15, qtd: 2, un: 'unidade', onde: 'Doces e lanches', contem: ['ovo', 'leite'],
    nomes: ['Cookie com gotas de chocolate', 'Chocolate chip cookie', 'Galleta con chispas de chocolate', 'Cookie aux pépites de chocolat', 'Schokoladen-Cookie', 'Biscotto con gocce di cioccolato'] },
  { id: 'donut', usda: 18255, gUn: 60, qtd: 1, un: 'unidade', onde: 'Doces e lanches', contem: ['ovo', 'leite'], busca: 'rosquinha sonho',
    nomes: ['Donut', 'Glazed doughnut', 'Dona glaseada', 'Beignet glacé (donut)', 'Donut', 'Ciambella glassata'] },
  { id: 'muffin', usda: 18274, gUn: 110, qtd: 1, un: 'unidade', onde: 'Doces e lanches', contem: ['ovo', 'leite'],
    nomes: ['Muffin de mirtilo', 'Blueberry muffin', 'Muffin de arándanos', 'Muffin aux myrtilles', 'Blaubeermuffin', 'Muffin ai mirtilli'] },
  { id: 'batata-chips', usda: 19411, gUn: 30, qtd: 1, un: 'porção', onde: 'Doces e lanches',
    nomes: ['Batata chips', 'Potato chips', 'Papas fritas de bolsa', 'Chips', 'Kartoffelchips', 'Patatine in busta'] },
  { id: 'bolacha-arroz', usda: 19816, gUn: 9, qtd: 2, un: 'unidade', onde: 'Doces e lanches', busca: 'biscoito de arroz',
    nomes: ['Biscoito de arroz', 'Rice cake', 'Galleta de arroz', 'Galette de riz', 'Reiswaffel', 'Galletta di riso'] },
  { id: 'pretzel', usda: 19047, gUn: 30, qtd: 1, un: 'porção', onde: 'Doces e lanches',
    nomes: ['Pretzel', 'Pretzels', 'Pretzels', 'Bretzels', 'Salzbrezeln', 'Pretzel'] },
  { id: 'mel', usda: 19296, gUn: 21, qtd: 1, un: 'colher', onde: 'Doces e lanches',
    nomes: ['Mel', 'Honey', 'Miel', 'Miel', 'Honig', 'Miele'] },
  { id: 'geleia', usda: 19297, gUn: 20, qtd: 1, un: 'colher', onde: 'Doces e lanches', busca: 'marmelada',
    nomes: ['Geleia de fruta', 'Jam', 'Mermelada', 'Confiture', 'Marmelade', 'Marmellata'] },
  { id: 'creme-avela', usda: 19125, gUn: 20, qtd: 1, un: 'colher', onde: 'Doces e lanches', contem: ['leite'], busca: 'nutella',
    nomes: ['Creme de avelã com cacau', 'Chocolate hazelnut spread', 'Crema de avellana con cacao', 'Pâte à tartiner chocolat-noisette', 'Nuss-Nougat-Creme', 'Crema spalmabile alla nocciola'] },

];
