/* A segunda leva de comidas (29/09/2026): o que faltava das principais
   frutas, verduras, carnes, peixes, queijos e grãos do mundo, e as duas
   prateleiras que não existiam — Bebidas e Molhos e gorduras.

   Mesmo formato de comidas-novas.mjs, com dois campos a mais:
     taco     o número da TACO, para o que é brasileiro e a TACO mede
              (costela, cupim, maracujá, jabuticaba);
     preparo  quando a descrição da tabela não diz (a polenta é fubá
              cozido; a tabela descreve o fubá).

   FICARAM DE FORA, de propósito: sucos e suplementos (decisão de
   29/09/2026 — o dicionário é de alimento), e variações de preparo do
   que já está na lista (uma entrada por alimento; ver consolidacao).
   O óleo de fritar está aqui, em "Molhos e gorduras": o frito é o
   alimento mais o óleo.

   nomes: [português, inglês, espanhol, francês, alemão, italiano]. */
export const NOVAS_2 = [
  /* --- frutas ------------------------------------------------------- */
  { id: 'limao', usda: 9150, gUn: 60, qtd: 1, un: 'unidade', onde: 'Frutas', busca: 'siciliano',
    nomes: ['Limão-siciliano', 'Lemon', 'Limón amarillo', 'Citron', 'Zitrone', 'Limone'] },
  { id: 'lima', usda: 9159, gUn: 67, qtd: 1, un: 'unidade', onde: 'Frutas', busca: 'limao tahiti galego lime',
    nomes: ['Limão-taiti', 'Lime', 'Limón (lima)', 'Citron vert', 'Limette', 'Lime'] },
  { id: 'maracuja', taco: 232, gUn: 50, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Maracujá', 'Passion fruit', 'Maracuyá', 'Fruit de la passion', 'Passionsfrucht', 'Frutto della passione'] },
  { id: 'coco', usda: 12104, gUn: 45, qtd: 1, un: 'pedaço', onde: 'Frutas',
    nomes: ['Coco (polpa)', 'Coconut meat', 'Coco (pulpa)', 'Noix de coco (chair)', 'Kokosnuss (Fruchtfleisch)', 'Cocco (polpa)'] },
  { id: 'roma', usda: 9286, gUn: 87, qtd: 1, un: 'porção', onde: 'Frutas',
    nomes: ['Romã', 'Pomegranate', 'Granada', 'Grenade', 'Granatapfel', 'Melagrana'] },
  { id: 'amora', usda: 9042, gUn: 70, qtd: 1, un: 'punhado', onde: 'Frutas',
    nomes: ['Amora', 'Blackberries', 'Moras', 'Mûres', 'Brombeeren', 'More'] },
  { id: 'toranja', usda: 9112, gUn: 123, qtd: 1, un: 'porção', onde: 'Frutas', busca: 'grapefruit pomelo',
    nomes: ['Toranja', 'Grapefruit', 'Toronja', 'Pamplemousse', 'Grapefruit', 'Pompelmo'] },
  { id: 'nectarina', usda: 9191, gUn: 140, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Nectarina', 'Nectarine', 'Nectarina', 'Nectarine', 'Nektarine', 'Pesca noce'] },
  { id: 'caqui', usda: 9263, gUn: 168, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Caqui', 'Persimmon', 'Caqui', 'Kaki', 'Kaki', 'Cachi'] },
  { id: 'lichia', usda: 9164, gUn: 10, qtd: 5, un: 'unidade', onde: 'Frutas',
    nomes: ['Lichia', 'Lychee', 'Lichi', 'Litchi', 'Litschi', 'Litchi'] },
  { id: 'ameixa-seca', usda: 9291, gUn: 10, qtd: 3, un: 'unidade', onde: 'Frutas',
    nomes: ['Ameixa seca', 'Prunes', 'Ciruela pasa', 'Pruneaux', 'Backpflaumen', 'Prugne secche'] },
  { id: 'acerola', usda: 9001, gUn: 5, qtd: 10, un: 'unidade', onde: 'Frutas',
    nomes: ['Acerola', 'Acerola', 'Acerola', 'Acérola', 'Acerola', 'Acerola'] },
  { id: 'carambola', usda: 9060, gUn: 90, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Carambola', 'Star fruit', 'Carambola', 'Carambole', 'Sternfrucht', 'Carambola'] },
  { id: 'banana-da-terra', usda: 9278, gUn: 100, qtd: 1, un: 'porção', onde: 'Frutas', busca: 'platano maduro',
    nomes: ['Banana-da-terra', 'Plantain', 'Plátano macho', 'Banane plantain', 'Kochbanane', 'Platano da cuocere'] },
  { id: 'damasco', usda: 9021, gUn: 35, qtd: 2, un: 'unidade', onde: 'Frutas',
    nomes: ['Damasco', 'Apricot', 'Damasco (chabacano)', 'Abricot', 'Aprikose', 'Albicocca'] },
  { id: 'caju-fruta', taco: 186, gUn: 70, qtd: 1, un: 'unidade', onde: 'Frutas',
    nomes: ['Caju (fruta)', 'Cashew apple', 'Marañón (fruta)', 'Pomme de cajou', 'Cashewapfel', 'Pomo di anacardio'] },
  { id: 'jabuticaba', taco: 203, gUn: 60, qtd: 1, un: 'punhado', onde: 'Frutas',
    nomes: ['Jabuticaba', 'Jabuticaba (Brazilian grape tree)', 'Jabuticaba (fruta brasileña)', 'Jaboticaba (fruit brésilien)', 'Jabuticaba (brasilianische Frucht)', 'Jabuticaba (frutto brasiliano)'] },
  { id: 'graviola', taco: 201, gUn: 100, qtd: 1, un: 'porção', onde: 'Frutas',
    nomes: ['Graviola', 'Soursop', 'Guanábana', 'Corossol', 'Stachelannone', 'Graviola'] },
  { id: 'acai-polpa', taco: 168, gUn: 100, qtd: 1, un: 'porção', onde: 'Frutas',
    nomes: ['Açaí (polpa, sem açúcar)', 'Açaí pulp, unsweetened', 'Açaí (pulpa, sin azúcar)', 'Açaí (pulpe, sans sucre)', 'Açaí (Fruchtmark, ungesüßt)', 'Açaí (polpa, senza zucchero)'] },

  /* --- verduras e legumes ------------------------------------------- */
  { id: 'cebola', usda: 11282, gUn: 30, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Cebola', 'Onion', 'Cebolla', 'Oignon', 'Zwiebel', 'Cipolla'] },
  { id: 'alho', usda: 11215, gUn: 3, qtd: 2, un: 'dente', onde: 'Verduras e legumes',
    nomes: ['Alho', 'Garlic', 'Ajo', 'Ail', 'Knoblauch', 'Aglio'] },
  { id: 'rucula', usda: 11959, gUn: 20, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Rúcula', 'Arugula', 'Rúcula', 'Roquette', 'Rucola', 'Rucola'] },
  { id: 'agriao', usda: 11591, gUn: 25, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Agrião', 'Watercress', 'Berro', 'Cresson', 'Brunnenkresse', 'Crescione'] },
  { id: 'alface', usda: 11253, gUn: 40, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Alface', 'Lettuce', 'Lechuga', 'Laitue', 'Kopfsalat', 'Lattuga'] },
  { id: 'rabanete', usda: 11429, gUn: 5, qtd: 4, un: 'unidade', onde: 'Verduras e legumes',
    nomes: ['Rabanete', 'Radishes', 'Rábanos', 'Radis', 'Radieschen', 'Ravanelli'] },
  { id: 'alho-poro', usda: 11247, gUn: 60, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Alho-poró', 'Leek', 'Puerro', 'Poireau', 'Lauch', 'Porro'] },
  { id: 'acelga', usda: 11148, gUn: 90, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Acelga', 'Swiss chard', 'Acelga', 'Blettes', 'Mangold', 'Bietole'] },
  { id: 'bok-choy', usda: 11117, gUn: 85, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Bok choy (acelga chinesa)', 'Bok choy', 'Bok choy', 'Pak-choï', 'Pak Choi', 'Pak choi'] },
  { id: 'nori', rotulo: { p: 33, kcal: 320, carb: 40, gord: 3, fibra: 33 }, gUn: 3, qtd: 2, un: 'folha', onde: 'Verduras e legumes',
    nomes: ['Alga nori', 'Nori seaweed', 'Alga nori', 'Algue nori', 'Nori-Alge', 'Alga nori'] },
  { id: 'kimchi', usda: 11118, gUn: 50, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Kimchi', 'Kimchi', 'Kimchi', 'Kimchi', 'Kimchi', 'Kimchi'] },
  { id: 'nopal', usda: 11964, gUn: 75, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Nopal (palma)', 'Nopales (cactus pads)', 'Nopales', 'Nopal (raquette de cactus)', 'Nopal (Kaktusblatt)', 'Nopal (pala di fico d’India)'] },
  { id: 'broto-feijao', usda: 11043, gUn: 50, qtd: 1, un: 'porção', onde: 'Verduras e legumes', busca: 'moyashi broto de soja',
    nomes: ['Broto de feijão', 'Bean sprouts', 'Germinado de soya (frijol mungo)', 'Pousses de soja', 'Sojasprossen', 'Germogli di soia'] },
  { id: 'aipo', usda: 11143, gUn: 40, qtd: 1, un: 'pedaço', onde: 'Verduras e legumes', busca: 'salsao',
    nomes: ['Salsão (aipo)', 'Celery', 'Apio', 'Céleri branche', 'Staudensellerie', 'Sedano'] },
  { id: 'kale', usda: 11233, gUn: 20, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Couve kale', 'Kale', 'Kale', 'Chou kale', 'Kale', 'Cavolo riccio (kale)'] },
  { id: 'alcachofra', usda: 11008, gUn: 120, qtd: 1, un: 'unidade', onde: 'Verduras e legumes',
    nomes: ['Alcachofra', 'Artichoke', 'Alcachofa', 'Artichaut', 'Artischocke', 'Carciofo'] },
  { id: 'inhame', usda: 11519, gUn: 100, qtd: 1, un: 'porção', onde: 'Verduras e legumes', busca: 'taro',
    nomes: ['Inhame (taro)', 'Taro', 'Malanga (taro)', 'Taro', 'Taro', 'Taro'] },
  { id: 'cara', taco: 102, gUn: 100, qtd: 1, un: 'porção', onde: 'Verduras e legumes',
    nomes: ['Cará', 'Yam', 'Ñame', 'Igname', 'Yamswurzel', 'Igname'] },

  /* --- carnes e aves ------------------------------------------------ */
  { id: 'costela', taco: 347, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves',
    nomes: ['Costela bovina', 'Beef ribs', 'Costilla de res', 'Plat de côtes de bœuf', 'Rinderrippe', 'Costine di manzo'] },
  { id: 'cupim', taco: 353, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves',
    nomes: ['Cupim', 'Cupim (beef hump)', 'Cupim (giba de res)', 'Cupim (bosse de bœuf)', 'Cupim (Rinderhöcker)', 'Cupim (gobba di manzo)'] },
  { id: 'fraldinha', taco: 361, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves',
    nomes: ['Fraldinha', 'Flank steak', 'Falda de res (vacío)', 'Bavette', 'Flanksteak', 'Bavetta di manzo'] },
  { id: 'maminha', taco: 368, gUn: 100, qtd: 1, un: 'bife', onde: 'Carnes e aves',
    nomes: ['Maminha', 'Tri-tip', 'Colita de cuadril', 'Aiguillette de rumsteck', 'Bürgermeisterstück', 'Punta di sottofesa'] },
  { id: 'carne-seca', taco: 384, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves', busca: 'charque jaba',
    nomes: ['Carne seca', 'Brazilian dried beef (carne seca)', 'Carne seca (tasajo)', 'Viande séchée (carne seca)', 'Trockenfleisch (Carne seca)', 'Carne secca (carne seca)'] },
  { id: 'coracao-frango', taco: 395, gUn: 5, qtd: 8, un: 'unidade', onde: 'Carnes e aves', contem: ['ave'],
    nomes: ['Coração de frango', 'Chicken hearts', 'Corazones de pollo', 'Cœurs de poulet', 'Hähnchenherzen', 'Cuori di pollo'] },
  { id: 'asa-frango', usda: 5103, gUn: 35, qtd: 3, un: 'unidade', onde: 'Carnes e aves', contem: ['ave'],
    nomes: ['Asa de frango', 'Chicken wings', 'Alitas de pollo', 'Ailes de poulet', 'Hähnchenflügel', 'Ali di pollo'] },
  { id: 'figado-frango', usda: 5028, gUn: 44, qtd: 2, un: 'unidade', onde: 'Carnes e aves', contem: ['ave'],
    nomes: ['Fígado de frango', 'Chicken liver', 'Hígado de pollo', 'Foie de volaille', 'Hühnerleber', 'Fegatini di pollo'] },
  { id: 'vitela', usda: 17103, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves',
    nomes: ['Vitela', 'Veal', 'Ternera', 'Veau', 'Kalbfleisch', 'Vitello'] },
  { id: 'cabrito', usda: 17169, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves',
    nomes: ['Cabrito', 'Goat meat', 'Carne de chivo', 'Chevreau', 'Ziegenfleisch', 'Capretto'] },
  { id: 'coelho', usda: 17178, gUn: 100, qtd: 1, un: 'porção', onde: 'Carnes e aves',
    nomes: ['Coelho', 'Rabbit', 'Conejo', 'Lapin', 'Kaninchen', 'Coniglio'] },

  /* --- peixes e frutos do mar --------------------------------------- */
  { id: 'linguado', usda: 15029, gUn: 127, qtd: 1, un: 'filé', onde: 'Peixes e frutos do mar',
    nomes: ['Linguado', 'Sole (flounder)', 'Lenguado', 'Sole', 'Seezunge', 'Sogliola'] },
  { id: 'robalo', usda: 15092, gUn: 100, qtd: 1, un: 'filé', onde: 'Peixes e frutos do mar',
    nomes: ['Robalo', 'Sea bass', 'Róbalo', 'Bar (loup)', 'Wolfsbarsch', 'Branzino'] },
  { id: 'pargo', usda: 15102, gUn: 120, qtd: 1, un: 'filé', onde: 'Peixes e frutos do mar',
    nomes: ['Pargo', 'Snapper', 'Pargo (huachinango)', 'Vivaneau', 'Schnapper', 'Dentice'] },
  { id: 'pintado', taco: 313, gUn: 120, qtd: 1, un: 'posta', onde: 'Peixes e frutos do mar',
    nomes: ['Pintado', 'Pintado (Brazilian catfish)', 'Pintado (bagre)', 'Pintado (poisson-chat)', 'Pintado (Wels)', 'Pintado (pesce gatto)'] },
  { id: 'arenque', usda: 15041, gUn: 20, qtd: 2, un: 'pedaço', onde: 'Peixes e frutos do mar',
    nomes: ['Arenque em conserva', 'Pickled herring', 'Arenque en escabeche', 'Hareng mariné', 'Eingelegter Hering', 'Aringa marinata'] },
  { id: 'ostra', usda: 15167, gUn: 14, qtd: 6, un: 'unidade', onde: 'Peixes e frutos do mar',
    nomes: ['Ostra', 'Oysters', 'Ostras (ostiones)', 'Huîtres', 'Austern', 'Ostriche'] },
  { id: 'vieira', usda: 90240, gUn: 30, qtd: 3, un: 'unidade', onde: 'Peixes e frutos do mar',
    nomes: ['Vieira', 'Scallops', 'Vieiras', 'Noix de Saint-Jacques', 'Jakobsmuscheln', 'Capesante'] },
  { id: 'lagosta', usda: 15148, gUn: 100, qtd: 1, un: 'porção', onde: 'Peixes e frutos do mar',
    nomes: ['Lagosta', 'Lobster', 'Langosta', 'Langouste', 'Languste', 'Aragosta'] },
  { id: 'vongole', usda: 15159, gUn: 90, qtd: 1, un: 'porção', onde: 'Peixes e frutos do mar', busca: 'marisco berbigao',
    nomes: ['Vôngole (marisco)', 'Clams', 'Almejas', 'Palourdes', 'Venusmuscheln', 'Vongole'] },

  /* --- leite e queijos ---------------------------------------------- */
  { id: 'queijo-coalho', rotulo: { p: 23, kcal: 333, carb: 1, gord: 25, fibra: 0 }, gUn: 40, qtd: 1, un: 'unidade', onde: 'Leite e queijos',
    nomes: ['Queijo coalho', 'Queijo coalho (Brazilian grilling cheese)', 'Queso coalho (queso para asar)', 'Queijo coalho (fromage à griller)', 'Queijo coalho (Grillkäse)', 'Queijo coalho (formaggio da griglia)'] },
  { id: 'queso-fresco', rotulo: { p: 18, kcal: 286, carb: 3.6, gord: 21, fibra: 0 }, gUn: 30, qtd: 1, un: 'fatia', onde: 'Leite e queijos',
    nomes: ['Queso fresco (queijo branco latino)', 'Queso fresco', 'Queso fresco', 'Queso fresco (fromage frais latino)', 'Queso fresco (lateinamerikanischer Frischkäse)', 'Queso fresco (formaggio fresco latino)'] },
  { id: 'provolone', usda: 1035, gUn: 20, qtd: 1, un: 'fatia', onde: 'Leite e queijos',
    nomes: ['Queijo provolone', 'Provolone', 'Queso provolone', 'Provolone', 'Provolone', 'Provolone'] },
  { id: 'gorgonzola', usda: 1004, gUn: 30, qtd: 1, un: 'porção', onde: 'Leite e queijos', busca: 'roquefort queijo azul',
    nomes: ['Gorgonzola (queijo azul)', 'Blue cheese', 'Queso azul', 'Bleu (gorgonzola, roquefort)', 'Blauschimmelkäse', 'Gorgonzola'] },
  { id: 'queijo-cabra', usda: 1159, gUn: 30, qtd: 1, un: 'porção', onde: 'Leite e queijos',
    nomes: ['Queijo de cabra', 'Goat cheese', 'Queso de cabra', 'Fromage de chèvre', 'Ziegenkäse', 'Formaggio di capra'] },
  { id: 'mascarpone', rotulo: { p: 4.6, kcal: 430, carb: 4, gord: 44, fibra: 0 }, gUn: 30, qtd: 1, un: 'colher', onde: 'Leite e queijos',
    nomes: ['Mascarpone', 'Mascarpone', 'Mascarpone', 'Mascarpone', 'Mascarpone', 'Mascarpone'] },
  { id: 'halloumi', rotulo: { p: 21, kcal: 316, carb: 1.6, gord: 25, fibra: 0 }, gUn: 40, qtd: 1, un: 'fatia', onde: 'Leite e queijos',
    nomes: ['Halloumi', 'Halloumi', 'Halloumi', 'Halloumi', 'Halloumi', 'Halloumi'] },
  { id: 'paneer', rotulo: { p: 18.3, kcal: 265, carb: 1.2, gord: 20.8, fibra: 0 }, gUn: 50, qtd: 1, un: 'porção', onde: 'Leite e queijos',
    nomes: ['Paneer (queijo indiano)', 'Paneer', 'Paneer (queso indio)', 'Paneer (fromage indien)', 'Paneer (indischer Käse)', 'Paneer (formaggio indiano)'] },
  { id: 'pecorino', usda: 1038, gUn: 10, qtd: 1, un: 'colher', onde: 'Leite e queijos',
    nomes: ['Queijo pecorino', 'Pecorino Romano', 'Queso pecorino', 'Pecorino', 'Pecorino', 'Pecorino romano'] },
  { id: 'leite-semidesnatado', usda: 1079, gUn: 200, qtd: 1, un: 'copo', onde: 'Leite e queijos',
    nomes: ['Leite semidesnatado', 'Reduced-fat milk (2%)', 'Leche semidescremada', 'Lait demi-écrémé', 'Teilentrahmte Milch', 'Latte parzialmente scremato'] },
  { id: 'iogurte-grego-integral', usda: 1293, gUn: 170, qtd: 1, un: 'pote', onde: 'Leite e queijos',
    nomes: ['Iogurte grego integral', 'Whole milk Greek yogurt', 'Yogur griego entero', 'Yaourt grec entier', 'Griechischer Joghurt, vollfett', 'Yogurt greco intero'] },

  /* --- grãos e feijões ---------------------------------------------- */
  { id: 'feijao-fradinho', usda: 16063, gUn: 80, qtd: 1, un: 'concha', onde: 'Grãos e feijões', busca: 'caupi macassar corda',
    nomes: ['Feijão-fradinho', 'Black-eyed peas', 'Frijol de ojo negro', 'Haricots à œil noir', 'Augenbohnen', 'Fagioli dall’occhio'] },
  { id: 'fava', usda: 16053, gUn: 80, qtd: 1, un: 'concha', onde: 'Grãos e feijões',
    nomes: ['Fava', 'Fava beans', 'Habas', 'Fèves', 'Dicke Bohnen', 'Fave'] },
  { id: 'soja-grao', usda: 16109, gUn: 80, qtd: 1, un: 'concha', onde: 'Grãos e feijões',
    nomes: ['Soja em grão', 'Soybeans', 'Frijol de soya', 'Fèves de soja', 'Sojabohnen', 'Semi di soia'] },
  { id: 'feijao-refrito', usda: 16103, gUn: 60, qtd: 1, un: 'porção', onde: 'Grãos e feijões',
    nomes: ['Feijão refrito', 'Refried beans', 'Frijoles refritos', 'Haricots frits (refritos)', 'Refried Beans', 'Fagioli refritos'] },
  /* A PTS é vendida seca e comida hidratada: o rendimento de 3 (um de
     proteína seca para três de hidratada) leva o número ao que vai para o
     prato. A tabela descreve o produto seco. */
  { id: 'pts', usda: 16106, rend: 3, gUn: 30, qtd: 3, un: 'colher', onde: 'Grãos e feijões', busca: 'proteina texturizada carne de soja',
    nomes: ['Proteína de soja texturizada (hidratada)', 'Textured soy protein (rehydrated)', 'Proteína de soya texturizada (hidratada)', 'Protéines de soja texturées (réhydratées)', 'Sojaschnetzel (eingeweicht)', 'Proteine di soia testurizzate (reidratate)'] },

  /* --- arroz, massas e pães ----------------------------------------- */
  { id: 'cevadinha', usda: 20006, gUn: 30, qtd: 3, un: 'colher', onde: 'Arroz, massas e pães',
    nomes: ['Cevadinha', 'Pearl barley', 'Cebada perlada', 'Orge perlé', 'Perlgraupen', 'Orzo perlato'] },
  { id: 'trigo-sarraceno', usda: 20010, gUn: 30, qtd: 3, un: 'colher', onde: 'Arroz, massas e pães',
    nomes: ['Trigo-sarraceno', 'Buckwheat', 'Trigo sarraceno', 'Sarrasin', 'Buchweizen', 'Grano saraceno'] },
  /* O fubá cozido: o rendimento de 4,5 (uma parte de fubá para quatro e
     meia de polenta pronta) leva o número do fubá ao da polenta. */
  { id: 'polenta', usda: 20022, rend: 4.5, preparo: 'cozido', gUn: 150, qtd: 1, un: 'porção', onde: 'Arroz, massas e pães', busca: 'angu fuba cozido',
    nomes: ['Polenta', 'Polenta', 'Polenta', 'Polenta', 'Polenta', 'Polenta'] },
  { id: 'naan', usda: 28307, gUn: 90, qtd: 1, un: 'unidade', onde: 'Arroz, massas e pães', contem: ['leite', 'ovo'],
    nomes: ['Pão naan', 'Naan', 'Pan naan', 'Naan', 'Naan-Brot', 'Pane naan'] },
  { id: 'arepa', usda: 36415, gUn: 98, qtd: 1, un: 'unidade', onde: 'Arroz, massas e pães',
    nomes: ['Arepa', 'Arepa', 'Arepa', 'Arepa', 'Arepa', 'Arepa'] },
  { id: 'pao-hamburguer', usda: 18350, gUn: 50, qtd: 1, un: 'unidade', onde: 'Arroz, massas e pães', contem: ['leite', 'ovo'],
    nomes: ['Pão de hambúrguer', 'Hamburger bun', 'Pan para hamburguesa', 'Pain à burger', 'Burgerbrötchen', 'Panino per hamburger'] },

  /* --- castanhas e sementes ----------------------------------------- */
  { id: 'macadamia', usda: 12131, gUn: 30, qtd: 1, un: 'punhado', onde: 'Castanhas e sementes',
    nomes: ['Macadâmia', 'Macadamia nuts', 'Nueces de macadamia', 'Noix de macadamia', 'Macadamianüsse', 'Noci di macadamia'] },
  { id: 'gergelim', usda: 12023, gUn: 9, qtd: 1, un: 'colher', onde: 'Castanhas e sementes',
    nomes: ['Gergelim', 'Sesame seeds', 'Ajonjolí (sésamo)', 'Graines de sésame', 'Sesam', 'Semi di sesamo'] },
  { id: 'peca', usda: 12142, gUn: 30, qtd: 1, un: 'punhado', onde: 'Castanhas e sementes',
    nomes: ['Noz-pecã', 'Pecans', 'Nueces pecanas', 'Noix de pécan', 'Pekannüsse', 'Noci pecan'] },
  { id: 'coco-ralado', usda: 12108, gUn: 10, qtd: 1, un: 'colher', onde: 'Castanhas e sementes',
    nomes: ['Coco ralado', 'Shredded coconut', 'Coco rallado', 'Noix de coco râpée', 'Kokosraspeln', 'Cocco grattugiato'] },

  /* --- doces e lanches ---------------------------------------------- */
  { id: 'acucar', usda: 19335, gUn: 5, qtd: 1, un: 'colher', onde: 'Doces e lanches',
    nomes: ['Açúcar', 'Sugar', 'Azúcar', 'Sucre', 'Zucker', 'Zucchero'] },
  { id: 'chocolate-branco', usda: 19087, gUn: 25, qtd: 1, un: 'porção', onde: 'Doces e lanches', contem: ['leite'],
    nomes: ['Chocolate branco', 'White chocolate', 'Chocolate blanco', 'Chocolat blanc', 'Weiße Schokolade', 'Cioccolato bianco'] },
  { id: 'gelatina', usda: 19173, gUn: 120, qtd: 1, un: 'porção', onde: 'Doces e lanches', contem: ['carne'],
    nomes: ['Gelatina (sobremesa)', 'Gelatin dessert', 'Gelatina', 'Gelée dessert', 'Götterspeise', 'Gelatina (dessert)'] },
  { id: 'bolo-simples', usda: 18120, gUn: 60, qtd: 1, un: 'fatia-torta', onde: 'Doces e lanches', contem: ['ovo', 'leite'],
    nomes: ['Bolo simples', 'Pound cake', 'Panqué (bizcocho)', 'Quatre-quarts', 'Rührkuchen', 'Torta margherita'] },
  { id: 'doce-de-leite', usda: 1225, gUn: 20, qtd: 1, un: 'colher', onde: 'Doces e lanches', contem: ['leite'],
    nomes: ['Doce de leite', 'Dulce de leche', 'Dulce de leche (cajeta)', 'Confiture de lait', 'Dulce de leche (Milchkaramell)', 'Dulce de leche'] },

  /* --- bebidas ------------------------------------------------------ */
  { id: 'cafe', usda: 14209, gUn: 150, qtd: 1, un: 'xícara', onde: 'Bebidas', busca: 'cafezinho espresso',
    nomes: ['Café (sem açúcar)', 'Coffee (black)', 'Café (sin azúcar)', 'Café (sans sucre)', 'Kaffee (schwarz)', 'Caffè (senza zucchero)'] },
  { id: 'cha', usda: 14355, gUn: 200, qtd: 1, un: 'xícara', onde: 'Bebidas',
    nomes: ['Chá (sem açúcar)', 'Tea (unsweetened)', 'Té (sin azúcar)', 'Thé (sans sucre)', 'Tee (ungesüßt)', 'Tè (senza zucchero)'] },
  { id: 'refrigerante', usda: 14148, gUn: 350, qtd: 1, un: 'lata-bebida', onde: 'Bebidas', busca: 'coca cola guarana soda',
    nomes: ['Refrigerante', 'Soda (regular)', 'Refresco (gaseosa)', 'Soda', 'Softdrink', 'Bibita gassata'] },
  { id: 'refrigerante-zero', usda: 14166, gUn: 350, qtd: 1, un: 'lata-bebida', onde: 'Bebidas', busca: 'diet light coca zero',
    nomes: ['Refrigerante zero', 'Diet soda', 'Refresco sin azúcar', 'Soda sans sucre', 'Softdrink ohne Zucker', 'Bibita gassata zero'] },
  { id: 'cerveja', usda: 14003, gUn: 350, qtd: 1, un: 'lata-bebida', onde: 'Bebidas', busca: 'chopp',
    nomes: ['Cerveja', 'Beer', 'Cerveza', 'Bière', 'Bier', 'Birra'] },
  { id: 'cerveja-sem-alcool', rotulo: { p: 0.2, kcal: 21, carb: 4.6, gord: 0, fibra: 0 }, gUn: 350, qtd: 1, un: 'lata-bebida', onde: 'Bebidas',
    nomes: ['Cerveja sem álcool', 'Non-alcoholic beer', 'Cerveza sin alcohol', 'Bière sans alcool', 'Alkoholfreies Bier', 'Birra analcolica'] },
  { id: 'vinho-tinto', usda: 14096, gUn: 150, qtd: 1, un: 'taça', onde: 'Bebidas',
    nomes: ['Vinho tinto', 'Red wine', 'Vino tinto', 'Vin rouge', 'Rotwein', 'Vino rosso'] },
  { id: 'vinho-branco', usda: 14116, gUn: 150, qtd: 1, un: 'taça', onde: 'Bebidas',
    nomes: ['Vinho branco', 'White wine', 'Vino blanco', 'Vin blanc', 'Weißwein', 'Vino bianco'] },
  { id: 'destilado', usda: 14037, gUn: 45, qtd: 1, un: 'dose', onde: 'Bebidas', busca: 'cachaca vodca vodka whisky uisque rum gin tequila',
    nomes: ['Destilado (cachaça, vodca, uísque)', 'Spirits (vodka, whiskey, rum)', 'Destilado (tequila, ron, vodka)', 'Alcool fort (vodka, whisky, rhum)', 'Spirituosen (Wodka, Whisky, Rum)', 'Superalcolici (vodka, whisky, rum)'] },
  { id: 'agua-coco', usda: 12119, gUn: 250, qtd: 1, un: 'copo', onde: 'Bebidas',
    nomes: ['Água de coco', 'Coconut water', 'Agua de coco', 'Eau de coco', 'Kokoswasser', 'Acqua di cocco'] },

  /* --- molhos e gorduras -------------------------------------------- */
  { id: 'azeite', usda: 4053, gUn: 13, qtd: 1, un: 'colher', onde: 'Molhos e gorduras',
    nomes: ['Azeite de oliva', 'Olive oil', 'Aceite de oliva', 'Huile d’olive', 'Olivenöl', 'Olio d’oliva'] },
  { id: 'oleo', usda: 4669, gUn: 13, qtd: 1, un: 'colher', onde: 'Molhos e gorduras', busca: 'oleo de soja canola girassol fritura',
    nomes: ['Óleo vegetal', 'Vegetable oil', 'Aceite vegetal', 'Huile végétale', 'Pflanzenöl', 'Olio di semi'] },
  { id: 'maionese', usda: 4025, gUn: 14, qtd: 1, un: 'colher', onde: 'Molhos e gorduras', contem: ['ovo'],
    nomes: ['Maionese', 'Mayonnaise', 'Mayonesa', 'Mayonnaise', 'Mayonnaise', 'Maionese'] },
  { id: 'ketchup', usda: 11935, gUn: 17, qtd: 1, un: 'colher', onde: 'Molhos e gorduras',
    nomes: ['Ketchup', 'Ketchup', 'Kétchup', 'Ketchup', 'Ketchup', 'Ketchup'] },
  { id: 'mostarda', usda: 2046, gUn: 10, qtd: 1, un: 'colher', onde: 'Molhos e gorduras',
    nomes: ['Mostarda', 'Mustard', 'Mostaza', 'Moutarde', 'Senf', 'Senape'] },
  { id: 'molho-tomate', usda: 11549, gUn: 20, qtd: 3, un: 'colher', onde: 'Molhos e gorduras',
    nomes: ['Molho de tomate', 'Tomato sauce', 'Salsa de tomate', 'Sauce tomate', 'Tomatensoße', 'Salsa di pomodoro'] },
  { id: 'shoyu', usda: 16123, gUn: 16, qtd: 1, un: 'colher', onde: 'Molhos e gorduras',
    nomes: ['Shoyu (molho de soja)', 'Soy sauce', 'Salsa de soya', 'Sauce soja', 'Sojasoße', 'Salsa di soia'] },
  { id: 'creme-leite', usda: 1050, gUn: 15, qtd: 1, un: 'colher', onde: 'Molhos e gorduras', contem: ['leite'],
    nomes: ['Creme de leite', 'Cream', 'Crema de leche', 'Crème (liquide)', 'Sahne', 'Panna da cucina'] },
  { id: 'leite-condensado', usda: 1095, gUn: 20, qtd: 1, un: 'colher', onde: 'Molhos e gorduras', contem: ['leite'],
    nomes: ['Leite condensado', 'Sweetened condensed milk', 'Leche condensada', 'Lait concentré sucré', 'Gezuckerte Kondensmilch', 'Latte condensato'] },
  { id: 'pesto', usda: 6626, gUn: 15, qtd: 1, un: 'colher', onde: 'Molhos e gorduras', contem: ['leite'],
    nomes: ['Molho pesto', 'Pesto', 'Pesto', 'Pesto', 'Pesto', 'Pesto'] },
];
