/* Os nomes das comidas da lista brasileira nos outros cinco idiomas:
   [inglês, espanhol, francês, alemão, italiano]. O português está na
   própria curadoria (comidas-base.json).

   ⚠️ SÃO TRADUÇÕES MINHAS, e entram na revisão nativa junto com o resto
   dos catálogos (PENDENCIAS, item 20). Um prato que só existe no Brasil
   fica com o nome dele — "Feijoada" é feijoada em qualquer língua —, com
   uma explicação curta quando o nome sozinho não diz nada a quem nunca
   comeu. */
export const NOMES_BASE = {
  /* carnes e aves */
  'peito-frango': ['Grilled chicken breast', 'Pechuga de pollo a la plancha', 'Blanc de poulet grillé', 'Gegrillte Hähnchenbrust', 'Petto di pollo alla griglia'],
  'frango-assado': ['Roast chicken, skinless', 'Pollo asado sin piel', 'Poulet rôti sans peau', 'Brathähnchen ohne Haut', 'Pollo arrosto senza pelle'],
  sobrecoxa: ['Chicken thigh or drumstick', 'Muslo o pierna de pollo', 'Cuisse ou pilon de poulet', 'Hähnchenschenkel', 'Coscia o sovracoscia di pollo'],
  'frango-milanesa': ['Breaded chicken cutlet', 'Milanesa de pollo', 'Escalope de poulet panée', 'Paniertes Hähnchenschnitzel', 'Cotoletta di pollo impanata'],
  patinho: ['Lean grilled beef steak', 'Bistec magro de res a la plancha', 'Steak de bœuf maigre grillé', 'Mageres Rindersteak, gegrillt', 'Bistecca magra di manzo alla griglia'],
  contrafile: ['Grilled strip steak', 'Bistec de lomo de res a la plancha', 'Faux-filet grillé', 'Gegrilltes Rumpsteak', 'Controfiletto alla griglia'],
  'file-mignon': ['Grilled filet mignon', 'Filete de res a la plancha', 'Filet mignon grillé', 'Gegrilltes Rinderfilet', 'Filetto di manzo alla griglia'],
  picanha: ['Grilled picanha (top sirloin cap)', 'Picaña a la parrilla', 'Picanha grillée (aiguillette baronne)', 'Gegrillte Picanha (Tafelspitz)', 'Picanha alla griglia (codone)'],
  'carne-moida': ['Sautéed ground beef', 'Carne molida guisada', 'Bœuf haché revenu', 'Angebratenes Rinderhack', 'Macinato di manzo in padella'],
  'carne-panela': ['Pot roast', 'Carne guisada', 'Bœuf braisé', 'Rinderschmorbraten', 'Brasato di manzo'],
  musculo: ['Stewed beef shank', 'Jarrete de res cocido (chambarete)', 'Jarret de bœuf cuit', 'Gekochte Rinderhesse', 'Muscolo di manzo bollito'],
  hamburguer: ['Hamburger patty', 'Carne de hamburguesa', 'Steak haché', 'Hamburger-Patty', 'Hamburger di manzo'],
  linguica: ['Pork sausage (linguiça)', 'Longaniza', 'Saucisse de porc (linguiça)', 'Schweinswurst (Linguiça)', 'Salsiccia di maiale (linguiça)'],
  lombo: ['Roast pork loin', 'Lomo de cerdo asado', 'Rôti de porc', 'Schweinelende, gebraten', 'Lonza di maiale arrosto'],
  pernil: ['Roast pork leg', 'Pierna de cerdo asada', 'Jambon de porc rôti', 'Schweinekeule, gebraten', 'Cosciotto di maiale arrosto'],
  costelinha: ['Pork ribs', 'Costillitas de cerdo', 'Travers de porc', 'Schweinerippchen', 'Costine di maiale'],
  'coxao-mole': ['Boiled beef (top round)', 'Carne de res cocida', 'Bœuf bouilli (tende de tranche)', 'Gekochtes Rindfleisch (Oberschale)', 'Manzo bollito (fesa)'],
  almondega: ['Meatballs', 'Albóndigas', 'Boulettes de viande', 'Fleischbällchen', 'Polpette di carne'],
  figado: ['Liver and onions', 'Hígado encebollado', 'Foie de bœuf aux oignons', 'Leber mit Zwiebeln', 'Fegato alla veneziana'],
  peru: ['Roast turkey', 'Pavo asado', 'Dinde rôtie', 'Truthahnbraten', 'Tacchino arrosto'],
  quibe: ['Baked kibbeh', 'Kibbe al horno', 'Kebbé au four', 'Gebackenes Kibbeh', 'Kibbeh al forno'],
  presunto: ['Ham', 'Jamón cocido', 'Jambon blanc', 'Kochschinken', 'Prosciutto cotto'],
  mortadela: ['Mortadella', 'Mortadela', 'Mortadelle', 'Mortadella', 'Mortadella'],
  coxinha: ['Coxinha (chicken croquette)', 'Coxinha (croqueta de pollo)', 'Coxinha (croquette de poulet)', 'Coxinha (Hähnchenkrokette)', 'Coxinha (crocchetta di pollo)'],

  /* peixes e frutos do mar */
  salmao: ['Grilled salmon', 'Salmón a la plancha', 'Saumon grillé', 'Gegrillter Lachs', 'Salmone alla griglia'],
  merluza: ['Baked hake', 'Merluza al horno', 'Merlu au four', 'Seehecht aus dem Ofen', 'Nasello al forno'],
  pescada: ['Fried whiting', 'Pescado blanco frito (pescada)', 'Merlan frit', 'Gebratener Wittling', 'Filetto di pesce bianco fritto'],
  sardinha: ['Roasted sardine', 'Sardina asada', 'Sardine au four', 'Sardine aus dem Ofen', 'Sardina al forno'],
  'sardinha-lata': ['Canned sardines', 'Sardinas en lata', 'Sardines en boîte', 'Sardinen aus der Dose', 'Sardine in scatola'],
  'atum-lata': ['Canned tuna', 'Atún en lata', 'Thon en boîte', 'Thunfisch aus der Dose', 'Tonno in scatola'],
  bacalhau: ['Sautéed salt cod', 'Bacalao guisado', 'Morue sautée', 'Geschmorter Klippfisch (Bacalhau)', 'Baccalà in padella'],
  corvina: ['Baked croaker', 'Corvina al horno', 'Maigre au four', 'Umberfisch aus dem Ofen', 'Ombrina al forno'],
  manjuba: ['Fried anchovies', 'Anchoas fritas', 'Petits poissons frits', 'Frittierte Sardellen', 'Alici fritte'],
  camarao: ['Boiled shrimp', 'Camarones cocidos', 'Crevettes cuites', 'Gekochte Garnelen', 'Gamberi lessati'],

  /* ovos */
  'ovo-cozido': ['Boiled egg', 'Huevo cocido', 'Œuf dur', 'Gekochtes Ei', 'Uovo sodo'],
  'ovo-frito': ['Fried or scrambled egg', 'Huevo frito o revuelto', 'Œuf au plat ou brouillé', 'Spiegel- oder Rührei', 'Uovo fritto o strapazzato'],
  omelete: ['Cheese omelet', 'Omelet de queso', 'Omelette au fromage', 'Käseomelett', 'Omelette al formaggio'],
  'ovo-codorna': ['Quail egg', 'Huevo de codorniz', 'Œuf de caille', 'Wachtelei', 'Uovo di quaglia'],

  /* leite e queijos */
  iogurte: ['Plain yogurt', 'Yogur natural', 'Yaourt nature', 'Naturjoghurt', 'Yogurt bianco'],
  'iogurte-fruta': ['Fruit yogurt', 'Yogur de frutas', 'Yaourt aux fruits', 'Fruchtjoghurt', 'Yogurt alla frutta'],
  'queijo-minas': ['Queijo minas (fresh white cheese)', 'Queso fresco', 'Fromage frais de Minas', 'Minas-Käse (frischer Weißkäse)', 'Formaggio fresco (Minas)'],
  mussarela: ['Mozzarella', 'Queso mozzarella', 'Mozzarella', 'Mozzarella', 'Mozzarella'],
  'queijo-prato': ['Prato cheese (mild yellow cheese)', 'Queso prato (queso amarillo suave)', 'Fromage prato (pâte pressée douce)', 'Prato-Käse (milder Schnittkäse)', 'Queijo prato (formaggio dolce a pasta semidura)'],
  parmesao: ['Grated parmesan', 'Queso parmesano rallado', 'Parmesan râpé', 'Geriebener Parmesan', 'Parmigiano grattugiato'],
  ricota: ['Ricotta', 'Ricota', 'Ricotta', 'Ricotta', 'Ricotta'],
  requeijao: ['Requeijão (creamy cheese spread)', 'Queso crema para untar (requeijão)', 'Requeijão (fromage à tartiner)', 'Requeijão (Streichkäse)', 'Requeijão (formaggio spalmabile)'],
  leite: ['Milk', 'Leche', 'Lait', 'Milch', 'Latte'],
  achocolatado: ['Chocolate milk', 'Leche con chocolate', 'Lait chocolaté', 'Kakao mit Milch', 'Latte al cioccolato'],
  cottage: ['Cottage cheese', 'Queso cottage', 'Cottage cheese', 'Hüttenkäse', 'Fiocchi di latte'],

  /* suplementos */
  whey: ['Whey protein', 'Proteína de suero (whey)', 'Protéine whey', 'Whey-Protein', 'Proteine del siero (whey)'],
  'barra-proteina': ['Protein bar', 'Barra de proteína', 'Barre protéinée', 'Proteinriegel', 'Barretta proteica'],

  /* grãos e feijões */
  'feijao-carioca': ['Pinto beans', 'Frijoles pintos', 'Haricots pinto', 'Wachtelbohnen', 'Fagioli pinto'],
  'feijao-preto': ['Black beans', 'Frijoles negros', 'Haricots noirs', 'Schwarze Bohnen', 'Fagioli neri'],
  lentilha: ['Cooked lentils', 'Lentejas cocidas', 'Lentilles cuites', 'Gekochte Linsen', 'Lenticchie lessate'],
  'grao-de-bico': ['Cooked chickpeas', 'Garbanzos cocidos', 'Pois chiches cuits', 'Gekochte Kichererbsen', 'Ceci lessati'],
  tofu: ['Tofu', 'Tofu', 'Tofu', 'Tofu', 'Tofu'],
  ervilha: ['Peas', 'Arvejas (chícharos)', 'Petits pois', 'Erbsen', 'Piselli'],
  amendoim: ['Peanuts', 'Maní (cacahuates)', 'Cacahuètes', 'Erdnüsse', 'Arachidi'],
  pacoca: ['Paçoca (peanut candy)', 'Paçoca (dulce de maní)', 'Paçoca (confiserie à la cacahuète)', 'Paçoca (Erdnusskonfekt)', 'Paçoca (dolcetto di arachidi)'],

  /* pratos prontos brasileiros e outros */
  'feijao-tropeiro': ['Feijão tropeiro (beans with cassava flour and bacon)', 'Feijão tropeiro (frijoles con harina de yuca y tocino)', 'Feijão tropeiro (haricots, farine de manioc et lard)', 'Feijão tropeiro (Bohnen mit Maniokmehl und Speck)', 'Feijão tropeiro (fagioli con farina di manioca e pancetta)'],
  'macarrao-bolonhesa': ['Spaghetti bolognese', 'Espagueti a la boloñesa', 'Spaghetti bolognaise', 'Spaghetti Bolognese', 'Spaghetti alla bolognese'],
  cuscuz: ['Cuscuz (steamed cornmeal)', 'Cuscús de maíz brasileño', 'Couscous de maïs brésilien', 'Brasilianischer Maiscouscous', 'Cuscuz (semola di mais al vapore)'],
  'arroz-carreteiro': ['Arroz carreteiro (rice with dried beef)', 'Arroz carreteiro (arroz con carne seca)', 'Arroz carreteiro (riz au bœuf séché)', 'Arroz carreteiro (Reis mit Trockenfleisch)', 'Arroz carreteiro (riso con carne secca)'],
  baiao: ['Baião de dois (rice and beans with cheese)', 'Baião de dois (arroz y frijoles con queso)', 'Baião de dois (riz et haricots au fromage)', 'Baião de dois (Reis und Bohnen mit Käse)', 'Baião de dois (riso e fagioli al formaggio)'],
  'cuscuz-paulista': ['Cuscuz paulista (savory corn cake)', 'Cuscuz paulista (pastel salado de maíz)', 'Cuscuz paulista (gâteau salé de maïs)', 'Cuscuz paulista (herzhafter Maiskuchen)', 'Cuscuz paulista (sformato salato di mais)'],
  estrogonofe: ['Chicken stroganoff', 'Strogonoff de pollo', 'Stroganoff de poulet', 'Hähnchen-Stroganoff', 'Stroganoff di pollo'],
  'bife-a-cavalo': ['Steak with fried egg', 'Bistec a caballo', 'Steak à cheval', 'Steak mit Spiegelei', 'Bistecca con uovo fritto'],
  legumes: ['Cooked vegetables', 'Verduras cocidas', 'Légumes cuits', 'Gedünstetes Gemüse', 'Verdure lessate'],
  feijoada: ['Feijoada (black bean and pork stew)', 'Feijoada (guiso de frijoles negros y cerdo)', 'Feijoada (ragoût de haricots noirs et porc)', 'Feijoada (Eintopf aus schwarzen Bohnen und Schwein)', 'Feijoada (stufato di fagioli neri e maiale)'],
  virado: ['Virado à paulista (beans, pork chop and egg)', 'Virado à paulista (frijoles, chuleta y huevo)', 'Virado à paulista (haricots, côte de porc et œuf)', 'Virado à paulista (Bohnen, Kotelett und Ei)', 'Virado à paulista (fagioli, braciola e uovo)'],
  'estrogonofe-carne': ['Beef stroganoff', 'Strogonoff de res', 'Bœuf Stroganoff', 'Rinder-Stroganoff', 'Manzo alla Stroganoff'],
  yakisoba: ['Yakisoba', 'Yakisoba', 'Yakisoba', 'Yakisoba', 'Yakisoba'],
  salpicao: ['Brazilian chicken salad', 'Ensalada de pollo brasileña', 'Salade de poulet brésilienne', 'Brasilianischer Hähnchensalat', 'Salpicão (insalata di pollo)'],
  dobradinha: ['Tripe stew', 'Guiso de mondongo', 'Tripes en ragoût', 'Kuttel-Eintopf', 'Trippa in umido'],
  'vaca-atolada': ['Vaca atolada (beef ribs with cassava)', 'Vaca atolada (costilla de res con yuca)', 'Vaca atolada (côtes de bœuf au manioc)', 'Vaca atolada (Rinderrippe mit Maniok)', 'Vaca atolada (costine di manzo con manioca)'],
  vatapa: ['Vatapá (Bahian shrimp and bread purée)', 'Vatapá (crema bahiana de camarón y pan)', 'Vatapá (purée bahianaise de crevettes et pain)', 'Vatapá (bahianisches Garnelen-Brot-Püree)', 'Vatapá (crema bahiana di gamberi e pane)'],
  acaraje: ['Acarajé (black-eyed pea fritter)', 'Acarajé (buñuelo de frijol carita)', 'Acarajé (beignet de haricots cornille)', 'Acarajé (Schwarzaugenbohnen-Krapfen)', 'Acarajé (frittella di fagioli dall’occhio)'],
  manicoba: ['Maniçoba (cassava leaf and pork stew)', 'Maniçoba (guiso de hojas de yuca y cerdo)', 'Maniçoba (ragoût de feuilles de manioc et porc)', 'Maniçoba (Eintopf aus Maniokblättern und Schwein)', 'Maniçoba (stufato di foglie di manioca e maiale)'],
  barreado: ['Barreado (slow-cooked beef stew)', 'Barreado (guiso de res cocido lento)', 'Barreado (bœuf mijoté longuement)', 'Barreado (langsam geschmortes Rindfleisch)', 'Barreado (stufato di manzo a cottura lenta)'],
  charuto: ['Stuffed cabbage roll', 'Hojas de repollo rellenas', 'Feuille de chou farcie', 'Kohlroulade', 'Involtino di cavolo'],
  tabule: ['Tabbouleh', 'Tabulé', 'Taboulé', 'Taboulé', 'Tabulè'],
  carbonara: ['Spaghetti carbonara', 'Espagueti a la carbonara', 'Spaghetti à la carbonara', 'Spaghetti Carbonara', 'Spaghetti alla carbonara'],
  'macarrao-alho': ['Spaghetti with garlic and oil', 'Espagueti al ajo y aceite', 'Spaghetti ail et huile', 'Spaghetti aglio e olio', 'Spaghetti aglio e olio'],
  'macarrao-queijos': ['Four-cheese pasta', 'Pasta a los cuatro quesos', 'Pâtes aux quatre fromages', 'Nudeln mit vier Käsesorten', 'Pasta ai quattro formaggi'],
  'lasanha-carne': ['Beef lasagna', 'Lasaña de carne', 'Lasagnes à la viande', 'Lasagne mit Rindfleisch', 'Lasagne al ragù'],
  'lasanha-frango': ['Chicken lasagna', 'Lasaña de pollo', 'Lasagnes au poulet', 'Lasagne mit Hähnchen', 'Lasagne al pollo'],
  'lasanha-presunto': ['Ham and cheese lasagna', 'Lasaña de jamón y queso', 'Lasagnes jambon-fromage', 'Lasagne mit Schinken und Käse', 'Lasagne prosciutto e formaggio'],
  nhoque: ['Gnocchi with tomato sauce', 'Ñoquis con salsa de tomate', 'Gnocchis à la sauce tomate', 'Gnocchi mit Tomatensoße', 'Gnocchi al pomodoro'],
  'parmegiana-frango': ['Chicken parmigiana', 'Pollo a la parmesana', 'Poulet à la parmigiana', 'Hähnchen-Parmigiana', 'Cotoletta di pollo alla parmigiana'],
  'parmegiana-carne': ['Beef parmigiana', 'Milanesa de res a la napolitana', 'Escalope de bœuf à la parmigiana', 'Rinderschnitzel Parmigiana', 'Cotoletta di manzo alla parmigiana'],
  'bife-milanesa': ['Breaded beef cutlet', 'Milanesa de res', 'Escalope de bœuf panée', 'Paniertes Rinderschnitzel', 'Cotoletta di manzo impanata'],
  galinhada: ['Galinhada (chicken and rice)', 'Galinhada (arroz con pollo)', 'Galinhada (riz au poulet)', 'Galinhada (Hähnchen mit Reis)', 'Galinhada (riso con pollo)'],
  'escondidinho-carne': ['Ground beef and cassava pie', 'Pastel de carne molida y puré de yuca', 'Escondidinho (hachis parmentier de manioc au bœuf)', 'Hackfleisch-Maniok-Auflauf', 'Pasticcio di macinato e manioca'],
  'escondidinho-carne-seca': ['Dried beef and cassava pie', 'Pastel de carne seca y puré de yuca', 'Escondidinho (hachis parmentier de manioc au bœuf séché)', 'Trockenfleisch-Maniok-Auflauf', 'Pasticcio di carne secca e manioca'],
  'escondidinho-frango': ['Chicken and cassava pie', 'Pastel de pollo y puré de yuca', 'Escondidinho (hachis parmentier de manioc au poulet)', 'Hähnchen-Maniok-Auflauf', 'Pasticcio di pollo e manioca'],
  'panqueca-carne': ['Beef-filled crepe', 'Panqueque de carne', 'Crêpe roulée à la viande', 'Pfannkuchen mit Hackfleisch', 'Crespella alla carne'],
  'panqueca-frango': ['Chicken-filled crepe', 'Panqueque de pollo', 'Crêpe roulée au poulet', 'Pfannkuchen mit Hähnchen', 'Crespella al pollo'],
  'torta-frango': ['Chicken pie', 'Pastel de pollo', 'Tourte au poulet', 'Hähnchenpastete', 'Torta salata di pollo'],
  'crepe-carne': ['Beef crepe', 'Crepe de carne', 'Crêpe à la viande', 'Crêpe mit Rindfleisch', 'Crêpe alla carne'],
  'crepe-frango': ['Chicken crepe', 'Crepe de pollo', 'Crêpe au poulet', 'Crêpe mit Hähnchen', 'Crêpe al pollo'],
  'crepe-queijo': ['Cheese crepe', 'Crepe de queso', 'Crêpe au fromage', 'Käse-Crêpe', 'Crêpe al formaggio'],
  'pizza-mussarela': ['Cheese pizza', 'Pizza de mozzarella', 'Pizza à la mozzarella', 'Käsepizza', 'Pizza alla mozzarella'],
  'pizza-calabresa': ['Calabresa pizza (smoked sausage and onion)', 'Pizza de calabresa (salchicha ahumada y cebolla)', 'Pizza calabresa (saucisse fumée et oignon)', 'Pizza Calabresa (Räucherwurst und Zwiebeln)', 'Pizza calabresa (salsiccia affumicata e cipolla)'],
  'pizza-frango': ['Chicken and cream cheese pizza', 'Pizza de pollo con queso crema', 'Pizza poulet et fromage frais', 'Pizza mit Hähnchen und Frischkäse', 'Pizza pollo e formaggio cremoso'],
  'pizza-portuguesa': ['Ham, egg and olive pizza', 'Pizza de jamón, huevo y aceitunas', 'Pizza jambon, œuf et olives', 'Pizza mit Schinken, Ei und Oliven', 'Pizza prosciutto, uovo e olive'],
  moqueca: ['Moqueca (Brazilian fish stew)', 'Moqueca (guiso brasileño de pescado)', 'Moqueca (ragoût de poisson brésilien)', 'Moqueca (brasilianischer Fischeintopf)', 'Moqueca (zuppa di pesce brasiliana)'],
  'bobo-camarao': ['Bobó de camarão (shrimp in cassava cream)', 'Bobó de camarão (camarones en crema de yuca)', 'Bobó de camarão (crevettes à la crème de manioc)', 'Bobó de camarão (Garnelen in Maniokcreme)', 'Bobó de camarão (gamberi in crema di manioca)'],
  'bacalhau-natas': ['Salt cod with potatoes', 'Bacalao con papas', 'Morue aux pommes de terre', 'Klippfisch (Bacalhau) mit Kartoffeln', 'Baccalà con patate'],
  sushi: ['Salmon sushi', 'Sushi de salmón', 'Sushi au saumon', 'Lachs-Sushi', 'Sushi al salmone'],
  'risoto-camarao': ['Shrimp risotto', 'Risotto de camarones', 'Risotto aux crevettes', 'Garnelenrisotto', 'Risotto ai gamberi'],
  'risoto-frango': ['Chicken risotto', 'Risotto de pollo', 'Risotto au poulet', 'Hähnchenrisotto', 'Risotto al pollo'],
  canja: ['Chicken and rice soup', 'Sopa de pollo con arroz', 'Soupe de poulet au riz', 'Hühnersuppe mit Reis', 'Minestra di pollo e riso'],
  'sopa-legumes': ['Vegetable soup', 'Sopa de verduras', 'Soupe de légumes', 'Gemüsesuppe', 'Minestra di verdure'],
  'sopa-feijao': ['Bean soup', 'Caldo de frijoles', 'Soupe de haricots', 'Bohnensuppe', 'Zuppa di fagioli'],
  'sopa-carne': ['Beef and vegetable soup', 'Sopa de res con verduras', 'Soupe de bœuf aux légumes', 'Rindfleischsuppe mit Gemüse', 'Zuppa di manzo e verdure'],
  'ramen-carne': ['Ramen with beef and egg', 'Ramen con carne y huevo', 'Ramen au bœuf et à l’œuf', 'Ramen mit Rindfleisch und Ei', 'Ramen con manzo e uovo'],
  'temaki-salmao': ['Salmon temaki', 'Temaki de salmón', 'Temaki au saumon', 'Lachs-Temaki', 'Temaki al salmone'],
  'poke-salmao': ['Salmon poke bowl', 'Poke de salmón', 'Poke bowl au saumon', 'Lachs-Poke-Bowl', 'Poke al salmone'],
  'gyoza-porco': ['Pork gyoza', 'Gyozas de cerdo', 'Gyozas au porc', 'Gyoza mit Schweinefleisch', 'Gyoza di maiale'],
  'frango-xadrez': ['Kung pao chicken', 'Pollo kung pao', 'Poulet kung pao', 'Kung-Pao-Hähnchen', 'Pollo kung pao'],
  'arroz-frito': ['Egg fried rice', 'Arroz frito con huevo', 'Riz cantonais à l’œuf', 'Gebratener Reis mit Ei', 'Riso saltato con uovo'],
  'pad-thai-camarao': ['Shrimp pad thai', 'Pad thai de camarones', 'Pad thaï aux crevettes', 'Pad Thai mit Garnelen', 'Pad thai ai gamberi'],
  bibimbap: ['Bibimbap', 'Bibimbap', 'Bibimbap', 'Bibimbap', 'Bibimbap'],
  'taco-carne': ['Beef taco', 'Taco de carne', 'Taco au bœuf', 'Taco mit Rindfleisch', 'Taco di manzo'],
  'burrito-frango': ['Chicken burrito', 'Burrito de pollo', 'Burrito au poulet', 'Hähnchen-Burrito', 'Burrito di pollo'],
  'quesadilla-queijo': ['Cheese quesadilla', 'Quesadilla de queso', 'Quesadilla au fromage', 'Käse-Quesadilla', 'Quesadilla al formaggio'],
  'chili-carne': ['Chili con carne', 'Chili con carne', 'Chili con carne', 'Chili con Carne', 'Chili con carne'],
  falafel: ['Falafel', 'Falafel', 'Falafels', 'Falafel', 'Falafel'],
  'shawarma-frango': ['Chicken shawarma', 'Shawarma de pollo', 'Chawarma au poulet', 'Hähnchen-Shawarma', 'Shawarma di pollo'],
  'kebab-carne': ['Beef kebab', 'Kebab de carne', 'Kebab au bœuf', 'Döner mit Rindfleisch', 'Kebab di manzo'],
  'souvlaki-frango': ['Chicken souvlaki', 'Souvlaki de pollo', 'Souvlaki de poulet', 'Hähnchen-Souvlaki', 'Souvlaki di pollo'],
  'tikka-masala': ['Chicken tikka masala', 'Pollo tikka masala', 'Poulet tikka masala', 'Chicken Tikka Masala', 'Pollo tikka masala'],
  'curry-grao-de-bico': ['Chickpea curry', 'Curry de garbanzos', 'Curry de pois chiches', 'Kichererbsen-Curry', 'Curry di ceci'],
  'paella-frutos-do-mar': ['Seafood paella', 'Paella de mariscos', 'Paella aux fruits de mer', 'Meeresfrüchte-Paella', 'Paella di mare'],
  'tortilla-espanhola': ['Spanish tortilla (potato omelet)', 'Tortilla española', 'Tortilla espagnole', 'Spanische Tortilla', 'Tortilla spagnola'],
  'quiche-queijo': ['Cheese quiche', 'Quiche de queso', 'Quiche au fromage', 'Käsequiche', 'Quiche al formaggio'],
  'mac-and-cheese': ['Mac and cheese', 'Macarrones con queso', 'Macaroni au fromage', 'Makkaroni mit Käse', 'Maccheroni al formaggio'],
  'ceviche-peixe': ['Fish ceviche', 'Ceviche de pescado', 'Ceviche de poisson', 'Fisch-Ceviche', 'Ceviche di pesce'],

  /* arroz, massas e pães */
  arroz: ['White rice', 'Arroz blanco', 'Riz blanc', 'Weißer Reis', 'Riso bianco'],
  'arroz-integral': ['Brown rice', 'Arroz integral', 'Riz complet', 'Naturreis', 'Riso integrale'],
  macarrao: ['Cooked pasta', 'Pasta cocida', 'Pâtes cuites', 'Gekochte Nudeln', 'Pasta cotta'],
  'pao-frances': ['Bread roll', 'Pan blanco (bolillo)', 'Petit pain', 'Brötchen', 'Panino'],
  'pao-integral': ['Whole wheat sandwich bread', 'Pan integral de molde', 'Pain de mie complet', 'Vollkorntoast', 'Pancarrè integrale'],
  aveia: ['Rolled oats', 'Avena en hojuelas', 'Flocons d’avoine', 'Haferflocken', 'Fiocchi d’avena'],
  tapioca: ['Tapioca crepe', 'Crepe de tapioca', 'Crêpe de tapioca', 'Tapioka-Fladen', 'Crespella di tapioca'],
  'pao-de-queijo': ['Pão de queijo (cheese bread)', 'Pão de queijo (pan de queso)', 'Pão de queijo (pain au fromage)', 'Pão de queijo (Käsebrötchen)', 'Pão de queijo (panino al formaggio)'],
  cereal: ['Breakfast cereal', 'Cereal de desayuno', 'Céréales du petit-déjeuner', 'Frühstücksflocken', 'Cereali da colazione'],
  'pao-sovado': ['Sweet bread roll', 'Pan dulce', 'Brioche', 'Süßes Brötchen', 'Panino dolce'],
  'pao-aveia': ['Oat bread', 'Pan de avena', 'Pain à l’avoine', 'Haferbrot', 'Pane all’avena'],
  milho: ['Sweet corn', 'Granos de maíz dulce', 'Maïs doux', 'Zuckermais', 'Mais dolce'],
  farofa: ['Farofa (toasted cassava flour)', 'Farofa (harina de yuca tostada)', 'Farofa (farine de manioc grillée)', 'Farofa (geröstetes Maniokmehl)', 'Farofa (farina di manioca tostata)'],
  granola: ['Granola', 'Granola', 'Granola', 'Granola', 'Granola'],
  torrada: ['Toast', 'Pan tostado', 'Biscotte', 'Zwieback', 'Fetta biscottata'],
  'biscoito-salgado': ['Saltine cracker', 'Galleta salada', 'Cracker', 'Cracker', 'Cracker'],
  'biscoito-recheado': ['Sandwich cookie', 'Galleta rellena', 'Biscuit fourré', 'Doppelkeks', 'Biscotto farcito'],
  'bolo-chocolate': ['Chocolate cake', 'Pastel de chocolate', 'Gâteau au chocolat', 'Schokoladenkuchen', 'Torta al cioccolato'],
  pipoca: ['Popcorn', 'Palomitas de maíz', 'Pop-corn', 'Popcorn', 'Popcorn'],

  /* verduras e legumes */
  'salada-folhas': ['Green salad', 'Ensalada verde', 'Salade verte', 'Blattsalat', 'Insalata verde'],
  tomate: ['Tomato', 'Tomate', 'Tomate', 'Tomate', 'Pomodoro'],
  brocolis: ['Broccoli', 'Brócoli', 'Brocoli', 'Brokkoli', 'Broccoli'],
  cenoura: ['Cooked carrot', 'Zanahoria cocida', 'Carottes cuites', 'Gekochte Karotten', 'Carote lessate'],
  beterraba: ['Cooked beet', 'Remolacha cocida', 'Betterave cuite', 'Gekochte Rote Bete', 'Barbabietola cotta'],
  couve: ['Sautéed collard greens', 'Col rizada salteada', 'Chou vert sauté', 'Gedünsteter Grünkohl', 'Cavolo nero saltato'],
  'couve-flor': ['Cauliflower', 'Coliflor', 'Chou-fleur', 'Blumenkohl', 'Cavolfiore'],
  espinafre: ['Sautéed spinach', 'Espinacas salteadas', 'Épinards sautés', 'Gedünsteter Spinat', 'Spinaci saltati'],
  abobora: ['Cooked pumpkin', 'Calabaza cocida', 'Potiron cuit', 'Gekochter Kürbis', 'Zucca cotta'],
  chuchu: ['Cooked chayote', 'Chayote cocido', 'Chayote cuite', 'Gekochte Chayote', 'Chayote lessata'],
  vagem: ['Green beans', 'Ejotes (vainitas, chauchas)', 'Haricots verts', 'Grüne Bohnen', 'Fagiolini'],
  quiabo: ['Okra', 'Okra', 'Gombo', 'Okra', 'Gombo'],
  repolho: ['Cabbage', 'Repollo', 'Chou blanc', 'Weißkohl', 'Cavolo cappuccio'],
  pepino: ['Cucumber', 'Pepino', 'Concombre', 'Gurke', 'Cetriolo'],
  mandioca: ['Boiled cassava', 'Yuca cocida', 'Manioc bouilli', 'Gekochter Maniok', 'Manioca bollita'],
  'mandioca-frita': ['Cassava fries', 'Yuca frita', 'Frites de manioc', 'Frittierter Maniok', 'Manioca fritta'],
  batata: ['Boiled potato', 'Papa cocida', 'Pomme de terre à l’eau', 'Salzkartoffel', 'Patata lessa'],
  'batata-frita': ['French fries', 'Papas fritas', 'Frites', 'Pommes frites', 'Patatine fritte'],
  'batata-doce': ['Sweet potato', 'Camote (batata dulce)', 'Patate douce', 'Süßkartoffel', 'Patata dolce'],
  palmito: ['Hearts of palm', 'Palmito', 'Cœurs de palmier', 'Palmherzen', 'Cuori di palma'],
  pimentao: ['Bell pepper', 'Pimiento morrón', 'Poivron', 'Paprika', 'Peperone'],

  /* frutas */
  banana: ['Banana', 'Banana (plátano)', 'Banane', 'Banane', 'Banana'],
  maca: ['Apple', 'Manzana', 'Pomme', 'Apfel', 'Mela'],
  abacate: ['Avocado', 'Aguacate', 'Avocat', 'Avocado', 'Avocado'],
  abacaxi: ['Pineapple', 'Piña', 'Ananas', 'Ananas', 'Ananas'],
  goiaba: ['Guava', 'Guayaba', 'Goyave', 'Guave', 'Guava'],
  laranja: ['Orange', 'Naranja', 'Orange', 'Orange', 'Arancia'],
  mamao: ['Papaya', 'Papaya', 'Papaye', 'Papaya', 'Papaya'],
  manga: ['Mango', 'Mango', 'Mangue', 'Mango', 'Mango'],
  melancia: ['Watermelon', 'Sandía', 'Pastèque', 'Wassermelone', 'Anguria'],
  morango: ['Strawberry', 'Fresa', 'Fraise', 'Erdbeere', 'Fragola'],
  uva: ['Grapes', 'Uvas', 'Raisin', 'Weintrauben', 'Uva'],
  'suco-laranja': ['Orange juice', 'Jugo de naranja', 'Jus d’orange', 'Orangensaft', 'Succo d’arancia'],

  /* castanhas e sementes */
  'castanha-caju': ['Cashews', 'Castañas de cajú (nueces de la India)', 'Noix de cajou', 'Cashewkerne', 'Anacardi'],
  'castanha-para': ['Brazil nut', 'Nuez de Brasil', 'Noix du Brésil', 'Paranuss', 'Noce del Brasile'],
  'pasta-amendoim': ['Peanut butter', 'Crema de maní', 'Beurre de cacahuète', 'Erdnussbutter', 'Burro di arachidi'],
  amendoa: ['Almonds', 'Almendras', 'Amandes', 'Mandeln', 'Mandorle'],

  /* doces e lanches */
  chocolate: ['Milk chocolate', 'Chocolate con leche', 'Chocolat au lait', 'Milchschokolade', 'Cioccolato al latte'],
  'barra-cereal': ['Cereal bar', 'Barra de cereal', 'Barre de céréales', 'Müsliriegel', 'Barretta di cereali'],
  'sanduiche-frango': ['Chicken sandwich', 'Sándwich de pollo', 'Sandwich au poulet', 'Hähnchen-Sandwich', 'Panino al pollo'],
  'sanduiche-atum': ['Tuna sandwich', 'Sándwich de atún', 'Sandwich au thon', 'Thunfisch-Sandwich', 'Panino al tonno'],
  'sanduiche-peru': ['Turkey sandwich', 'Sándwich de pavo', 'Sandwich à la dinde', 'Truthahn-Sandwich', 'Panino al tacchino'],
  'x-salada': ['Cheeseburger with lettuce and tomato', 'Hamburguesa con queso y ensalada', 'Cheeseburger salade-tomate', 'Cheeseburger mit Salat und Tomate', 'Cheeseburger con insalata e pomodoro'],
  'misto-quente': ['Grilled ham and cheese', 'Sándwich tostado de jamón y queso', 'Croque-monsieur', 'Schinken-Käse-Toast', 'Toast prosciutto e formaggio'],
  'tapioca-frango': ['Chicken tapioca crepe', 'Crepe de tapioca con pollo', 'Crêpe de tapioca au poulet', 'Tapioka-Fladen mit Hähnchen', 'Crespella di tapioca al pollo'],
  'tapioca-queijo': ['Cheese tapioca crepe', 'Crepe de tapioca con queso', 'Crêpe de tapioca au fromage', 'Tapioka-Fladen mit Käse', 'Crespella di tapioca al formaggio'],
  esfiha: ['Meat sfiha', 'Esfiha de carne', 'Sfiha à la viande', 'Sfiha mit Fleisch', 'Sfiha di carne'],
  'pastel-carne': ['Fried beef pastry', 'Empanada frita de carne', 'Chausson frit à la viande', 'Frittierte Teigtasche mit Fleisch', 'Fagottino fritto di carne'],
  'pastel-queijo': ['Fried cheese pastry', 'Empanada frita de queso', 'Chausson frit au fromage', 'Frittierte Teigtasche mit Käse', 'Fagottino fritto al formaggio'],
  croquete: ['Beef croquette', 'Croqueta de carne', 'Croquette de viande', 'Fleischkrokette', 'Crocchetta di carne'],
  'empada-frango': ['Chicken hand pie', 'Empanadita de pollo', 'Petit pâté au poulet', 'Hähnchen-Pastetchen', 'Tortino di pollo'],
  'guacamole-nachos': ['Guacamole with tortilla chips', 'Guacamole con nachos (totopos)', 'Guacamole et chips de maïs', 'Guacamole mit Tortilla-Chips', 'Guacamole con nachos'],
  'homus-pao': ['Hummus with pita', 'Hummus con pan árabe', 'Houmous et pain pita', 'Hummus mit Fladenbrot', 'Hummus con pane pita'],
  'wrap-frango': ['Chicken wrap', 'Wrap de pollo', 'Wrap au poulet', 'Hähnchen-Wrap', 'Wrap al pollo'],

  /* café da manhã */
  'mingau-aveia': ['Oatmeal porridge', 'Avena cocida con leche', 'Porridge d’avoine', 'Haferbrei', 'Porridge d’avena'],
  'vitamina-banana': ['Banana smoothie (with milk)', 'Licuado de plátano', 'Smoothie banane-lait', 'Bananenmilch', 'Frullato di banana e latte'],
  'panqueca-americana': ['Pancakes', 'Pancakes (hot cakes)', 'Pancakes', 'Pancakes', 'Pancake'],
  waffle: ['Waffle', 'Waffle', 'Gaufre', 'Waffel', 'Waffle'],
  crepioca: ['Crepioca (egg and tapioca crepe) with cheese', 'Crepioca (crepe de huevo y tapioca) con queso', 'Crepioca (crêpe œuf-tapioca) au fromage', 'Crepioca (Ei-Tapioka-Fladen) mit Käse', 'Crepioca (crespella di uovo e tapioca) al formaggio'],
  'iogurte-granola': ['Yogurt with granola and fruit', 'Yogur con granola y fruta', 'Yaourt, granola et fruits', 'Joghurt mit Granola und Obst', 'Yogurt con granola e frutta'],
  'smoothie-proteico': ['Banana whey smoothie', 'Batido de plátano con whey', 'Smoothie banane et whey', 'Bananen-Whey-Smoothie', 'Frullato di banana con whey'],
  'torrada-abacate-ovo': ['Avocado toast with egg', 'Pan tostado con aguacate y huevo', 'Toast avocat et œuf', 'Avocado-Toast mit Ei', 'Pane tostato con avocado e uovo'],
  shakshuka: ['Shakshuka', 'Shakshuka', 'Chakchouka', 'Shakshuka', 'Shakshuka'],
  'croissant-presunto-queijo': ['Ham and cheese croissant', 'Croissant de jamón y queso', 'Croissant jambon-fromage', 'Schinken-Käse-Croissant', 'Cornetto prosciutto e formaggio'],
  'bagel-cream-cheese': ['Bagel with cream cheese', 'Bagel con queso crema', 'Bagel au fromage frais', 'Bagel mit Frischkäse', 'Bagel con formaggio spalmabile'],
  'sanduiche-ovo': ['Egg sandwich', 'Sándwich de huevo', 'Sandwich à l’œuf', 'Eiersandwich', 'Panino con uovo'],
  'acai-tigela': ['Açaí bowl', 'Bowl de açaí', 'Bol d’açaí', 'Açaí-Bowl', 'Açaí bowl'],
};
